### ISSUE TITLE
#16 - Add a Drawer to a screen - 在屏幕上添加一个 Drawer

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#100]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/drawer.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/design/drawer.html

建议完成时间：1 - 3 天

**Comment by Vadaski** [comment]
申请翻译该文档 翻译者@MzoneCL

**Comment by chenglu** [comment]
谢谢鑫磊的组织，谢谢译者 @MzoneCL 谢谢你们两位的时间！

**Comment by chenglu** [comment]
谢谢译者，谢谢 @noahziheng 帮忙 review，该任务已经完成并登记，这里我就 close 这个 issue 啦。
谢谢！
