### ISSUE TITLE
[PAGE ISSUE]: '路由和导航'

### ISSUE THREAD

**Issue by Lucaziki** [cfug/flutter.cn#1006]
### 页面 URL

https://flutter.cn/docs/development/ui/navigation/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/development/ui/navigation/index.md

### 描述问题

未翻译为中文

### 期望如何修复

完成翻译

**Comment by chenglu** [comment]
@Nayuta403 这篇需要做成新的任务，看起来不像是这次文档迁移覆盖掉的内容。

**Comment by Nayuta403** [comment]
> 

GET

**Comment by Nayuta403** [comment]
周末我处理了吧
