### ISSUE TITLE
#17 - Displaying SnackBars - 显示 SnackBars

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#101]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/snackbars.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/design/snackbars.html

建议完成时间：1 - 3 天

**Comment by linhou** [comment]
认领任务

**Comment by chenglu** [comment]
辛苦了，感谢～

**Comment by inferjay** [comment]
重新认领此文档
预计完成时间 5 月 16 日。

**Comment by Jin-zz** [comment]
感谢大家的对此篇翻译的贡献
#17 - Displaying SnackBars - 显示 SnackBars 已经圆满完成啦

**Comment by Jin-zz** [comment]
感谢大家对此篇翻译的贡献~#17已经圆满完成啦
