### ISSUE TITLE
[PAGE ISSUE]: '集成测试介绍'

### ISSUE THREAD

**Issue by CivelXu** [cfug/flutter.cn#1011]
### 页面 URL

https://flutter.cn/docs/cookbook/testing/integration/introduction/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/cookbook/testing/integration/introduction.md

### 描述问题

 flutter_driver方案 ->  integration_test方案 文档该更新了

### 附加信息

https://docs.flutter.dev/cookbook/testing/integration/introduction

**Comment by chenglu** [comment]
收到，我会进行一次文档同步并修复这个 issue。
