### ISSUE TITLE
[PAGE ISSUE]: '使用内存视图 (Memory view)'

### ISSUE THREAD

**Issue by Nayuta403** [cfug/flutter.cn#1012]
### 页面 URL

https://flutter.cn/docs/development/tools/devtools/memory/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/development/tools/devtools/memory.md

### 描述问题

![image](https://user-images.githubusercontent.com/40540394/143864925-46f741c5-2b07-42b6-a6f7-60dedb99f4b4.png)
看起来标签格式出现较多问题

**Comment by chenglu** [comment]
@asnowwolf 雪狼兄和 @MeandNi 加康帮忙看看？
