### ISSUE TITLE
[Page issue] {https://flutter.cn/docs/development/add-to-app/ios/project-setup}

### ISSUE THREAD

**Issue by haohaoyin** [cfug/flutter.cn#1015]
### 页面 URL

https://flutter.cn/docs/development/add-to-app/ios/project-setup

### 描述问题

在Xcode13上 根据文档中的使用CocoaPods和Flutter SDK 集成到原生iOS项目中的步骤进行集成后 在iOS15真机上运行会直接crash。

>  Library not loaded: @rpath/App.framework/App
  Referenced from: /private/var/containers/Bundle/Application/D0F18BF7-C30D-4722-AA23-366A407536C5/frameworkTest.app/frameworkTest

### 期望如何修复

希望可以将如何解决这个crash的步骤也附上

### 附加信息

MacOS 12.0.1
iOS 15
Xcode 13

**Comment by AlexV525** [comment]
根据你的描述，应该不属于页面问题，而且内容也不应该导致 crash。请向 [上游](https://github.com/flutter/website) 提交问题。
