### ISSUE TITLE
[PAGE ISSUE]: '在 Linux 操作系统上安装和配置 Flutter 开发环境'

### ISSUE THREAD

**Issue by 1191000606** [cfug/flutter.cn#1019]
### 页面 URL

https://flutter.cn/docs/get-started/install/linux#update-your-path

### 页面源地址

https://github.com/cfug/flutter.cn/blob/master/src/get-started/install/linux.md

### 描述问题

在“更新你的环境变量”部分第3点，“将 [PATH_TO_FLUTTER_GIT_DIRECTORY] 改到你 clone Flutter 的 git 仓库目录下。”，此处我感觉应该是“将 [PATH_TO_FLUTTER_GIT_DIRECTORY] 改为你 clone Flutter 的 git 仓库目录。”，但还是有点不精确，我觉得“将 [PATH_TO_FLUTTER_GIT_DIRECTORY] 改到你的Flutter目录”较好

**Comment by chenglu** [comment]
![image](https://user-images.githubusercontent.com/2258420/146019625-78eb0e4b-374d-48df-a1b2-99e8b50bb7e0.png)

这里的中文部分应该将 `[PATH_TO_FLUTTER_GIT_DIRECTORY]` 修改为 `[PATH_OF_FLUTTER_GIT_DIRECTORY]`，以保持上下文的一致。

至于 @1191000606 一帆提到的这个，我觉得可以简单修改一下措辞。比如：
并将下面命令行里 `[PATH_OF_FLUTTER_GIT_DIRECTORY]` 修改为你通过 `git clone` 命令检出的 Flutter 仓库目录地址，或者通过下载 Flutter SDK 压缩包解压之后的目录地址。

**Comment by 1191000606** [comment]
您这个翻译我感觉挺好

**Comment by chenglu** [comment]
OK，我稍后提交一个 PR 修复这个问题，谢谢你的提出！
