### ISSUE TITLE
#19 - Updating the UI based on orientation - 根据屏幕方向更新界面

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#102]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/orientation.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/design/orientation.html

建议完成时间：1 - 3 天

**Comment by hrt96** [comment]
认领该任务，预计 1 - 3 天

**Comment by chenglu** [comment]
谢谢 @hrt96 的时间和贡献～

**Comment by Jin-zz** [comment]
helo! @hrt96 翻译进度如何呢，翻译完的话可以提交 PR 啦
要是遇到问题的话可以一起讨论看看！
辛苦啦 再次感谢~

**Comment by Jin-zz** [comment]
@hrt96 请注意一下完成时间哦~

**Comment by cfug-dev** [comment]
该稿件收回。
