### ISSUE TITLE
[PAGE ISSUE]: '编写第一个 Flutter 应用'

### ISSUE THREAD

**Issue by ohalo** [cfug/flutter.cn#1026]
### 页面 URL

https://flutter.cn/docs/get-started/codelab/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/get-started/codelab.md

### 描述问题

第一步：创建初始化工程

---

    观察和分析
        主函数（main）使用了 (=>) 符号，这是 Dart 中单行函数或方法的简写。
        
但是在主函数（main）中并没有使用(=>) 符号，以下是相关的代码，不知道作者的意思是在哪里的main函数中有使用？
        
```
void main() {
  runApp(const MyApp());
}

```
[（参考了原网站：https://docs.flutter.dev/get-started/codelab）](https://docs.flutter.dev/get-started/codelab)也没有发现关于这一段的描述。原网站信息：

- This example creates a Material app. Material is a visual design language that is standard on mobile and the web. Flutter offers a rich set of Material widgets. It’s a good idea to have a uses-material-design: true entry in the flutter section of your pubspec.yaml file. This will allow you to use more features of Material, such as their set of predefined Icons.
- The app extends StatelessWidget, which makes the app itself a widget. In Flutter, almost everything is a widget, including alignment, padding, and layout.
- The Scaffold widget, from the Material library, provides a default app bar, and a body property that holds the widget tree for the home screen. The widget subtree can be quite complex.
- A widget’s main job is to provide a build() method that describes how to display the widget in terms of other, lower level widgets.
- The body for this example consists of a Center widget containing a Text child widget. The Center widget aligns its widget subtree to the center of the screen.

**Comment by AlexV525** [comment]
最新的内容中没有找到相关内容。可否再次验证是否存在？如果存在烦请提供下截图。

**Comment by ohalo** [comment]
应该是之前的页面遗留问题，新的内容里面的代码是正确的

**Comment by AlexV525** [comment]
> 新的内容里面的代码是正确的

感谢协助验证~
