### ISSUE TITLE
[PAGE ISSUE]: '开发体验初探'

### ISSUE THREAD

**Issue by ohalo** [cfug/flutter.cn#1029]
### 页面 URL

https://flutter.cn/docs/get-started/test-drive/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/get-started/test-drive/index.md

### 描述问题

看了你的辛苦成果，很是受益，我见Android Studio and IntelliJ部分没有翻译，我翻译了一下，你看看有什么问题没有。
其中有两点问题：
1.  Verify the Flutter SDK path specifies the SDK’s location (select Install SDK… if the text field is blank). 
2. In the target selector, select an Android device for running the app. If none are listed as available, select Tools > AVD Manager and create one there. For details, see Managing AVDs.

第一个问题，在于我没有在new flutter project上找到安装sdk的地方，是我自己按照说明文档安装的flutter sdk 
第二个问题，我的andriod studio 上面没有Tools > AVD Manager 这个菜单，只有Device Manager这个菜单，我是按照文档上下载的andriod studio 

### 期望如何修复

[flutter 开发初体验](https://flutter.cn/docs/get-started/test-drive?tab=androidstudio)

Android Studio and IntelliJ

1. Open the IDE and select Create New Flutter Project.
打开 IDE 单击File菜单找到New，并选择"New Flutter Project"。
2. Select Flutter Application as the project type. Then click Next. 
选择"Flutter 应用程序"作为项目类型。然后单击"下一步"。
3. Verify the Flutter SDK path specifies the SDK’s location (select Install SDK… if the text field is blank). 
验证 Flutter SDK 路径是否指定了 SDK 的位置（如果文本框为空，请安装 SDK，或者指定本地安装路径）。
4. Enter a project name (for example, myapp). Then click Next.  
输入项目名称（例如：myapp），然后单击"下一步"。
5. Click Finish. 
单击"Finish"。
6. Wait for Android Studio to install the SDK and create the project. 
等待 Android Studio 安装 SDK 并创建项目。

The above commands create a Flutter project directory called myapp that contains a simple demo app that uses Material Components.
以上的命令是创建一个名叫myapp的 Flutter 项目，它包含一个简单的示例应用，这个应用使用的是[“Material组件”](https://material-io.cn/design)

小提示 The code for your app is in lib/main.dart. For a high-level description of what each code block does, see the comments at the top of that file.
应用程序的代码在lib/main.dart中。对于每个代码块的功能的高层次的描述，请参阅该文件顶部的注释。

Run the app
运行应用
1. Locate the main Android Studio toolbar:
定位于Android Studio的工具栏
2. In the target selector, select an Android device for running the app. If none are listed as available, select Tools > AVD Manager and create one there. For details, see Managing AVDs.
在target selector中，选择运行应用程序的Android设备。如果没有列出可用的，选择Tools > Device Manager并在那里创建一个，详细操作请参见[“创建和管理虚拟设备”](https://developer.android.google.cn/studio/run/managing-avds)。
3. Click the run icon in the toolbar, or invoke the menu item Run > Run.
单击工具栏中的“运行”图标，或调用菜单项“运行>运行”

**Comment by AlexV525** [comment]
这部分的流程已经发生改变，我先给上游提交后再来回溯。

**Comment by AlexV525** [comment]
https://github.com/flutter/website/pull/6937
