### ISSUE TITLE
#20 - Using Themes to share colors and font styles - 使用 Themes 统一颜色和字体风格

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#103]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/themes.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/design/themes.html

建议完成时间：2 - 3 天

**Comment by vinciarts** [comment]
认领这个任务，预计20号之前完成，这礼拜超级的忙！！

**Comment by chenglu** [comment]
感谢忙里抽闲的锅锅，辛苦啦～

**Comment by chenglu** [comment]
👍
