### ISSUE TITLE
编写你的第一个 Flutter App  [2/2] 

### ISSUE THREAD

**Issue by cuilanxin** [cfug/flutter.cn#1033]
### 页面 URL

https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt2-cn/index.html#0

### 页面源地址

https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt2-cn/index.html#0

### 描述问题

<img width="391" alt="WX20220217-105110@2x" src="https://user-images.githubusercontent.com/57083007/154395448-82981c46-9f21-4bf5-96b7-61f612661785.png">

# 我勾选不了第二个选项 `我只开发过基于移动网页的应用`，当我点击这个选项的时候会勾选到第一个上面

### 期望如何修复

可以点击这个选项

**Comment by chenglu** [comment]
![image](https://user-images.githubusercontent.com/2258420/154396732-ed413b0c-6e57-491b-97ee-98219ca45df0.png)

刷新一下页面，应该已经 OK 啦～

**Comment by cuilanxin** [comment]
好的谢谢
