### ISSUE TITLE
[PAGE ISSUE]: '{页面的左侧菜单栏不会自动定位}'

### ISSUE THREAD

**Issue by wcldyx** [cfug/flutter.cn#1037]
### 页面 URL

https://flutter.cn/docs/development/ui/layout

### 描述问题

页面的左侧菜单栏不会自动定位,

**Comment by chenglu** [comment]
初步研究了一下，应该是 CN repo 里的 site-shared 没有与上游同步的原因造成的，会尽快解决。

**Comment by chenglu** [comment]
尴尬了，并木有解决，我明天再看看～

**Comment by AlexV525** [comment]
Fixed by #1040.
