### ISSUE TITLE
#21 - Using custom fonts - 使用自定义字体

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#104]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/fonts.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/design/fonts.html

建议完成时间：2 - 3 天

**Comment by Vadaski** [comment]
申请翻译

**Comment by chenglu** [comment]
建议提交之前多多审稿，避免出现明显失误哈 ;-)

**Comment by Vadaski** [comment]
好德

**Comment by chenglu** [comment]
谢谢鑫磊的时间，该任务已完成。
