### ISSUE TITLE
[Page issue] https://flutter.cn/docs/development/tools/hot-reload

### ISSUE THREAD

**Issue by violinday** [cfug/flutter.cn#1051]
### 页面 URL

https://flutter.cn/docs/development/tools/hot-reload

### 描述问题

左侧导航栏布局存在问题，如下所示：
![image](https://user-images.githubusercontent.com/9434515/160038815-40bfe60e-b785-4bb0-b795-ff00ea1af174.png)

### 期望如何修复

希望可以正确展示.

### 附加信息

MacOS 12.2.1
Chrome:  99.0.4844.83（正式版本） (x86_64)

**Comment by AlexV525** [comment]
请打开 Chrome DevTools (F12) 并确认所有字体都加载完成。

![image](https://user-images.githubusercontent.com/15884415/160041738-b1360f3a-9309-4a2f-9246-97c0c6180e3a.png)

**Comment by violinday** [comment]
可能是字体没加载出来导致的，chrome 经过几次刷新请求成功，没有展示问题了。
这是 safari 的字体请求情况：
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/9434515/160052855-da7f7f7d-a177-465c-91a2-970c657814c5.png">

**Comment by chenglu** [comment]
[Fonts 的 infra 已经搬到国内了](https://ping.chinaz.com/fonts.gstatic.com)，检查一下 VPN 或者 host 设置 @violinday ？
对 `fonts.googleapis.com` 以及 `fonts.gtatic.com` 和 `www.gstatic.com` 应该使用直连模式。

或者你本机命令行窗口执行一下 `dig fonts.gstatic.com` 或者 `ping fonts.gtatic.com` 看看返回的是什么？

**Comment by chenglu** [comment]
要不我们参考 [How to host material icons offline](https://stackoverflow.com/questions/37270835/how-to-host-material-icons-offline) 先把 Material Icons 挪回来吧，好像雪狼之前挪过一次，在 [这个文件夹](https://github.com/cfug/flutter.cn/tree/master/tool/translator/assets/translator/css) 里。
@asnowwolf 能不能帮忙再更新一波，或者下周我看看。

**Comment by violinday** [comment]
@chenglu 
- 检查了下 VPN，展示有问题时 打开了 VPN PAC 模式，可能是受了 VPN 影响
- `ping fonts.gstatic.com`  丢包率基本100%
- 在没有打开终端代理的情况下 `ping fonts.gtatic.com` 出现概率性丢包
1. 第一次 ping 丢包率较高
![image](https://user-images.githubusercontent.com/9434515/160067331-6d7b6371-8358-4ec3-b50c-8439ef9499fc.png)

2.  第二次 ping 丢包率 15% 左右
![image](https://user-images.githubusercontent.com/9434515/160067787-8257626c-1b21-4ca6-85fb-3db342cf113c.png)

3. 第三次 ping fonts.gtatic.com 丢包率 3.8%
![image](https://user-images.githubusercontent.com/9434515/160074986-fdc2f875-2eb0-4023-a067-7cf5c30faac1.png)

**Comment by chenglu** [comment]
看截图，应该是请求这些服务走了代理了，建议使用 VPN 直连 (*或者关闭 VPN 应用) 并使用本地的 DNS 解析 (*记得清空一下 DNS 缓存) 就可以啦。建议做一下这方面的调试，不然也可能会影响所有使用 Google Fonts 的网站。

针对这个 issue 请参考我上面的评论，为了保障更好的访问体验，近期我们会把 Material Icon 和 Fonts 资源迁回来，谢谢你的反馈和推动。

**Comment by violinday** [comment]
flutter.cn 体验已经很好了，字体加载问题应该是个例。

我在本地运行 Flutter web 项目时也遇到了 Material Icon 加载问题（VPN 已关），替换为本地 font 就没有展示问题~

**Comment by chenglu** [comment]
@violinday 最近的 commit https://github.com/cfug/flutter.cn/commit/ab497de7e6fb1b7c6188b2edbc235daca13d3432 已经将 Google Fonts / Material Icons 的引用调整为使用官方的 .cn 国内镜像，未来的访问应该会好很多，我就暂时先关闭这个 Issue 了，如果后期有任何别的访问问题，请随时继续向我们提出反馈！
