### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by 00SunnyDay00** [cfug/flutter.cn#1056]
### 问题镜像 URL

https://pub.flutter-io.cn

### 错误内容截图或 log

紧急 4.6号开始~  中国站出现稳定性问题
export PUB_HOSTED_URL=https://pub.flutter-io.cn  设置以后

通过flutter doctor 会失败  

![image](https://user-images.githubusercontent.com/6287040/161973518-3443b3d1-4eb7-4f26-8be6-ad70fac35473.png)

如果执行flutter pub upgrade 会出现 如下错误：
- Building flutter tool...
- Connection closed while receiving data
- Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

应该是源的稳定性有问题 ，辛苦排查一下。造福flutter 中国社区

**Comment by AlexV525** [comment]
麻烦补充一下 doctor 信息，同时尝试加上 -v 运行后贴上问题看看。

**Comment by 00SunnyDay00** [comment]
flutter doctor  已经报错了

**Comment by 00SunnyDay00** [comment]
感觉差不多 本质上doctor是 engine产物是下载下来了，但是pub的更新失败了
![image](https://user-images.githubusercontent.com/6287040/161978513-e78b5290-7af7-415a-963d-2e42aba888a8.png)

**Comment by 00SunnyDay00** [comment]
测试了一下  pub get 貌似问题不大  但是f'lflutter pub upgrade会报错 
![image](https://user-images.githubusercontent.com/6287040/161979260-94a1a67a-8ee1-46b4-9495-f8c4db7538da.png)

**Comment by AlexV525** [comment]
测试了 2.5.3 (hash: `1811693`)，并未复现上述问题：

```
PS X:\SDK\flutter-test> .\bin\flutter doctor -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine d3ea636dc5d16b56819f3266241e1f708979c233...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Material fonts...                                    1,609ms
Downloading package sky_engine...                                1,251ms
Downloading flutter_patched_sdk tools...                         1,220ms
Downloading flutter_patched_sdk_product tools...                 2,538ms
Downloading windows-x64 tools...                                   14.7s
Downloading windows-x64/font-subset tools...                       394ms
[✓] Flutter (Channel master, 2.5.3, on Microsoft Windows [Version 10.0.22000.556], locale zh-CN)
    • Flutter version 2.5.3 at X:\SDK\flutter-test
    • Upstream repository https://github.com/AlexV525/flutter
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by 00SunnyDay00** [comment]
> 测试了 2.5.3 (hash: `1811693`)，并未复现上述问题：
> 
> ```
> PS X:\SDK\flutter-test> .\bin\flutter doctor -v
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine d3ea636dc5d16b56819f3266241e1f708979c233...
> Expanding downloaded archive...
> Building flutter tool...
> Running pub upgrade...
> ╔════════════════════════════════════════════════════════════════════════════╗
> ║ A new version of Flutter is available!                                     ║
> ║                                                                            ║
> ║ To update to the latest version, run "flutter upgrade".                    ║
> ╚════════════════════════════════════════════════════════════════════════════╝
> 
> 
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
> Downloading Material fonts...                                    1,609ms
> Downloading package sky_engine...                                1,251ms
> Downloading flutter_patched_sdk tools...                         1,220ms
> Downloading flutter_patched_sdk_product tools...                 2,538ms
> Downloading windows-x64 tools...                                   14.7s
> Downloading windows-x64/font-subset tools...                       394ms
> [✓] Flutter (Channel master, 2.5.3, on Microsoft Windows [Version 10.0.22000.556], locale zh-CN)
>     • Flutter version 2.5.3 at X:\SDK\flutter-test
>     • Upstream repository https://github.com/AlexV525/flutter
>     • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
>     • Engine revision d3ea636dc5
>     • Dart version 2.14.4
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> ```

你需要删掉本地缓存

**Comment by AlexV525** [comment]
烦请提供网络环境，以及尝试新建项目后再次尝试。

> 你需要删掉本地缓存

我的本地没有任何缓存，`.pub-cache` 为新建内容。

**Comment by chenglu** [comment]
`pub upgrade` 应该是会读取 `pubspec.yaml` 文件里的 package 依赖，然后去请求 pub 看版本来对比～ 所以可能要在不透露隐私的情况下，试试看同一份 package 引用，也有可能是镜像在缓存某个 package 的时候，把一个错误的 / 过期的版本缓存过来了，我刚去刷新一下 pub cn 的 CDN，然后方便的话 @00SunnyDay00 再试试看？

**Comment by 00SunnyDay00** [comment]
> `pub upgrade` 应该是会读取 `pubspec.yaml` 文件里的 package 依赖，然后去请求 pub 看版本来对比～ 所以可能要在不透露隐私的情况下，试试看同一份 package 引用，也有可能是镜像在缓存某个 package 的时候，把一个错误的 / 过期的版本缓存过来了，我刚去刷新一下 pub cn 的 CDN，然后方便的话 @00SunnyDay00 再试试看？

非常感谢  我再测试一下先

**Comment by chenglu** [comment]
方便的话，也可以回头 share 一下 pubspec 文件里引用的 package 哈。

**Comment by 00SunnyDay00** [comment]
> 方便的话，也可以回头 share 一下 pubspec 文件里引用的 package 哈。

恩 但是其实我们doctor 就过不了 刚才成功了一次 然后又开始失败了

**Comment by 00SunnyDay00** [comment]
今天重新测试已经恢复正常  感谢各位大佬~
