### ISSUE TITLE
#24 - Create and style a text field - 文本框的创建和设定

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#107]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/forms/text-input.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/forms/text-input.html

建议完成时间： 1 - 3 天

**Comment by JasonLinkinBright** [comment]
翻译认领，预计1-3天

**Comment by chenglu** [comment]
谢谢 JasonZ 的时间和贡献，任务已经确认。
