### ISSUE TITLE
[mirrors]

### ISSUE THREAD

**Issue by godwork** [cfug/flutter.cn#1075]
![图片](https://user-images.githubusercontent.com/6427282/167530201-87e5b3d2-0f98-4f92-bc38-648bfc8608a4.png)

**Comment by chenglu** [comment]
@godwork Maven 的镜像地址是 `https://dl.google.com/dl/android/maven2/`
不属于 Flutter 社区维护的范围，配置方法参考 [官方文档](https://developer.android.google.cn/studio/build/dependencies#google-maven)。
