### ISSUE TITLE
#25 - Focus on a Text Field - Text Field 上的焦点

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#108]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/forms/focus.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/forms/focus.html

建议完成时间：3 - 5 天

**Comment by Vadaski** [comment]
申请翻译该任务 译者@MzoneCL

**Comment by chenglu** [comment]
已确认，谢谢你们的时间，辛苦啦！
