### ISSUE TITLE
#26 - Handling changes to a text field - 响应文本框内容的更改

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#109]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/forms/text-field-changes.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/forms/text-field-changes.html

建议完成时间：3 - 5 天

**Comment by Jenniferyingni** [comment]
认领

**Comment by chenglu** [comment]
谢谢 @Jenniferyingni 的时间，辛苦啦！

**Comment by Jin-zz** [comment]
#26 - Handling changes to a text field - 响应文本框内容的更改
翻译任务圆满完成 感谢大家贡献！
