### ISSUE TITLE
[PAGE ISSUE]: '编辑工具设定'

### ISSUE THREAD

**Issue by l1006986533** [cfug/flutter.cn#1090]
### 页面 URL

https://flutter.cn/docs/get-started/editor/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/editor.md

### 描述问题

点击Visual Studio Code时无反应.
When clicking button"Visual Studio Code", the page does not response.

**Comment by chenglu** [comment]
已经修好了，如果有任何问题再随时打开这个 issue 向我们反馈。
@l1006986533
