### ISSUE TITLE
#27 - Retrieve the value of a text field - 获取文本框的输入值

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#110]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/forms/retrieve-input.md

英文文档预览：https://flutter.cn/docs/cookbook/forms/retrieve-input.html

建议完成时间：1 - 3 天

**Comment by JasonLinkinBright** [comment]
翻译认领，预计1-3天

**Comment by Jin-zz** [comment]
抱歉回复晚啦！审核已经通过啦 
感谢 @JasonLinkinBright ！
