### ISSUE TITLE
[Page issue] {https://flutter.cn/docs/development/ui/layout/tutorial}

### ISSUE THREAD

**Issue by YeJiashen** [cfug/flutter.cn#1104]
### 页面 URL

https://flutter.cn/docs/development/ui/layout/tutorial

### 描述问题

左侧目录有很多 keyboard_arrow_down 和 arrow_drop_down 的文字, 与英文界面对比应该是图片资源没有正常加载导致的.
![QQ截图20220712143303](https://user-images.githubusercontent.com/26545532/178424172-4fb8a3a1-e291-4ed0-bc22-22065456b74f.png)

### 期望如何修复

至少不影响左侧目录的观看.

**Comment by AlexV525** [comment]
请打开 Chrome DevTools (F12)，切换到「网络」视图并筛选「字体」，查看是否有失败的请求。
![image](https://user-images.githubusercontent.com/15884415/178432779-f1b6ed3d-932d-4ae9-a5a4-92bdca7b16ea.png)

**Comment by YeJiashen** [comment]
> 请打开 Chrome DevTools (F12)，切换到「网络」视图并筛选「字体」，查看是否有失败的请求。 ![image](https://user-images.githubusercontent.com/15884415/178432779-f1b6ed3d-932d-4ae9-a5a4-92bdca7b16ea.png)

![image](https://user-images.githubusercontent.com/26545532/178450161-5592028e-de86-4a85-83cc-1d5bc77c7a18.png)
字体有很多失败

**Comment by YeJiashen** [comment]
> https://fonts.gstatic.cn/ 打开显示 404 页面（正常就是 404）还是其他错误？
> 
> <img alt="image" width="740" src="https://user-images.githubusercontent.com/2258420/178481406-9246a169-af25-445b-af38-63ff2d271a5e.png">


===========================================
这个网址如下图

![image](https://user-images.githubusercontent.com/26545532/178485031-c40d626c-2f11-468d-b6a2-daa53f11a46f.png)

**Comment by YeJiashen** [comment]
> fonts.gstatic.cn 在全国大部分地区都是可用的: https://ping.chinaz.com/fonts.gstatic.cn 如果可以请尝试更换一下本机的 DNS 地址为 114.114.114.114、8.8.8.8、1.1.1.1 等国内外公共 DNS 服务器再测试一下，后面我们会考虑把 Material Icons 迁移回站内，但是字体系统过于复杂和庞大了，建议还是调整一下本机的网络设定哈。



好的， 感谢。
修改了dns之后可以成功刷新出来图标了。
