### ISSUE TITLE
[PAGE ISSUE]: '在移动设备上减少着色器编译卡顿'

### ISSUE THREAD

**Issue by Nayuta403** [cfug/flutter.cn#1119]
### 页面 URL

https://flutter.cn/docs/perf/rendering/shader/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/docs/perf/rendering/shader.md

### 描述问题

![image](https://user-images.githubusercontent.com/40540394/184061012-6b334370-7107-4262-bfd6-eb1040a6bc4f.png)

**Comment by Nayuta403** [comment]
![image](https://user-images.githubusercontent.com/40540394/184568680-2a55b863-2ffb-4580-b358-e0410841200a.png)
点击这里的链接有问题，看起来 issue 上关联的位置也不对
https://github.com/cfug/flutter.cn/blob/master/src/perf/shader.md

**Comment by AlexV525** [comment]
正确的地址应该是 https://flutter.cn/docs/perf/shader，旧地址对应的对应文件已不在。不确定是何原因导致的重复，排查 site data 后未发现异常，我再跟进下上游有没有问题。cc @chenglu

**Comment by chenglu** [comment]
https://docs.flutter.dev/perf/shader

应该是在这里吧。

**Comment by chenglu** [comment]
眼下先把 side-nav 的数据指向新的页面，文档部分我改天对一下上下游，如果有旧的文档我们就做删除处理或加一个跳转到新文档页面吧。

**Comment by chenglu** [comment]
人肉筛了一下这几个页面，做了如下页面跳转安排：

旧链接 | 新链接
-- | --
https://flutter.cn/docs/perf/rendering/shader | https://flutter.cn/docs/perf/shader
https://flutter.cn/docs/perf/rendering/best-practices | https://flutter.cn/docs/perf/best-practices
https://flutter.cn/docs/perf/rendering/ui-performance | https://flutter.cn/docs/perf/ui-performance
https://flutter.cn/docs/perf/rendering/ | https://flutter.cn/docs/perf/rendering-performance
