### ISSUE TITLE
#29 - Handling Taps - 捕获和处理点击动作

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#112]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/gestures/handling-taps.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/gestures/handling-taps.html

建议完成时间：1 - 3 天

**Comment by songfei** [comment]
认领

**Comment by chenglu** [comment]
飞哥的效率高，我连状态都没来得及改呐 ;-)
