### ISSUE TITLE
#30 - Implement Swipe to Dismiss - 实现「滑动清除」效果

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#113]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/gestures/dismissible.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/gestures/dismissible.html

建议完成时间：3 - 5 天

**Comment by krave1986** [comment]
我是krave@上海GDG，申请认领这篇文档。拥有3年使用 angular，vue 开发前端项目的经验，对移动开发有很大兴趣。预计5天可完成。

**Comment by chenglu** [comment]
谢谢 Krave 的时间，任务已经登记和确认。

**Comment by Jin-zz** [comment]
本篇翻译已完成 辛苦大家啦 感谢！
