### ISSUE TITLE
No. 190 - Create a download button - 创建一个带进度条的下载按钮

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1171]
任务编号: No.190

文档地址: 
https://flutter.cn/docs/cookbook/effects/download-button

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/cookbook/effects/download-button.md

预计完成时间: 7 - 10 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by WeiJun0507** [comment]
认领翻译，预计 7 天完成

**Comment by Pleasurecruise** [comment]
认领任务，预计 3 天。
