### ISSUE TITLE
No. 192 - Create a photo filter carousel - 创建一个照片滤镜选择器

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1173]
任务编号: No.192

文档地址: 
https://flutter.cn/docs/cookbook/effects/photo-filter-carousel

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/cookbook/effects/photo-filter-carousel.md

预计完成时间: 7 - 10 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
即将废弃
![image](https://github.com/user-attachments/assets/82f61ef1-f3e1-44f6-a0bb-55150121a474)
