### ISSUE TITLE
No. 194 - Create a shimmer loading effect - 创建一个微光加载效果

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1175]
任务编号: No.194

文档地址: 
https://flutter.cn/docs/cookbook/effects/shimmer-loading

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/cookbook/effects/shimmer-loading.md

预计完成时间: 7 - 10 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
https://github.com/cfug/flutter.cn/pull/1493
