### ISSUE TITLE
No. 198 - Create gradient chat bubbles - 创建一个渐变色的对话气泡

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1179]
任务编号: No.198

文档地址: 
https://flutter.cn/docs/cookbook/effects/gradient-bubbles

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/cookbook/effects/gradient-bubbles.md

预计完成时间: 5 - 7 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
即将废弃
![image](https://github.com/user-attachments/assets/82f61ef1-f3e1-44f6-a0bb-55150121a474)
