### ISSUE TITLE
#35 - Create a horizontal list - 创建一个水平滑动的列表

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#118]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/lists/horizontal-list.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/lists/horizontal-list.html

建议完成时间：1 - 3 天

**Comment by nesger** [comment]
认领该任务，预计 1 - 3 天

**Comment by chenglu** [comment]
任务已确认，建议先看一下上一个 PR 的 comments，感谢～ 祝好。

**Comment by Jin-zz** [comment]
#35 - Create a horizontal list - 创建一个水平滑动的列表
感谢大家贡献！翻译任务圆满完成！
