### ISSUE TITLE
No. 206 - Using slivers to achieve fancy scrolling - 使用 sliver 实现出色的滑动效果

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1187]
任务编号: No.206

文档地址: 
https://flutter.cn/docs/development/ui/advanced/slivers

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/ui/advanced/slivers.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
