### ISSUE TITLE
No. 208 - AndroidX migration - 迁移到使用 AndroidX

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1189]
任务编号: No.208

文档地址: 
https://flutter.cn/docs/development/platform-integration/android/androidx-migration

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/android/androidx-migration.md

预计完成时间: 5 - 7 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
