### ISSUE TITLE
#36 - Creating a Grid List - 创建一个网格列表

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#119]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/lists/grid-lists.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/lists/grid-lists.html

建议完成时间：1 - 3 天

**Comment by talisk** [comment]
认领该任务，预计 1 - 3 天

**Comment by Jin-zz** [comment]
感谢百忙中抽空参与！任务已经成功认领和登记啦！
期待你的翻译，再次感谢@talisk ！

**Comment by Jin-zz** [comment]
#36 - Creating a Grid List - 创建一个网格列表
翻译任务圆满完成！感谢大家贡献！
