### ISSUE TITLE
No. 209 - Deprecated Splash Screen API Migration - 已弃用的闪屏页 API 迁移

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1190]
任务编号: No.209

文档地址: 
https://flutter.cn/docs/development/platform-integration/android/splash-screen-migration

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/android/splash-screen-migration.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
