### ISSUE TITLE
No. 213 - Building macOS apps with Flutter - 构建 macOS 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1194]
任务编号: No.213

文档地址: 
https://flutter.cn/docs/development/platform-integration/macos/building

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/macos/building.md

预计完成时间: 7 - 10 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by RoleWong** [comment]
申请领取，完成时间六天

**Comment by AlexV525** [comment]
谢谢 @RoleWong ，祝顺利
