### ISSUE TITLE
No. 214 - Customizing web app initialization - 自定义 Web 应用初始化

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1195]
任务编号: No.214

文档地址: 
https://flutter.cn/docs/development/platform-integration/web/initialization

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/web/initialization.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
