### ISSUE TITLE
No. 216 - Migrate a Windows project to set version information - Window 版本信息迁移

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1197]
任务编号: No.216

文档地址: 
https://flutter.cn/docs/development/platform-integration/windows/version-migration

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/windows/version-migration.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 1 天。
