### ISSUE TITLE
No. 217 - Happy paths project - Happy paths 项目

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1198]
任务编号: No.217

文档地址: 
https://flutter.cn/docs/development/packages-and-plugins/happy-paths

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/packages-and-plugins/happy-paths.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
已转至 https://docs.flutter.cn/packages-and-plugins/favorites
