### ISSUE TITLE
No. 218 - Happy paths recommendations - Happy paths package 和插件推荐

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1199]
任务编号: No.218

文档地址: 
https://flutter.cn/docs/development/packages-and-plugins/happy-paths/recommended

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/packages-and-plugins/happy-paths/recommended.md

预计完成时间: 5 - 7 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
已转到 https://docs.flutter.cn/packages-and-plugins/favorites
