### ISSUE TITLE
#37 - Creating lists with different types of items - 创建拥有不同列表项的列表

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#120]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/lists/mixed-list.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/lists/mixed-list.html

建议完成时间：3 - 5 天

**Comment by talisk** [comment]
认领该任务，预计 3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @talisk 的时间，任务已成功认领和登记啦！
期待你的翻译，再次感谢！

**Comment by Jin-zz** [comment]
#37 - Creating lists with different types of items - 创建拥有不同列表项的列表 
本篇翻译已经完成 感谢大家的贡献~
