### ISSUE TITLE
No. 222 - Using the Network View - 使用网络视图 (Network View)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1203]
任务编号: No.222

文档地址: 
https://flutter.cn/docs/development/tools/devtools/network

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/tools/devtools/network.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 1 天。

**Comment by AlexV525** [comment]
豆神󠁖v5

**Comment by AmosHuKe** [comment]
最近事情多，先弄小工作量的哈哈哈哈哈~
