### ISSUE TITLE
No. 228 - Performance FAQ - 性能常见问题和回答

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1209]
任务编号: No.228

文档地址: 
https://flutter.cn/docs/perf/faq

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/perf/faq.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
