### ISSUE TITLE
No. 235 - flutter: The Flutter command-line tool - flutter: The Flutter command-line tool

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1216]
任务编号: No.235

文档地址: 
https://flutter.cn/docs/reference/flutter-cli

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/reference/flutter-cli.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 3 天。
