### ISSUE TITLE
No. 236 - Separation of the Element and RenderObject trees - Flutter 工作原理 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1217]
任务编号: No.236

文档地址: 
https://flutter.cn/docs/resources/inside-flutter#separation-of-the-element-and-renderobject-trees

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/resources/inside-flutter.md#separation-of-the-element-and-renderobject-trees

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
任务认领，预计 2 天。
