### ISSUE TITLE
No. 238 - Configuring your web server - 配置 Web 应用的 URL 策略 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1219]
任务编号: No.238

文档地址: 
https://flutter.cn/docs/development/ui/navigation/url-strategies

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/ui/navigation/url-strategies.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
认领任务，预计 2 天。
