### ISSUE TITLE
#39 - Working with long lists - 长列表的处理

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#122]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/lists/long-lists.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/lists/long-lists.html

建议完成时间：1 - 3 天

**Comment by JasonLinkinBright** [comment]
翻译认领，预计 1 - 3 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright，任务已登记啦！
格式问题可参考[文档格式要求](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
再次感谢你的时间，期待翻译！为你点赞！

**Comment by cfug-dev** [comment]
任务已经完成，谢谢大家的时间。
