### ISSUE TITLE
No. 240 - Developing FFI plugin packages - Flutter Packages 的开发和提交 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1221]
任务编号: No.240

文档地址: 
https://flutter.cn/docs/development/packages-and-plugins/developing-packages

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/packages-and-plugins/developing-packages.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 3 天完成。
@AlexV525
