### ISSUE TITLE
No. 241 - Local Network Privacy Permissions - 将 Flutter module 集成到 iOS 项目 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1222]
任务编号: No.241

文档地址: 
https://flutter.cn/docs/development/add-to-app/ios/project-setup

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/add-to-app/ios/project-setup.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 3 天完成。
@AlexV525
