### ISSUE TITLE
No. 242 - 时间线事件表 - 使用性能视图 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1223]
任务编号: No.242

文档地址: 
https://flutter.cn/docs/development/tools/devtools/performance

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/tools/devtools/performance.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 2 天。
