### ISSUE TITLE
No. 243 - What is shader compilation jank? - 着色器编译时卡顿 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1224]
任务编号: No.243

文档地址: 
https://flutter.cn/docs/perf/shader

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/perf/shader.md

预计完成时间: 3 - 5 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 2 天。
