### ISSUE TITLE
No. 244 - 更新应用程序的版本号 - 构建和发布为 Windows 应用 - [中文内容增补]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#1225]
任务编号: No.244

文档地址: 
https://flutter.cn/docs/deployment/windows

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/deployment/windows.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 2 天。
