### ISSUE TITLE
No. 255 - Migrate a Windows project to the idiomatic run loop - 将工程迁移到「更 Windows」的事件循环系统

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#1227]
任务编号: No.255

文档地址: 
https://flutter.cn/docs/development/platform-integration/windows/run-loop-migration

Markdown 源码地址: 
https://github.com/cfug/flutter.cn/blob/master/src/development/platform-integration/windows/run-loop-migration.md

预计完成时间: 1 - 3 天

感谢你为 Flutter 中文文档所出的贡献！

**Comment by AmosHuKe** [comment]
申请认领任务，预计 2 天完成。
