### ISSUE TITLE
#40 - Report errors to a service - 把报错信息通过服务上传

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#123]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/maintenance/error-reporting.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/maintenance/error-reporting.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领 预计 3-5 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright ！任务已成功认领和登记啦
期待你的翻译！再次感谢！

**Comment by Jin-zz** [comment]
#40 - Report errors to a service - 把报错信息通过服务上传
本篇翻译已完成 感谢大家的贡献~
