### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by frame-php-free** [cfug/flutter.cn#1237]
### 问题镜像 URL

https://pub.dev/packages/flutter_stripe

### 错误内容截图或 log

![QQ截图20221102152456](https://user-images.githubusercontent.com/42052492/199425723-8ac36c9c-0ee2-478c-a2d3-0151db4ab912.png)

### pubspec.yaml

name: talkhaiwai
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2

  flutter_html: ^0.11.1 
 
  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.5.4
  flutter_keyboard_visibility: ^2.0.0
  meta: ^1.7.0
 
  image_picker: ^0.6.5+3
  permission_handler: 8.2.4
  
  convert: ^3.0.2 
  dio: ^3.0.9 
  cookie_jar: ^1.0.1
  shared_preferences: ^0.4.2
  dio_cookie_manager: ^1.0.0
  json_serializable: ^6.3.1 
  
  path: ^1.8.0
  sqflite: ^2.0.2
  provider: ^5.0.0
  crypto: ^3.0.1
  badges: ^2.0.1
  fluttertoast: ^8.0.6
  url_launcher: ^6.0.3
  flutter_easyrefresh: ^2.1.8

  flutter_stripe: ^2.5.0
  flutter_stripe_web: ^0.1.3
  stripe_checkout: ^0.1.2
  http: ^0.11.0
  font_awesome_flutter: ^9.2.0
  platform: ^3.0.0
 

 
  flutter_spinkit: ^5.1.0
  http_auth: ^1.0.1
  webview_flutter_x5: ^2.0.8+4

  tencent_im_sdk_plugin: 3.9.0

  tencent_trtc_cloud: 2.3.4
  flutter_styled_toast: ^2.1.3

  qr_code_scanner: ^0.7.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  

  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0 

 

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
        

    - family: kegaise
      fonts:
        - asset: assets/fonts/kegaise.ttf

    - family: haiwaity
      fonts:
        - asset: assets/fonts/haiwaity.ttf

    - family: caise
      fonts:
        - asset: assets/fonts/caise.ttf

### flutter doctor -v

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19045.2130], locale zh-CN)
    • Flutter version 2.10.5 at C:\dj\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (7 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\dj\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: D:\dj\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at D:\dj\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by AlexV525** [comment]
你好，Android Gradle Build 的依赖解析并非通过 cn 镜像进行绕转，Flutter 中国镜像站也并未配置 Gradle 镜像。请检查你的本地 Gradle 是否配置了其他的镜像站，或者是否能从 Google/MavenCentral 解析到对应的依赖版本。

**Comment by frame-php-free** [comment]
android/gradle/wrapper/gradle-wrapper.properties
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
```

android/build.gradle
镜像配置
```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
