### ISSUE TITLE
#41 - Animating a Widget across screens - 跨页面切换的动效 Widget (Hero animations)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#124]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/hero-animations.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/hero-animations.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领，预计 3-5 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright 的时间！期待你的翻译！辛苦啦

**Comment by Jin-zz** [comment]
#41 - Animating a Widget across screens - 跨页面切换的动效 Widget (Hero animations)
本篇翻译已完成 感谢大家的贡献~
