### ISSUE TITLE
请问 flutter.cn 顶层路径的网页在哪里

### ISSUE THREAD

**Issue by doggy8088** [cfug/flutter.cn#1243]
### 页面 URL

/

### 描述问题

我从这个 Repo 可以 build 出所有 `flutter.cn/docs` 底下的所有文档页面，但是 `/` 底下的页面找不到，想请教一下如何能找到这部分的内容？谢谢！

**Comment by chenglu** [comment]
保哥好，好久不见！/ 下面的页面我们称之为 Flutter 的 marketing site，目前是通过一个私有的 repo 进行开发的。.cn 没有重新部署 marketing site 的程序，而是通过 global 团队打包 HTML 页面我们直接做本地化来完成的，所以这部分内容没有开源协作，有什么需要嘛？

**Comment by doggy8088** [comment]
你好 😊

我想将文件网站转成繁体中文版，提供台湾开发者便于阅读，但是网址都是错误的，因为连结都是 `/docs/*`，所以我才想连同 marketing site 一起转成繁体版。

**Comment by chenglu** [comment]
如果可以加快完成中文内容本地化，我们可以试试看如何一起协作一下。

因为道理上说简体中文和繁体中文的相互转换应该不会花费太多精力，换句话说，有社区的贡献者完成了文档的繁体中文翻译，稍加改动应该就可以变成简体中文，这样比纯英文翻中文要简单很多，不知道保哥计划里是否有这一项？

`flutter.tw` 域名也在我这里。现有的 `flutter/website` 对应的是 https://docs.flutter.dev/ 其实 marketing site 在其他语言里也没有是必须项，我倒是觉得直接把 docs.flutter.dev 变成 flutter.tw 首页应该也可以～ 

我给你微信留言了，我们可以聊一下先？

**Comment by doggy8088** [comment]
我已经先完成了两个网站：

1. https://flutter.tw.gh.miniasp.com/
2. https://dart.tw.gh.miniasp.com/
