### ISSUE TITLE
[Page issue] https://flutter.cn/docs/development/ui/assets-and-images#asset-bundling

### ISSUE THREAD

**Issue by 588q9** [cfug/flutter.cn#1244]
### 页面 URL

https://flutter.cn/docs/development/ui/assets-and-images#asset-bundling

### 描述问题

**该 assets 部分的 flutter 部分**   翻译似乎有误，原文为  **The assets subsection of the flutter section**

**Comment by 588q9** [comment]
> ### 页面 URL
> 
> https://flutter.cn/docs/development/ui/assets-and-images#asset-bundling
> ### 页面源地址
> 
> _No response_
> ### 描述问题
> 
> **该 assets 部分的 flutter 部分** 翻译似乎有误，原文为 **The assets subsection of the flutter section**
> ### 期望如何修复
> 该yaml中flutter部分下的assets 部分
>
> ### 附加信息
> 
> _No response_

**Comment by Vadaski** [comment]
谢谢 @588q9 的反馈，这里确实翻译有问题，方便直接提交一个 pr 么~

**Comment by 588q9** [comment]
> 谢谢 @588q9 的反馈，这里确实翻译有问题，方便直接提交一个 pr 么~
好的
