### ISSUE TITLE
[页面图标显示有问题] {https://flutter.cn/docs/get-started/install}

### ISSUE THREAD

**Issue by youngledo** [cfug/flutter.cn#1248]
### 页面 URL

https://flutter.cn/docs/get-started/install

### 描述问题

出现的问题的不是上述地址，而是左侧菜单的图标显示有问题，我猜测大概率是网络慢图标渲染不正常。

不正常的：
<img width="638" alt="image" src="https://user-images.githubusercontent.com/68590897/212521093-96e5033a-16cc-43b9-88f6-4dc421252814.png">

正常的：
<img width="403" alt="image" src="https://user-images.githubusercontent.com/68590897/212521118-27b696aa-b1f5-48cf-a93b-f8eb0c6a7fb3.png">

### 期望如何修复

图标正常加载。

**Comment by chenglu** [comment]
@AlexV525 今天也反馈了这个问题，我们准备把谷歌的这些 Icons 和 Fonts 资源离线到本地来调用。

**Comment by AlexV525** [comment]
清除 DNS 缓存后再次尝试：
```powershell
Clear-DnsClientCache
ipconfig /flushdns
```

**Comment by chenglu** [comment]
@youngledo 我们已经把谷歌字体和 Material Icons 资源同步到国内的服务器上了，可否请你清空本地浏览器缓存或者比如打开一个隐身窗口再次尝试？
感谢 @AlexV525 的帮助。

**Comment by youngledo** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/68590897/236399815-1f41701d-9b4f-420f-ac84-893b8aca83eb.png">
就在刚刚莫名其妙又出现了，控制台报错信息如图（已经清理了浏览器缓存）。

**Comment by AlexV525** [comment]
尝试直接访问 https://files.flutter-io.cn/fonts/flutter/fonts.css，根据控制台报错是证书问题，也没有到证书过期时间，可以检查一下是不是经过了 VPN 然后节点出现了问题，或者时间未对上。

**Comment by AlexV525** [comment]
如仍有类似的问题，请按照类似步骤排查：
1. 打开 Console (F12)，确定报错内容。
2. 如果是 CERT 相关，请检查是否对应 URL 被 VPN 或代理处理，而代理节点出现问题。
