### ISSUE TITLE
#42 - Navigate to a new screen and back - 导航到一个新页面和返回

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#125]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/navigation-basics.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/navigation-basics.html

建议完成时间：3 - 5 天

**Comment by songfei** [comment]
认领

**Comment by chenglu** [comment]
谢谢飞哥参与～

**Comment by chenglu** [comment]
谢谢飞哥的时间，本文档已发布：https://debug.flutter.cn/docs/cookbook/navigation/navigation-basics.html，本 Issue 关闭。
