### ISSUE TITLE
#43 - Navigate with named routes - 导航到对应名称的 routes 里

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#126]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/named-routes.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/named-routes.html

建议完成时间：3 - 5 天

**Comment by Zhangdroid** [comment]
认领这篇~

**Comment by Jin-zz** [comment]
感谢 @Zhangdroid 的时间！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！辛苦啦

**Comment by Jin-zz** [comment]
本篇翻译已完成 感谢贡献~辛苦大家啦
