### ISSUE TITLE
升级AS后旧的flutter项目没法运行问题 

### ISSUE THREAD

**Issue by aliulll** [cfug/flutter.cn#1263]
AS版本: Electric Eel | 2022.1.1 Patch 1
您好: 
   我升级了最新的AS,旧的flutter项目运行报错“Error: Entrypoint isn't within the current project“,我尝试过用”project structure“重新设置”source“,但显示”this location is already imported“,所以我没办法重新设置,我尝试过删除“.idea”,然后重新打开,还是不行.希望能得到处理,谢谢!

**Comment by AlexV525** [comment]
请通过搜索引擎搜索相应的问题解决方案，谢谢。

**Comment by aliulll** [comment]
搜索的方法我都试过了,没用

**Comment by aliulll** [comment]
我给AS提了这个,谷歌也是让给了我链接方法,我试过,都没用他那边让我问问flutter官方

**Comment by aliulll** [comment]
这个是他们给我的最后回话:Could you try reporting a bug to Flutter? (Based on the error message and the search results, I suspect it is an issue for Flutter, not Android Studio.)
