### ISSUE TITLE
Flutter 在IOS上不能实现自动点击网页的按钮

### ISSUE THREAD

**Issue by ouyangzhanzhu** [cfug/flutter.cn#1265]
你好  我想实现一个自动点击器在IOS上，主要是点击任意网页上的按钮，大致的实现思路就是通过手动设置需要点击按钮的位置，然后发送点击按钮事件，然后在iPhone手机上，并没有看到我想要的效果，android手机是可以的，不知道是什么原因？能不能帮助我下，谢谢

double cx = offset.dx + (width! / 2 + offsetF.dx);
    double cy = offsetF.dy + height! / 2;

    print("_pressAdd ==$width==$height==$cx==$cy");

    //模拟点击
    var addPointer = PointerAddedEvent(
      pointer: 0,
      position: Offset(cx, cy),
    );

    var downPointer = PointerDownEvent(
      pointer: 0,
      position: Offset(cx, cy),
    );

    var upPointer = PointerUpEvent(
      pointer: 0,
      position: Offset(cx, cy),
    );

    GestureBinding.instance!.handlePointerEvent(addPointer);

    GestureBinding.instance!.handlePointerEvent(downPointer);

    GestureBinding.instance!.handlePointerEvent(upPointer);

**Comment by AlexV525** [comment]
请通过搜索引擎搜索相应的问题解决方案，谢谢。

**Comment by ouyangzhanzhu** [comment]
> 

就是找不到相应的解决方案才到这里来求助
