### ISSUE TITLE
#44 - Pass arguments to a named route - 给特定的 route 传参

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#127]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/navigate-with-arguments.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/navigate-with-arguments.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领 预计 3-5 天

**Comment by Jin-zz** [comment]
再次感谢 @JasonLinkinBright ！
辛苦啦

**Comment by Jin-zz** [comment]
#44 - Pass arguments to a named route - 给特定的 route 传参
本篇翻译已经圆满完成啦 感谢大家的贡献
