### ISSUE TITLE
关于Flutter3.7.4版本关联Java jdk版本问题

### ISSUE THREAD

**Issue by wavedanger** [cfug/flutter.cn#1271]
### 页面 URL

https://flutter.cn/docs/get-started/install/windows#agree-to-android-licenses

### 描述问题

2023/2/22发布了flutter3.7.4版本，所对应的jdk版本应该是11，而文档上写的是"确保你安装了 Java 8，并且正确设置了 JAVA_HOME 环境变量到 JDK 目录"

### 期望如何修复

可以根据不同版本列出对应的Java jdk版本

**Comment by wavedanger** [comment]
"Make sure that you have a version of Java 11 installed and that your JAVA_HOME environment variable is set to the JDK’s folder."

**Comment by AlexV525** [comment]
上游已经提交修复，已计划在下次同步时调整。

**Comment by AlexV525** [comment]
Duplicate of #1260
