### ISSUE TITLE
#45 - Return data from a screen - 从一个页面回传数据

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#128]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/returning-data.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/returning-data.html

建议完成时间：3 - 5 天

**Comment by songfei** [comment]
认领

**Comment by chenglu** [comment]
飞哥的效率已经让我两次都没来得及登记就直接做完了，高！😂
