### ISSUE TITLE
镜像更新不及时，麻烦更新下，谢谢。

### ISSUE THREAD

**Issue by wengxianxun** [cfug/flutter.cn#1280]
### 问题镜像 URL

https://pub.dev/packages/syncfusion_flutter_treemap

### 错误内容截图或 log

Because flutter_examples depends on syncfusion_flutter_treemap ^21.1.35 which doesn't match any versions, version solving failed.

### pubspec.yaml

name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 21.1.35  
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.0
  path_provider: ^2.0.1
  path_provider_foundation: ^2.1.0
  desktop_window: 0.4.0
  intl: ">=0.17.0 <0.20.0"
  
  syncfusion_localizations: ^21.1.35
  syncfusion_flutter_datagrid_export: ^21.1.35-beta
  syncfusion_flutter_calendar: ^21.1.35
  syncfusion_flutter_datepicker: ^21.1.35
  syncfusion_flutter_charts: ^21.1.35
  syncfusion_flutter_gauges: ^21.1.35
  syncfusion_flutter_sliders: ^21.1.35
  syncfusion_flutter_pdf: ^21.1.35
  syncfusion_flutter_barcodes: ^21.1.35
  syncfusion_officechart: ^21.1.35-beta
  syncfusion_flutter_maps: ^21.1.35
  syncfusion_flutter_signaturepad: ^21.1.35
  syncfusion_flutter_pdfviewer: ^21.1.35
  syncfusion_flutter_treemap: ^21.1.35

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - images/pdf_viewer/
    - assets/pdf/
    - lib/sample_details.json
    - assets/world_map.json
    - assets/africa.json
    - assets/europe.json
    - assets/germany.json
    - assets/india.json
    - assets/usa.json
    - assets/south_america.json
    - assets/australia.json
    - assets/maps_brazil_boundary.json
    - assets/maps_uk_boundary.json
    - assets/maps_france_boundary.json
    - assets/river.json
    - assets/london_to_british.json
    - assets/london_to_chessington.json
    - assets/london_to_hampton_court_palace.json
    - assets/london_to_twickenham_stadium.json
    - assets/london_to_windsor_castle.json
    - assets/product_data.json
    - assets/chart_data.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf 

### 网络环境

公网

**Comment by chenglu** [comment]
排查问题 ing，为了不耽误使用，我先把中国镜像的 CDN 缓存清空了，现在应该会回站源去取数据，请在试一下。

**Comment by chenglu** [comment]
新的刷新代码已经部署了，测试了一天，每个 package 都刷新到了，我先把 issue 关掉啦，有任何问题随时再开 Issue。
