### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by CaiJingLong** [cfug/flutter.cn#1282]
### 问题镜像 URL

https://pub.flutter-io.cn/api/packages/dio

### 错误内容截图或 log

我提供了一个可复现的 Demo， 均为请求 https://pub.flutter-io.cn/api/packages/dio

仓库地址： https://github.com/flutter-fix-something/PubErrorReport

仓库内有三个shell文件和对应的日志文件，包含了请求的 curl 命令和返回的json文件

分别对应使用curl模拟
- 浏览器访问 cn
- pub 访问 cn
- pub 访问 pub.dev

**Comment by CaiJingLong** [comment]
浏览器请求 pub.flutter-io.cn 获取到的 dio 是 5.1.1 
pub 请求获取的 pub.flutter-io.cn 是 5.1.0
pub 和浏览器请求 pub.dev 都是 5.1.1

**Comment by CaiJingLong** [comment]
curl 'https://pub.flutter-io.cn/api/packages/dio' --compressed | jq ".latest.version"

curl 'https://pub.flutter-io.cn/api/packages/dio' | jq ".latest.version"

<img width="679" alt="image" src="https://user-images.githubusercontent.com/14145407/229119211-1e499910-178b-4c50-981f-3419e212e659.png">

**Comment by chenglu** [comment]
我单独刷新一下这个 dio 的 package 你再测试一下？在线不，我微信你了～

**Comment by chenglu** [comment]
新的刷新代码已经部署了，测试了一天，每个 package 都刷新到了，我先把 issue 关掉啦，有任何问题随时再开 Issue。
