### ISSUE TITLE
[PAGE ISSUE]: 'Flutter 实践教程'

### ISSUE THREAD

**Issue by jzllove9** [cfug/flutter.cn#1287]
### 页面 URL

https://flutter.cn/docs/reference/tutorials/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/reference/tutorials.md

### 描述问题

页面样式异常
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13548092/236606279-eb2fb581-09dc-416b-ac0a-da8213faefe6.png">

### 期望如何修复

恢复正常页面样式

### 附加信息

猜测是代码里面变量引用错误，本身的icon直接引用成了字符串

**Comment by AlexV525** [comment]
Duplicated of #1248
