### ISSUE TITLE
#46 - Send data to a new screen - 传递数据到新页面

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#129]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/navigation/passing-data.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/navigation/passing-data.html

建议完成时间：3 - 5 天

**Comment by songfei** [comment]
认领

**Comment by chenglu** [comment]
谢谢飞哥！

**Comment by chenglu** [comment]
PR 已经 merged，任务已经完成！
