### ISSUE TITLE
#47 - Fetch data from the internet - 获取网络数据

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#130]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/fetch-data.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/networking/fetch-data.html

建议完成时间：3 - 5 天

**Comment by Jin-zz** [comment]
翻译已成功认领和登记！辛苦啦 @XatMassacrE 
格式问题可参考 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
以及 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide)

**Comment by Jin-zz** [comment]
感谢大家参与贡献~
本篇翻译已完成
