### ISSUE TITLE
[Page issue] {https://github.com/cfug/flutter.cn/blob/master/src/resources/inside-flutter.md}

### ISSUE THREAD

**Issue by tsunhua** [cfug/flutter.cn#1306]
### 页面 URL

https://github.com/cfug/flutter.cn/blob/master/src/resources/inside-flutter.md

### 描述问题

> The element tree is necessary because the widgets themselves are immutable, which means (among other things), they cannot remember their parent or child relationships with other widgets.
Element 树是非常有必要的，这是因为 widget 自身是不可变的， 这意味着（其他情况除外），它们无法记住父（或子）节点与其他 widget 的关系。

翻译内容错了，原文是“无法记住与其他widget的父或子关系”，译文 “无法记住父（或子）节点与其他 widget 的关系”  整个意思都错了。

### 期望如何修复

修订翻译内容

**Comment by AlexV525** [comment]
@AmosHuKe
