### ISSUE TITLE
#48 - Making authenticated requests - 发起 HTTP 认证授权请求

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#131]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/authenticated-requests.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/networking/authenticated-requests.html

建议完成时间：1 - 3 天

**Comment by Jin-zz** [comment]
感谢 @XatMassacrE，翻译已成功认领和登记
格式问题可参考 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
以及 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide)
再次感谢！

**Comment by Jin-zz** [comment]
#48 - Making authenticated requests - 发起 HTTP 认证授权请求
本篇翻译已完成啦 感谢大家抽出时间参与贡献 辛苦哒
