### ISSUE TITLE
#49 - Parsing JSON in the background - 在后台处理 JSON 数据解析

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#132]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/background-parsing.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/networking/background-parsing.html

建议完成时间：3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @XatMassacrE！一次性认领四个！真棒！
可以先领两个做完继续认领的哈哈 也请注意完成时间啦
辛苦啦！

**Comment by Jin-zz** [comment]
感谢大家的时间~本篇翻译已完成啦
