### ISSUE TITLE
#50 - Working with WebSockets - 发起 WebSockets 请求

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#133]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/web-sockets.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/networking/web-sockets.html

建议完成时间：3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @XatMassacrE！翻译已成功认领和登记
格式问题可参考 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
以及 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide)
期待你的翻译！再次感谢

**Comment by Jin-zz** [comment]
本篇翻译已完成 辛苦大家啦
