### ISSUE TITLE
#51 - Persist data with SQLite - 用 SQLite 做数据持久化

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#134]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/persistence/sqlite.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/persistence/sqlite.html

建议完成时间：3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @panda8z ！任务已成功认领和登记
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Translation-Workflow-with-GitHub)`
期待你的翻译！再次感谢！
