### ISSUE TITLE
#52 - Reading and Writing Files - 文件读写

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#135]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/persistence/reading-writing-files.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/persistence/reading-writing-files.html

建议完成时间：3 - 5 天

**Comment by panda8z** [comment]
任务认领 预计5月15日完成

**Comment by Jin-zz** [comment]
感谢 @panda8z 的时间！
翻译格式问题可参考 [文档格式要求](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
以及 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide)
期待你的翻译！再次感谢！
