### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by bufffun** [cfug/flutter.cn#1352]
### 问题镜像 URL

https://storage.flutter-io.cn/flutter_infra_release/flutter/3316dd8728419ad3534e3f6112aa6291f587078a/dart-sdk-linux-x64.zip

### 错误内容截图或 log

这两天dart sdk的下载速度很慢，可以帮忙看一下吗？
<img width="695" alt="image" src="https://github.com/cfug/flutter.cn/assets/2651340/704f7c35-3176-428c-8aca-1d386e59df93">

### 网络环境

中国大陆电信

**Comment by AmosHuKe** [comment]
@bufffun  我也是大陆电信，满速。

**Comment by bufffun** [comment]
> @bufffun 我也是大陆电信，满速。
也试下这个？我用vpn一开始速度也挺快的，后面就慢慢的慢下来了
https://storage.flutter-io.cn/flutter_infra_release/flutter/3316dd8728419ad3534e3f6112aa6291f587078a/dart-sdk-darwin-x64.zip

**Comment by AmosHuKe** [comment]
@bufffun 也是满速（未开魔法上网）

**Comment by AlexV525** [comment]
根据测试没有问题。在使用镜像时请勿使用 vpn 二次代理。可以调整 PAC 将 *.cn 过滤。
