### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by SQSora** [cfug/flutter.cn#1353]
### 问题镜像 URL

https://storage.flutter-io.cn/nnbd_artifacts/3.1.3/flutter_web.js

### 错误内容截图或 log

使用大陆IP请求时下载缓慢，非大陆ip正常。
![image](https://github.com/cfug/flutter.cn/assets/87071734/3e083379-65b0-4aaf-b8ee-efec93cc1073)

### 网络环境

广东电信

**Comment by chenglu** [comment]
我去问一下 CDN 服务商电信网络的访问情况。

**Comment by chenglu** [comment]
@SQSora 请再试试看，我们的 CDN 服务商已经对广东电信和周边区域调整了节点覆盖，如果有任何其他问题请再随时打开这个 Issue 提出！
