### ISSUE TITLE
[PAGE ISSUE]: '在 Windows 操作系统上安装和配置 Flutter 开发环境'

### ISSUE THREAD

**Issue by Yangself666** [cfug/flutter.cn#1354]
### 页面 URL

https://flutter.cn/docs/get-started/install/windows/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/get-started/install/windows.md

### 描述问题

在安装与环境设置的页面中，Using Flutter in China的链接https://flutter.cn/docs/community/china页面已经不存在，应该修改为https://flutter.cn/community/china，请修改多个页面的链接为新的地址

### 期望如何修复

将全局的https://flutter.cn/docs/community/china链接修改为https://flutter.cn/community/china

**Comment by AmosHuKe** [comment]
- #1348
