### ISSUE TITLE
#53 - Storing key-value data on disk - 存储键值对数据

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#136]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/persistence/key-value.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/persistence/key-value.html

建议完成时间：3 - 5 天

**Comment by duxinfeng** [comment]
翻译认领，预计需要 3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @duxinfeng 的时间！
翻译格式问题可参考 [中文文案排版指南 ](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！辛苦啦

**Comment by Jin-zz** [comment]
#53 - Storing key-value data on disk - 存储键值对数据 
本篇翻译已完成 感谢大家贡献~
