### ISSUE TITLE
[Mirror issue] 使用 https://pub-web.flutter-io.cn 中国镜像搜索的问题

### ISSUE THREAD

**Issue by lycstar** [cfug/flutter.cn#1363]
### 问题镜像 URL

https://pub-web.flutter-io.cn/packages?q=diuashd

### 错误内容截图或 log

[搜索陌生的关键词会出现错误](https://pub-web.flutter-io.cn/packages?q=diuashd)
![image](https://github.com/cfug/flutter.cn/assets/37872392/5915321b-0fb2-476a-b6b3-7e64e9eb8269)

[常见的则不会](https://pub-web.flutter-io.cn/packages?q=path+provider)
![image](https://github.com/cfug/flutter.cn/assets/37872392/43276de0-cfc1-414b-ab7b-9f335a5d3fc4)

**Comment by chenglu** [comment]
Fixed, 请验证如果有问题请随时打开这个 issue 跟进，感谢反馈！
