### ISSUE TITLE
#54 - Play and pause a video - 视频的播放和暂停

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#137]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/plugins/play-video.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/plugins/play-video.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领 预计 3-5 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright 的时间！
辛苦啦　期待翻译！

**Comment by Jin-zz** [comment]
#54 - Play and pause a video - 视频的播放和暂停
本篇翻译已完成~感谢大家的贡献！
