### ISSUE TITLE
#55 - Take a picture using the Camera - 使用 Camera 插件实现拍照功能

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#138]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/plugins/picture-using-camera.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/plugins/picture-using-camera.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领 预计 3-5 天

**Comment by Jin-zz** [comment]
@JasonLinkinBright 辛苦啦！翻译已成功认领和登记！

**Comment by Jin-zz** [comment]
#55 - Take a picture using the Camera - 使用 Camera 插件实现拍照功能
本篇翻译已完成~感谢大家的时间 辛苦啦
