### ISSUE TITLE
#56 - An introduction to integration testing - 集成测试介绍

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#139]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/testing/integration/introduction.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/testing/integration/introduction.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领 预计 3-5 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright ！翻译已成功认领和登记
辛苦啦

**Comment by Jin-zz** [comment]
本篇翻译已完成啦 感谢译者的时间
