### ISSUE TITLE
#58 - Scrolling - 列表滚动 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#141]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/testing/integration/scrolling.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/testing/integration/scrolling.html

建议完成时间：3 - 5 天

**Comment by 5ibinbin** [comment]
认领这篇

**Comment by Jin-zz** [comment]
感谢@5ibinbin的时间！
翻译格式问题可以查看 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！再次感谢

**Comment by Jin-zz** [comment]
helo! @5ibinbin 翻译完了可以提交 PR 啦
如果是遇到问题了也可以一起讨论看看哦~

**Comment by 5ibinbin** [comment]
我再校对一下再提交pr，晚上提交

nickyzhang

**Comment by Jin-zz** [comment]
@5ibinbin 好滴！辛苦啦！

**Comment by Jin-zz** [comment]
本篇翻译已完成~感谢译者的时间！
