### ISSUE TITLE
#61 - An introduction to widget testing - Widget 测试介绍 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#142]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/testing/widget/introduction.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/testing/widget/introduction.html

建议完成时间：3 - 5 天

**Comment by wswdevil** [comment]
认领，今天认领的上一篇快完成了，很有意思。
预计3天完成吧

**Comment by chenglu** [comment]
谢谢对文档翻译的兴趣，感谢你的时间和贡献！

**Comment by Jin-zz** [comment]
#61 - An introduction to widget testing - Widget 测试介绍 
本篇翻译已经圆满完成~感谢大家的贡献！
