### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by wjlotus1992** [cfug/flutter.cn#1429]
### 问题镜像 URL

https://pub.flutter-io.cn

### 错误内容截图或 log

Package not available (could not find package path_provider_android at https://pub.flutter-io.cn/).

### pubspec.yaml

  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      sha256: "592dc01a18961a51c24ae5d963b724b2b7fa4a95c100fe8eb6ca8a5a4732cadf"
      url: "https://pub.flutter-io.cn/"
    source: hosted
    version: "2.0.17"

使用https://pub.dev 可以正常flutter pub get

### flutter doctor -v

Flutter 3.13.10-0.0.pre.6
Dart 3.1.5

**Comment by chenglu** [comment]
应该是上游的问题，目前上游问题已经解决，请再试试看，如果还有问题请再反馈，谢谢！
https://github.com/dart-lang/pub-dev/issues/7624
