### ISSUE TITLE
#62 - Finding widgets - 定位到目标 Widgets 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#143]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/cookbook/testing/widget/finders.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/testing/widget/finders.html

建议完成时间：3 - 5 天

**Comment by wswdevil** [comment]
认领任务，预计两天完成

**Comment by chenglu** [comment]
谢谢 @wswdevil 的时间，任务已经登记。

**Comment by Jin-zz** [comment]
#62 - Finding widgets - 定位到目标 Widgets 
感谢大家的贡献 本篇翻译圆满完成！
