### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题 https://pub.flutter-io.cn/api/packages/path_provider

### ISSUE THREAD

**Issue by ParryingDagger** [cfug/flutter.cn#1430]
### 问题镜像 URL

https://pub.flutter-io.cn/api/packages/path_provider

### 错误内容截图或 log

<detail>pub get返回了旧的内容。导致无法获取最新版本2.1.3

pub get 结果
<img width="1216" alt="pub_get" src="https://github.com/cfug/flutter.cn/assets/25905249/b153fbed-f6b7-47fe-8194-b27630b05692">

直接在浏览器访问
<img width="1465" alt="browser" src="https://github.com/cfug/flutter.cn/assets/25905249/a374534f-6863-49d5-b237-22d5f7fbad14">

<https://pub-web.flutter-io.cn/packages/path_provider/versions>

前端访问也有点问题

versions和scores最新版本2.1.3

其他tab是2.1.2
</detail>

**Comment by AmosHuKe** [comment]
@ParryingDagger Hi~ 再试试，现在应该可以了
![image](https://github.com/cfug/flutter.cn/assets/32262985/a9538332-b8c7-4e47-9b0e-a0c1926b2cd3)

**Comment by ParryingDagger** [comment]
可以了。感谢 @AmosHuKe

**Comment by ParryingDagger** [comment]
@AmosHuKe 你好，发现还有其他库有类似的问题

```shell
$ curl -LSs https://pub.flutter-io.cn/api/packages/video_player | jq | head -n 4
{
  "name": "video_player",
  "latest": {
    "version": "2.8.5",
$ curl -LSs https://pub.flutter-io.cn/api/packages/video_player | jq | head -n 4
{
  "name": "video_player",
  "latest": {
    "version": "2.8.6",
$ curl -LSs https://pub.flutter-io.cn/api/packages/video_player | jq | head -n 4
{
  "name": "video_player",
  "latest": {
    "version": "2.8.5",
$ curl -LSs https://pub.flutter-io.cn/api/packages/video_player | jq | head -n 4
{
  "name": "video_player",
  "latest": {
    "version": "2.8.6",`

**Comment by AmosHuKe** [comment]
CC @AlexV525 @chenglu

**Comment by AlexV525** [comment]
刷新再试？

**Comment by ParryingDagger** [comment]
可以了，谢谢
