### ISSUE TITLE
[Mirror issue] pub镜像没有同步package最新版本

### ISSUE THREAD

**Issue by jialongsu** [cfug/flutter.cn#1434]
### 问题镜像 URL

https://pub-web.flutter-io.cn/packages/fluttertoast

### 错误内容截图或 log

列表显示的最新版本
![image](https://github.com/cfug/flutter.cn/assets/17847087/617f5bca-c2f7-439e-953b-6c19cf8b1a1c)

详情显示的不是最新版本，使用pub get获取的是详情中显示的版本：
![image](https://github.com/cfug/flutter.cn/assets/17847087/9e790f20-d669-4424-955c-bde7da102d7e)

### pubspec.yaml

fluttertoast: ^8.2.5

**Comment by AlexV525** [comment]
刷新再试

**Comment by jialongsu** [comment]
> 刷新再试

刷新什么

**Comment by AlexV525** [comment]
<img width="568" alt="image" src="https://github.com/cfug/flutter.cn/assets/15884415/c7d658d3-ebb1-4188-bb97-ba6fa71bb8ef">

**Comment by AmosHuKe** [comment]
我这边看着没问题了，是最新版本。
![image](https://github.com/cfug/flutter.cn/assets/32262985/3f5e0c42-9f9d-401d-8f9a-9e20a0e37f23)

**Comment by jialongsu** [comment]
> <img alt="image" width="568" src="https://private-user-images.githubusercontent.com/15884415/324337789-c7d658d3-ebb1-4188-bb97-ba6fa71bb8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjE4NjIsIm5iZiI6MTcxMzg2MTU2MiwicGF0aCI6Ii8xNTg4NDQxNS8zMjQzMzc3ODktYzdkNjU4ZDMtZWJiMS00MTg4LWJiOTctYmE2ZmE3MWJiOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA4MzkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZjYyYjMzZDJiNjdiZGVjOTk2MjU1NzIxZTFhM2QyN2E4OTM0ZGQ3MzcyODUwNzdlZWI0NmEwMGZmMjdhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dpnmm5Yd6zCkDQhaeb_87DZzRIu0lVyYwiJcTCJBKtE">

切换tab时版本号会变化，反正就是拉不下来最新的
![zzu4t-yqb3e](https://github.com/cfug/flutter.cn/assets/17847087/381e1546-043f-4a39-b458-ad4dd9f58f01)

**Comment by AlexV525** [comment]
url_launcher 已刷新
