### ISSUE TITLE
[Mirror issue] dart.dev的package的publisher在搜索页都变成了dart.cn

### ISSUE THREAD

**Issue by Dabbit-Chan** [cfug/flutter.cn#1437]
### 问题镜像 URL

https://pub-web.flutter-io.cn/packages?q=http

### 错误内容截图或 log

在[搜索页](https://pub-web.flutter-io.cn/packages?q=http)显示publisher为dart.cn(实际上为dart.dev)
![issue1](https://github.com/cfug/flutter.cn/assets/25811834/27baf4c8-0fa8-4e6d-b4c9-fb66519cba9e)
在[详情页](https://pub-web.flutter-io.cn/packages/http)publisher则正常显示
![issue2](https://github.com/cfug/flutter.cn/assets/25811834/0fba14d3-0201-47ff-bea6-c24f31717e15)

**Comment by chenglu** [comment]
抱歉，我再看一下网址替换规则，预计24小时内修复。

**Comment by chenglu** [comment]
<img width="929" alt="image" src="https://github.com/cfug/flutter.cn/assets/2258420/27024fa3-3d47-474b-825f-f699a83deb3f">

Fixed 如果有任何问题请再开启这个 issue 告知。
