### ISSUE TITLE
#63 - Tapping, dragging and entering text - 点击、拖拽事件和文本输入 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#144]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/cookbook/testing/widget/tap-drag.md

英文文档预览：https://debug.flutter.cn/docs/cookbook/testing/widget/tap-drag.html

建议完成时间：3 - 5 天

**Comment by JasonLinkinBright** [comment]
翻译认领，预计 3 - 5 天

**Comment by Jin-zz** [comment]
感谢 @JasonLinkinBright 的时间！
翻译已成功认领和登记！

**Comment by Jin-zz** [comment]
感谢译者的时间~本篇翻译已完成！
