### ISSUE TITLE
[页面问题] 'Start building Flutter native desktop apps on macOS'

### ISSUE THREAD

**Issue by hubao-1125** [cfug/flutter.cn#1440]
### 页面 URL

https://flutter.cn/docs/get-started/install/macos/desktop/

### 页面源代码地址

https://github.com/cfug/flutter.cn/tree/main/src/get-started/install/macos/desktop.md

### 描述问题

no chinese

### 期望如何修复

have chinese doc

### 我希望能自己修复这个问题

- [ ] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
@hubao-1125 
感谢你的反馈 😄，我们将完成这些内容。
