### ISSUE TITLE
[页面问题] '在屏幕上添加一个 drawer'

### ISSUE THREAD

**Issue by sudot** [cfug/flutter.cn#1445]
### 页面 URL

https://flutter.cn/docs/cookbook/design/drawer/

### 页面源代码地址

https://github.com/cfug/flutter.cn/tree/main/src/cookbook/design/drawer.md

### 描述问题

没有打开 drawer 的相关说明和代码。

### 期望如何修复

请添加打开 drawer 相关的代码和说明。

例如：
### 通过编程打开 drawer

打开 drawer 有两种常用的操作方式。

第一种方式，在 `Builder` 中子组件的点击事件中打开 `drawer`。

```dart
Scaffold(
  appBar: AppBar(
    leading: Builder(
      builder: (context) {
        return IconButton(
          icon: const Icon(Icons.menu),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      },
    ),
  ),
  drawer: Drawer(),
)
```

第二种方式，给定一个 `GlobalKey<ScaffoldState>`，然后你可以使用他来打开 `drawer`。

```dart
final GlobalKey<ScaffoldState> scaffoldStateKey = GlobalKey<ScaffoldState>();
Scaffold(
  key: scaffoldStateKey,
  appBar: AppBar(
    leading: IconButton(
      icon: const Icon(Icons.menu),
      onPressed: () {
        scaffoldStateKey.currentState?.openDrawer();
      },
    ),
  ),
  drawer: Drawer(),
)
```

### 我希望能自己修复这个问题

- [ ] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
感谢你的建议，
由于文档内容（镜像）来源于[上游](https://github.com/flutter/website)，
如果有时间的的话，你可以优先向他们 [提出 Issue](https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Add%20a%20drawer%20to%20a%20screen%27&page-url=https://docs.flutter.dev/cookbook/design/drawer/&page-source=https://github.com/flutter/website/tree/main/src/content/cookbook/design/drawer.md)  或者为他们 PR 参与贡献。
