### ISSUE TITLE
#64 - Introduction to Widgets - Widgets 介绍 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#145]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/widgets-intro.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/widgets-intro

建议完成时间：7 - 10 天

**Comment by xiongcai** [comment]
我是Angela，从事客户端开发近两年，从事React Native开发一年多，之后将接触flutter，工作中可能会遇到，近申请认领这篇文章，预计一周（7天）完成

**Comment by chenglu** [comment]
谢谢 Angela，谢谢上海 GDG 的推荐，我们的 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec) 可能会需要提前阅读一下。
感谢您的时间和贡献！
