### ISSUE TITLE
#65 - Layouts in Flutter - Flutter 中的布局 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#146]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/layout/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/layout

建议完成时间：15 - 20 天

**Comment by xiongcai** [comment]
我是Angela，从事客户端开发近两年，从事React Native开发一年多，之后将接触flutter，工作中可能会遇到，近申请认领这篇文章，预计15 - 20 天完成

**Comment by chenglu** [comment]
谢谢 Angela 的时间和贡献！任务已经确认 + 登记。

**Comment by Jin-zz** [comment]
Helo！@xiongcai 不知翻译进度如何啦，如果翻译完了可以提交 PR 啦
另外注意一下预计时间哦，如果是遇到问题了可以大家讨论看看~

**Comment by cfug-dev** [comment]
稿件需要二次审校，issue 关闭，回头统一处理。
