### ISSUE TITLE
[Mirror issue] 使用 Flutter 中国镜像的问题

### ISSUE THREAD

**Issue by 89ao** [cfug/flutter.cn#1464]
### 问题镜像 URL

N/A

### 错误内容截图或 log

受到清华大学镜像站点（https://mirrors.tuna.tsinghua.edu.cn/flutter/）等成功镜像的启发，我们有意镜像 Flutter 仓库，以提升区域访问速度和性能。
烦请协助解答成为一个flutter授权代理的以下问题：
1. 关于第三方镜像 Flutter 仓库的政策：即如何合法的同步flutter仓库。
2. 需要如何获取必要的授权或协议：即如何获取以及获取哪些必要的授权？
3. 同步和数据完整性的最佳实践：即如何同步数据，同步周期以及如何及时同步到后续的政策变化（如有）？
我们致力于遵守 Flutter 的社区标准，并为全球开发者做出积极贡献。

**Comment by chenglu** [comment]
Flutter 资源均为公开资源，其中 Storage 内容来自 Google Cloud Storage，Pub API 来自 pub.dartlang.org，无需也没有授权即可自由镜像，请注意在镜像运行过程中遵守当地法律法规，中国社区和 Flutter 团队都无法提供任何技术服务支持。

中国镜像采取的解决方案多是反向代理的方式，属于被动请求而非主动同步，贵组织可以自行探索和测试适合你们的解决方案。在运营过程中请注意保护镜像服务器的安全，Flutter 团队正在部署更严格的 SLSA 供应链安全协议，任何对原始文件的改动都可能造成命令行报错，同时建议提供有效的开发者反馈通道。

如果有区域性的访问速度问题，也欢迎再次反馈，我们会调整和优化线路，谢谢！
