### ISSUE TITLE
侧边下拉选项都点不开。

### ISSUE THREAD

**Issue by thousmile** [cfug/flutter.cn#1469]
### 页面 URL

https://docs.flutter.cn/get-started

### 描述问题

侧边栏，下拉选项都打不开！我是最新的chrome浏览器。
![image](https://github.com/user-attachments/assets/d15e1930-2b62-40e9-a35a-05cc8bdf3e96)

![image](https://github.com/user-attachments/assets/aa2c0489-0c0d-4b02-b4d2-8da55fbd3806)

### 我希望能自己修复这个问题

- [ ] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
@thousmile 感谢反馈！

刚才我通过最新版的 Chrome 测试了一下，展开正常。
看报错是你请求相关的库失败。
麻烦你访问一下 https://cdn.staticfile.net/jquery/3.7.0/jquery.min.js 看看能不能正常访问。
再尝试清理一下缓存后重新访问。

**Comment by AlexV525** [comment]
@AmosHuKe 已将静态资源移动到站内，相关请求应该不会出现问题了，如仍有问题可以评论留言，谢谢
