### ISSUE TITLE
#66 - Layout Tutorial - 布局构建教程 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#147]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/layout/tutorial.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/layout/tutorial

建议完成时间：5 - 7 天

**Comment by xiongcai** [comment]
我是Angela，从事客户端开发近两年，从事React Native开发一年多，之后将接触flutter，工作中可能会遇到，近申请认领这篇文章，预计5 - 7 天完成

**Comment by chenglu** [comment]
感谢 @xiongcai 的时间，任务已经确认。
建议不要一次领这么多任务哈，不过能力超强的同学除外 ;-)

**Comment by Jin-zz** [comment]
还有这篇哦 @xiongcai 
要是遇到困难或是最近较忙也可告知我们哒！
辛苦啦

**Comment by xiongcai** [comment]
好的会尽快完成

**Comment by cfug-dev** [comment]
任务超期暂时做关闭处理。
