### ISSUE TITLE
翻译工具有问题

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#1476]
`toc: true` 的时候会在侧边栏根据目录生成锚文本链接

<img width="340" alt="image" src="https://github.com/user-attachments/assets/6132929d-0da6-4959-a0ee-22a782db24bf">

如果类似下面的情况出现，而且二级标题是英文的话，就会出现第链接找不到的 issue。

```
## 二级标题 

### 这是三级标题

```

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/97070f50-cd73-4da7-a484-953632c74824">

初步感觉可能是翻译工具的问题，不是网站部署系统的问题。

cc/ @asnowwolf 帮忙看看？

**Comment by AmosHuKe** [comment]
@chenglu 找到问题了，
被 [tool/translator/gulpfile.js](https://github.com/cfug/flutter.cn/blob/main/tool/translator/gulpfile.js) 替换了，
没有正确判断到不同的分级标题。

**Comment by chenglu** [comment]
OK 那我们就自己解决吧
