### ISSUE TITLE
#67 - Box constraints - 边界约束 (Box constraints) 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#148]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/layout/box-constraints.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/layout/box-constraints

建议完成时间：3 - 5 天

**Comment by linguowu** [comment]
任务认领。

**Comment by chenglu** [comment]
谢谢五哥的时间，辛苦啦 ;-)

**Comment by cfug-dev** [comment]
任务已经完成，谢谢大家！
