### ISSUE TITLE
#68 - Adding interactivity - 交互添加 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#149]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/interactive/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/interactive

建议完成时间：10 - 15 天

**Comment by Vadaski** [comment]
申请翻译

**Comment by chenglu** [comment]
好，尽快完成，辛苦xinlei了

**Comment by Vadaski** [comment]
no prob

**Comment by Vadaski** [comment]
文档翻译已完成，故关闭此 issue

**Comment by chenglu** [comment]
@Jin-zz 微信留言你了，帮忙把新老文档的翻译合并一下，方法是把现在上面的文档里的中文，加入到这里 https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/interactive.md，做好了发个 PR，谢谢。
