### ISSUE TITLE
解压命令写错了，为`Expand-Archive`而非`Extract-Archive`

### ISSUE THREAD

**Issue by up55** [cfug/flutter.cn#1494]
### 页面 URL

https://docs.flutter.cn/community/china/

### 页面源代码地址

https://github.com/cfug/flutter.cn/tree/main/src/content/community/china/index.md

### 描述问题

解压命令为`Expand-Archive`而非`Extract-Archive`
原文：
```
从 zip 压缩文件中解压提取 SDK。
本示例假定你下载了 Windows 版本的 Flutter SDK。
C:> Extract-Archive: flutter_windows_v3.13.0-stable.zip
```

### 我希望能自己修复这个问题

- [ ] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
感谢你的建议~ 这边已经转到了 https://github.com/flutter/website/pull/11112 。

**Comment by AmosHuKe** [comment]
上游已更新，将在下次同步时修复这个问题。
