### ISSUE TITLE
#69 - Assets and images - 添加资源和图片

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#150]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/assets-and-images.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/assets-and-images

建议完成时间：7 - 10 天

**Comment by yantao13145210** [comment]
认领翻译

**Comment by Jin-zz** [comment]
感谢 @yantao13145210 的时间！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！

**Comment by Jin-zz** [comment]
helo! @yantao13145210  如果翻译完了可以准备提交 PR 啦
要是遇到问题了也可以一起讨论看看哦~

**Comment by Jin-zz** [comment]
helo! @yantao13145210 
本翻译项目即将接近尾声~希望能够尽快提交 PR 啦
如果近期较忙或是遇到问题也可告知哦

**Comment by yantao13145210** [comment]
ok，@Jin-zz，最近太忙，今天一定翻译完成，O(∩_∩)O谢谢；

**Comment by yantao13145210** [comment]
初稿翻译完成 #69 @Jin-zz

**Comment by cfug-dev** [comment]
谢谢译者 @yantao13145210 和校对者 @liuzhen0218 的配合，本任务已经完成，再次感谢大家的时间！
