### ISSUE TITLE
Cannot compile in the embedded Dartpad

### ISSUE THREAD

**Issue by wow-222** [cfug/flutter.cn#1505]
### 页面 URL

https://docs.flutter.cn/cookbook/navigation/navigation-basics/

### 页面源代码地址

https://github.com/cfug/flutter.cn/tree/main/src/content/cookbook/navigation/navigation-basics.md

### 描述问题

<img width="632" alt="Screenshot 2024-10-09 at 20 40 08" src="https://github.com/user-attachments/assets/0d5d3e22-6110-4fe7-957f-87f648f9c89c">
<img width="786" alt="Screenshot 2024-10-09 at 20 39 55" src="https://github.com/user-attachments/assets/f4a56190-feba-4230-8881-ce5dcc0e5f1b">

### 我希望能自己修复这个问题

- [ ] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
@chenglu

**Comment by wow-222** [comment]
"https://stableapi.dartpad.cn/api/v3/analyze" should change to "https://stable.api.dartpad.dev/api/v3/version" ?

**Comment by AmosHuKe** [comment]
看起来已经没有相关报错，可以正常运行了。
再次感谢 @wow-222 你的反馈~ 
如果后续还有问题欢迎随时反馈。
