### ISSUE TITLE
#71 - Introduction to animations - 动画效果介绍 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#152]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/animations

建议完成时间：5 - 7 天

**Comment by wswdevil** [comment]
认领，五天完成

**Comment by Jin-zz** [comment]
抱歉回复晚啦，任务已经成功认领和登记！谢谢 @wswdevil的时间
翻译时遇到的格式问题可查阅[文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！再次感谢！

**Comment by wswdevil** [comment]
抱歉因为生病和假期耽搁了，尽快完成

**Comment by Jin-zz** [comment]
感谢大家的贡献~本篇翻译已完成
