### ISSUE TITLE
翻译此篇文档

### ISSUE THREAD

**Issue by chengp97** [cfug/flutter.cn#1525]
### 页面 URL

https://docs.flutter.cn/ui/adaptive-responsive/safearea-mediaquery/

### 页面源代码地址

https://github.com/cfug/flutter.cn/tree/main/src/content/ui/adaptive-responsive/safearea-mediaquery.md

### 描述问题

英文文档，没有中文翻译

### 期望如何修复

中文文档

### 我希望能自己修复这个问题

- [X] 我将自己尝试修复这个问题

**Comment by AmosHuKe** [comment]
感谢你的反馈，已发布为任务 https://github.com/cfug/flutter.cn/issues/1526
