### ISSUE TITLE
#72 - Animations Overview - 动画概览 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#153]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/overview.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/animations/overview

建议完成时间：7 - 10 天

**Comment by nervouself** [comment]
我想翻译这篇文章

**Comment by Jin-zz** [comment]
@nervouself  翻译已成功认领和登记~
再次感谢参与贡献！

**Comment by cfug-dev** [comment]
翻译完成，有个标题的格式问题，我稍后统一处理一下。
