### ISSUE TITLE
#73 - Animations Tutorial - 在 Flutter 应用里实现动画效果 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#154]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/tutorial.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/animations/tutorial

建议完成时间：10 - 15 天

**Comment by wswdevil** [comment]
认领，和hero animation一起翻

**Comment by Jin-zz** [comment]
再次感谢 @wswdevil 的时间！辛苦啦 期待你的翻译

**Comment by Jin-zz** [comment]
Helo！@wswdevil 如果翻译完了可以提交 PR 啦
要是遇到困难了可以一起讨论看看哦~

**Comment by Jin-zz** [comment]
Flutter 中文文档翻译项目就快接近尾声啦 还请注意一下完成时间~@wswdevil
如果最近较忙或是遇到其他问题也可以告诉我们哦

**Comment by wswdevil** [comment]
抱歉，这篇早就完成了，一直没pull
