### ISSUE TITLE
#74 - Hero animations - 主动画 (Hero animations) 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#155]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/hero-animations/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/animations/hero-animations

建议完成时间：10 - 15 天

**Comment by wswdevil** [comment]
认领翻译

**Comment by Jin-zz** [comment]
感谢 @wswdevil ！
翻译格式问题可参考 [文档格式要求](https://github.com/cfug/flutter.cn/wiki/Translation-Spec) 
以及 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide)
期待你的翻译！再次感谢 辛苦啦

**Comment by Jin-zz** [comment]
@wswdevil 还有这篇翻译 ~ 关注下预期完成时间哦
有问题的话随时沟通呀！

**Comment by Jin-zz** [comment]
这篇翻译也请注意一下哦，我们的翻译项目即将接近尾声啦
近期较忙或是遇到困难也请告知哦！ @wswdevil
