### ISSUE TITLE
#75 - Staggered animations - 交织动画 (Staggered animations)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#156]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/staggered-animations/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/animations/staggered-animations

建议完成时间：5 - 7 天

**Comment by chenglu** [comment]
该任务已经完成。
