### ISSUE TITLE
#76 - Slivers - 滑动效果 (Slivers) 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#157]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/advanced/slivers.md

英文文档预览：https://flutter.cn/docs/development/ui/advanced/slivers

建议完成时间：1 - 3 天

**Comment by Jin-zz** [comment]
认领一下

**Comment by chenglu** [comment]
谢谢 @Jin-zz 的时间，任务已经成功认领和登记。
初次翻译，建议阅读 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec) 这个文档学习一下本次翻译项目的翻译格式。
再次感谢！（抱歉回复晚了
