### ISSUE TITLE
#77 - Gestures - 点击、拖动和其他手势

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#158]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/advanced/gestures.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/advanced/gestures

建议完成时间：5 - 7 天

**Comment by Zhiw** [comment]
翻译认领，预计 3-5 天

**Comment by Jin-zz** [comment]
抱歉回复晚了~翻译已成功认领和登记！辛苦啦

**Comment by cfug-dev** [comment]
任务已经完成，谢谢大家！
