### ISSUE TITLE
#78 - Widget catalog - 核心 Widget 目录 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#159]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/widgets/index.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/widgets

建议完成时间：1 - 3 天

**Comment by bestony** [comment]
认领本文
完成时间 5月12日

**Comment by Jin-zz** [comment]
感谢 @bestony！翻译已成功认领和登记！已在审核中 辛苦啦

**Comment by Jin-zz** [comment]
本篇翻译已完成 感谢大家贡献
