### ISSUE TITLE
#79 - Introduction - 状态管理介绍 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#160]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/intro.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/intro

建议完成时间：1 - 3 天

**Comment by bestony** [comment]
认领文章
预计完成时间 5月12日

**Comment by Jin-zz** [comment]
感谢@bestony！真棒！

**Comment by Jin-zz** [comment]
本篇翻译已完成 感谢大家贡献！
