### ISSUE TITLE
#80 - Think declaratively - 声明式的编程思维 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#161]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/intro.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/intro

建议完成时间：3 - 5 天

**Comment by Iamnotromantic** [comment]
翻译认领，预计6月10号完成

**Comment by Jin-zz** [comment]
翻译已成功认领和登记，感谢@Iamnotromantic的时间！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！

**Comment by cfug-dev** [comment]
该任务已经完成，感谢大家的时间！
