### ISSUE TITLE
#81 - Ephemeral vs app state - 短时 (ephemeral) 和共享 (app) 状态

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#162]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app

建议完成时间：5 - 7 天

**Comment by cfug-dev** [comment]
assign to @tyisme614, thanks for the time.

**Comment by Jin-zz** [comment]
翻译已登记！提前感谢 @tyisme614 的帮忙~

**Comment by Jin-zz** [comment]
本篇翻译重新开放认领~

**Comment by zhuangtao97** [comment]
I do it

**Comment by chenglu** [comment]
@zhuangtao97 抱歉，我们的发布时间临近，这篇文章的的交稿和 review 时间不够了，是否可以请帮忙到 PR 页面为已提交稿件作出评论和改进意见？

**Comment by zhuangtao97** [comment]
@chenglu  好的。我就校对一下 https://github.com/cfug/flutter.cn/issues/167 这个吧

**Comment by zhuangtao97** [comment]
@chenglu  校对了https://github.com/cfug/flutter.cn/pull/323这个，167有其他道友校对过了。

**Comment by zhuangtao97** [comment]
@chenglu 167 有道友校对过，对 [https://github.com/cfug/flutter.cn/pull/323](url) 校对了一下。

**Comment by chenglu** [comment]
该任务已经完成，Issue closed, thanks!
