### ISSUE TITLE
#83 - Options - 状态管理参考 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#164]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/options

建议完成时间：3 - 5 天

**Comment by changer0** [comment]
我要认领翻译该篇文章

**Comment by yeqiling** [comment]
我要认领翻译该篇文章

**Comment by Jin-zz** [comment]
感谢@changer0的时间，翻译已成功认领和登记！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译呀

**Comment by Jin-zz** [comment]
由于翻译项目即将接近尾声~翻译完的话希望能尽快提交 PR 哦 @changer0 
再次感谢你的时间~辛苦辽

**Comment by changer0** [comment]
基本完工，还需几个地方确认，会尽快提交PR，感谢提醒 @Jin-zz

**Comment by changer0** [comment]
@Jin-zz 有部分链接打开 404，这种如何处理~

**Comment by yeqiling** [comment]
我来认领校对

**Comment by Jin-zz** [comment]
> 
> 
> @Jin-zz 有部分链接打开 404，这种如何处理~
不知是哪个链接。。我查了一遍好像没看到有 404 的
另外链接的翻译，如果是 Flutter 站内的链接，可以采用对应链接里的已经翻译过的标题，
如果是站外的，能理解意思即可，当然偶尔也有不翻译的情况，随机应变哈哈
Reviewer 也会比我专业一些，可以向她请教，翻译很赞，格式完整，也很通顺

**Comment by changer0** [comment]
抱歉打扰 ^v^， 发现问题所在了。 @Jin-zz 
我看到很多地址都是这样的： {{site.flutter-medium}}/build-reactive-mobile-apps-in-flutter-companion-article-13950959e381  所以在我自己的GitHub仓库中访问就会找不到路径。
而在 https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/options 就可以 ~

**Comment by chenglu** [comment]
👍 提醒一下，翻译之后的稿件需要保留类似 {{site.flutter-medium}} 的引用哈 ;-)

**Comment by changer0** [comment]
已保留~

**Comment by cfug-dev** [comment]
本任务已经完成，感谢大家的时间。
