### ISSUE TITLE
#85 - Firebase - 使用 Firebase 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#166]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/firebase.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/firebase

建议完成时间：1 - 3 天

**Comment by Jin-zz** [comment]
感谢 @bestony 的认领！PR 已在审核中！辛苦啦

**Comment by Jin-zz** [comment]
本篇翻译圆满完成！感谢大家的贡献
