### ISSUE TITLE
#86 - Accessibility - 无障碍 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#167]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/accessibility-and-localization/accessibility.md

英文文档预览：https://debug.flutter.cn/docs/development/accessibility-and-localization/accessibility

建议完成时间：3 - 5 天

**Comment by zhangjiana** [comment]
我要认领这个任务，预计6月10号完成

**Comment by lennonover** [comment]
任务认领

**Comment by Jin-zz** [comment]
那就麻烦@lennonover啦 ，翻译已成功认领和登记！感谢你的时间~
格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)

**Comment by zhuangtao97** [comment]
这个我来校对吧

**Comment by cfug-dev** [comment]
本任务已经完成，谢谢大家的时间！
