### ISSUE TITLE
#87 - Internationalization - Flutter 应用里的国际化

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#168]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

英文文档预览：https://debug.flutter.cn/docs/development/accessibility-and-localization/internationalization

建议完成时间：7 - 10 天

**Comment by git-patrickliu** [comment]
认领这篇

**Comment by Jin-zz** [comment]
感谢 @git-patrickliu 的时间！翻译已成功认领和登记
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译呀

**Comment by git-patrickliu** [comment]
已完成翻译，正在内部校对中...

**Comment by cfug-dev** [comment]
任务完成，谢谢大家的时间。
