### ISSUE TITLE
#88 - Writing platform-specific code - 撰写双端平台代码 (插件编写实现) 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#169]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/platform-integration/platform-channels.md

英文文档预览：https://debug.flutter.cn/docs/development/platform-integration/platform-channels

建议完成时间：7 - 10 天

**Comment by nanjingboy** [comment]
任务认领

**Comment by chenglu** [comment]
谢谢周末的时间！
