### ISSUE TITLE
#90 - Developing packages & plugins - Package 的开发和提交 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#171]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

英文文档预览：https://debug.flutter.cn/docs/development/packages-and-plugins/developing-packages

建议完成时间：5 - 7 天

**Comment by nanjingboy** [comment]
任务认领

**Comment by chenglu** [comment]
抱歉回复晚了，谢谢 Tom @nanjingboy 的时间，翻译任务已经确认和登记，感谢！
