### ISSUE TITLE
#91 - Background processes - 后台进程 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#172]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/packages-and-plugins/background-processes.md

英文文档预览：https://debug.flutter.cn/docs/development/packages-and-plugins/background-processes

建议完成时间：1 - 3 天

**Comment by bestony** [comment]
认领本文
预计完成时间 5月12日

**Comment by Jin-zz** [comment]
再次感谢@bestony ！翻译已在审核中啦

**Comment by Jin-zz** [comment]
本篇翻译已完成！大家辛苦啦
