### ISSUE TITLE
#92 - Android Studio / IntelliJ - 在 Android Studio 或类 IntelliJ 里开发 Flutter 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#173]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/android-studio.md

英文文档预览：https://debug.flutter.cn/docs/development/tools/android-studio

建议完成时间：7 - 10 天

**Comment by SouthernBox** [comment]
我来认领啦

**Comment by chenglu** [comment]
感谢认领任务～已经确认。

**Comment by Jin-zz** [comment]
#92 - Android Studio / IntelliJ - 在 Android Studio 或类 IntelliJ 里开发 Flutter 应用
翻译圆满完成啦，已经由 @chenglu merge了
辛苦啦大家
