### ISSUE TITLE
#93 - Visual Studio Code - 在 VS Code 里开发 Flutter 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#174]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/vs-code.md

英文文档预览：https://debug.flutter.cn/docs/development/tools/vs-code

建议完成时间：5 - 7 天

**Comment by xilihuasi** [comment]
翻译认领

**Comment by chenglu** [comment]
感谢 @xilihuasi 的时间，任务认领已经确认。请在提交 PR 的时候 refer 到这个 Issue 哈，感谢～

**Comment by Jin-zz** [comment]
helo! @xilihuasi 翻译进度如何呢，翻译完的话可以提交 PR 啦
要是遇到问题的话可以一起讨论看看！辛苦啦 再次感谢~

**Comment by xilihuasi** [comment]
非常抱歉，最近有事耽搁了。已经翻译完了，晚上我会提交 PR。后面我会安排好时间，抱歉！

**Comment by Jin-zz** [comment]
本篇翻译已完成~感谢大家的贡献呀
