### ISSUE TITLE
#94 - Upgrading - 升级你的 Flutter 版本

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#175]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/sdk/upgrading.md

英文文档预览：https://debug.flutter.cn/docs/development/tools/sdk/upgrading

建议完成时间：3 - 5 天

**Comment by reachzhai** [comment]
认领翻译

**Comment by Jin-zz** [comment]
感谢 @reachzhai 的时间！
翻译格式问题可参考 [中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)
期待翻译！辛苦啦

**Comment by Jin-zz** [comment]
Helo！@reachzhai  不知翻译进度如何啦 
遇到困难的话可以一起讨论看看哦

**Comment by Jin-zz** [comment]
@reachzhai 由于翻译项目即将接近尾声~还请注意一下完成时间哦
近期较忙或是遇到问题也可告知哦！

**Comment by cfug-dev** [comment]
本任务收回。

**Comment by Realank** [comment]
认领翻译，本周末完成
