### ISSUE TITLE
#95 - Releases - Flutter SDK 版本列表

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#176]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/sdk/releases.md

英文文档预览：https://debug.flutter.cn/docs/development/tools/sdk/releases

建议完成时间：1 - 3 天

**Comment by bestony** [comment]
@wanglin6600 此文件似乎已经翻译完成了

**Comment by chenglu** [comment]
好，这个是我之前为了做 Flutter 版本更新自动发微博页面的时候翻译的。
