### ISSUE TITLE
#97 - Code formatting - 代码格式 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#178]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/formatting.md

英文文档预览：https://debug.flutter.cn/docs/development/tools/formatting

建议完成时间：3 - 5 天

**Comment by wonderful89** [comment]
认领，时间 3～5 天

**Comment by Jin-zz** [comment]
感谢 @wonderful89 抽出宝贵时间参与
任务已成功认领和登记啦！格式问题可参阅文档 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！

**Comment by Jin-zz** [comment]
#97 - Code formatting - 代码格式
本篇翻译已完成~感谢大家抽出时间参与贡献
