### ISSUE TITLE
#98 - Debugging - 调试 Flutter 应用 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#179]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/testing/debugging.md

英文文档预览：https://debug.flutter.cn/docs/testing/debugging

建议完成时间：10 - 15 天

**Comment by kira159357** [comment]
I  want to translate this passage

**Comment by chenglu** [comment]
Hi @kira159357, thanks for your time, would like to have your self introduction first here at #3 .

**Comment by Jin-zz** [comment]
之前的译者因为个人问题退出啦 欢迎大家继续认领和翻译

**Comment by chenglu** [comment]
assigned

**Comment by chenglu** [comment]
任务完成。
