### ISSUE TITLE
[翻译] /docs/deployment/flavors.html

### ISSUE THREAD

**Issue by yanyixin** [cfug/flutter.cn#18]
希望完成该文档的翻译。
文章链接: https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/flavors.md

**Comment by chenglu** [comment]
确认，请安排时间开始翻译，完成翻译之后请发 PR，谢谢！

**Comment by chenglu** [comment]
@yanyixin 嗨，请告知完成时间 ;-)
