### ISSUE TITLE
#100 - Flutter's build modes - Flutter 的构建模式选择

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#181]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/testing/build-modes.md

英文文档预览：https://debug.flutter.cn/docs/testing/build-modes

建议完成时间：3 - 5 天

**Comment by yanyixin** [comment]
认领翻译

**Comment by Jin-zz** [comment]
感谢@yanyixin的时间！
翻译格式问题可参考[中文文案排版指南](https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译~再次感谢

**Comment by Jin-zz** [comment]
由于翻译项目即将接近尾声，如果翻译完的话还请尽快提交 PR 呀
辛苦啦  感谢小姐姐的贡献先！ @yanyixin

**Comment by chenglu** [comment]
谢谢 @yanyixin 帮忙翻译，也恭喜成为 Flutter 的 contributor！
