### ISSUE TITLE
#102 - Performance best practices - 性能优化最佳实践 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#183]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/testing/best-practices.md

英文文档预览：https://debug.flutter.cn/docs/testing/best-practices

建议完成时间：5 - 7 天

**Comment by talisk** [comment]
认领该任务，预计 1 - 3 天

**Comment by chenglu** [comment]
谢谢恺哥的认领和时间。

**Comment by Jin-zz** [comment]
helo！@talisk  还记得这篇翻译么哈哈 
翻译完了可以提交 PR 啦，感谢呀

**Comment by Jin-zz** [comment]
helo！@talisk
由于本翻译项目接近尾声~还请希望尽快提交 PR 哦 
感谢！如果近期较忙或遇到问题也可告知

**Comment by chenglu** [comment]
谢谢恺哥！
