### ISSUE TITLE
#104 - Creating flavors for Flutter - 配置 flavors 构建双端 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#185]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/flavors.md

英文文档预览：https://debug.flutter.cn/docs/deployment/flavors

建议完成时间：1 - 3 天

**Comment by reachzhai** [comment]
认领此文档
预计完成时间 5 月 15 日。

**Comment by Jin-zz** [comment]
感谢 @reachzhai 的时间！
翻译格式问题可参考 中文文案排版指南[https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide](url) 以及 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译！再次感谢

**Comment by Jin-zz** [comment]
#104 - Creating flavors for Flutter - 配置 flavors 构建双端 
本篇翻译已经完成啦 感谢大家的贡献！
