### ISSUE TITLE
#105 - Build and release for Android - 打包和发布到 Android 平台 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#186]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/android.md

英文文档预览：https://debug.flutter.cn/docs/deployment/android

建议完成时间：5 - 7 天

**Comment by qiuyuezhong** [comment]
任务认领，第一次做，试试看～～

**Comment by chenglu** [comment]
@qiuyuezhong 谢谢你的时间，为你点赞！辛苦啦。

**Comment by cfug-dev** [comment]
v1 任务完成。
