### ISSUE TITLE
#106 - Build and release for iOS - 打包和发布到 iOS 平台 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#187]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/ios.md

英文文档预览：https://debug.flutter.cn/docs/deployment/ios

建议完成时间：5 - 7 天

**Comment by bestony** [comment]
认领此文档
预计完成时间 5 月 10 日。

**Comment by chenglu** [comment]
谢宦成兄的认领和贡献！

**Comment by Jin-zz** [comment]
helo！@bestony 还记得这篇翻译么哈哈
不知进度如何啦，翻译完可以提交 PR 啦！

**Comment by Jin-zz** [comment]
helo！@bestony 
由于本翻译项目接近尾声，翻译完的话希望能尽快提交 PR~
如果近期较忙或是遇到问题也可告知哦

**Comment by bestony** [comment]
好的，我尽快发起 PR

**Comment by cfug-dev** [comment]
任务完成，谢谢大家！
