### ISSUE TITLE
#107 - Continuous deployment with fastlane - 使用 fastlane 持续交付

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#188]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/fastlane-cd.md

英文文档预览：https://debug.flutter.cn/docs/deployment/fastlane-cd

建议完成时间：3 - 5 天

**Comment by panda8z** [comment]
任务认领 预计5月27日完成。

**Comment by Jin-zz** [comment]
再次感谢 @panda8z~
翻译已成功认领和登记！

**Comment by Jin-zz** [comment]
helo！@panda8z 还记得这篇翻译嘛 哈哈
翻译完可以提交 PR 啦，如果遇到问题的话也可讨论看看哦

**Comment by cfug-dev** [comment]
超期未修改 / 跟进稿件，issue 关闭，内容未来统一处理。
