### ISSUE TITLE
#109 - Inside Flutter - Flutter 工作原理 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#190]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/resources/inside-flutter.md

英文文档预览：https://debug.flutter.cn/docs/resources/inside-flutter

建议完成时间：15 - 20 天

**Comment by nanjingboy** [comment]
任务认领

**Comment by Jin-zz** [comment]
感谢 @nanjingboy 的时间，任务已成功认领和登记！
格式问题可参照 [文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)
期待你的翻译，辛苦啦

**Comment by cfug-dev** [comment]
谢谢 @nanjingboy 和各位 reviewers 的帮助，该篇翻译已经完成！
