### ISSUE TITLE
#111 - Technical videos - 学习 Flutter 的视频列表

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#191]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/resources/videos.md

英文文档预览：https://debug.flutter.cn/docs/resources/videos

建议完成时间：3 - 5 天

**Comment by panda8z** [comment]
认领任务  预计5月24号完成

**Comment by Jin-zz** [comment]
感谢 @panda8z 的时间！
翻译已成功认领和登记 辛苦啦 期待你的翻译

**Comment by cfug-dev** [comment]
超期未修改 / 跟进稿件，issue 关闭，内容未来统一处理。
