### ISSUE TITLE
#112 - FAQ - 常见问题解答 

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#192]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/resources/faq.md

英文文档预览：https://debug.flutter.cn/docs/resources/faq

建议完成时间：15 - 20 天

**Comment by chenglu** [comment]
任务认领。

**Comment by chenglu** [comment]
@Jin-zz 排版结束之后，帮我直接发 PR，感谢！

**Comment by chenglu** [comment]
遥远的感谢 Anna 老师，谢谢 Google 的资源。
