### ISSUE TITLE
#114 - Platform adaptations - 平台行为差异和适配

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#200]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/platform-adaptations.md

英文文档预览：https://debug.flutter.cn/docs/resources/platform-adaptations

建议完成时间：3 - 5 天

**Comment by chunlea** [comment]
认领，时间 3～5 天

**Comment by chenglu** [comment]
谢谢 @chunlea 的时间，辛苦啦。这篇文档是今天刚发布的，本来还想发个朋友圈号召一下大家呢～
请安排时间完成翻译，注意我们的[翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)，再次感谢！

**Comment by chunlea** [comment]
进度更新：整篇已经翻译完成，再需要一两天润色一下全篇之后提交 PR。

**Comment by chenglu** [comment]
PR merged，任务已经出色完成，非常感谢！
