### ISSUE TITLE
#115 - Introduction to declarative UI - 声明式 UI 介绍

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#217]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/declarative.md

英文文档预览：https://debug.flutter.cn/docs/get-started/flutter-for/declarative

建议完成时间：3 - 5 天

**Comment by bestony** [comment]
认领此文档
预计完成时间 4 月 28 日。

**Comment by Jin-zz** [comment]
谢谢 @bestony贡献宝贵时间 ~抱歉回复晚啦 
任务已经成功认领和登记~
翻译时请注意格式 详情可查看[文档翻译格式](https://github.com/cfug/flutter.cn/wiki/Translation-Spec)~再次感谢！

**Comment by Jin-zz** [comment]
#115 - Introduction to declarative UI - 声明式 UI 介绍
翻译任务顺利完成！感谢大家贡献！
