### ISSUE TITLE
[翻译] /docs/get-started/editor.html

### ISSUE THREAD

**Issue by youngyou** [cfug/flutter.cn#22]
希望完成该文档的翻译。
文章链接: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/editor.md

**Comment by chenglu** [comment]
👍 请安排时间翻译这篇文档，建议可以在 #3 做一下自我介绍。
谢谢您的时间。

**Comment by chenglu** [comment]
感谢！
