### ISSUE TITLE
'给 iOS 开发者的 Flutter 指南' page issue

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#282]
Page URL: https://flutter.cn/docs/get-started/flutter-for/ios-devs
Page source: https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/ios-devs.md
Description of issue: 
文章非常赞，但还有一点小问题。我没有找到原 issue，麻烦帮 @原译者 再 check 一下😉

（1. 如何退回到 iOS 原生的 viewcontroller？描述部分未正确使用换行
（2.如何监听 iOS 中的生命周期？ 描述部分格式有误
（3.如何确定列表中被点击的元素？ 描述部分未正确使用换行

**Comment by chenglu** [comment]
@iCell

**Comment by iCell** [comment]
@Vadaski 看上去都是换行的格式问题，会很快得到修复，感谢你的反馈。

**Comment by iCell** [comment]
#317

**Comment by chenglu** [comment]
Thanks!
