### ISSUE TITLE
自我介绍 - Self Introductions

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#3]
请在这个 Issue 下简要介绍自己的背景和关于 Flutter 的技术程度，再次谢谢你对 Flutter 文档的贡献！

**Comment by LyndonChin** [comment]
报名！

我叫梁飞，目前在杭州某大厂做前端开发，之前有过4年的Android开发经验。

业余时间维护了一个技术公众号和知乎专栏「老梁写代码」，去年在Github专门建了一个repo翻译Kotlin的官方教程，非常喜欢Flutter，而且对“翻译事业”很有热情。望组织收留。

**Comment by youngyou** [comment]
大家好！

我叫于京洋, 英文名字 Keyon You (`You` 来自西方姓氏转换)，目前在天津从事前端开发，一年后端及三年前端开发经验。

对一些前沿技术比较感兴趣，也想为开源社区做点贡献。

第一次从事翻译工作，希望大家多多指导。

**Comment by ziank** [comment]
翟现旗，目前在杭州某猪厂做iOS开发4年了，对最新的Flutter感兴趣，也希望能够做一点贡献吧。
没怎么做过文章翻译，希望大家多多指导。

**Comment by DongXYZ** [comment]
大家好，我是萌东（忠东），初来乍到，请多指教！

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)

俺是大妈, 对一切对生产力提高有帮助的好技术都有兴趣的大妈;

主持翻译出版过两本技术图书, 也原创出过一本;

当然, 更多的是各种小众技术文档的嗯哼...

**Comment by Vadaski** [comment]
大家好！
我是王鑫磊，现在是一名大三学生。接触flutter快一年了，非常喜欢！第一次参加翻译工作，希望大家多多指教～😆

**Comment by noahziheng** [comment]
大家好！
我是高梓恒, And u can call me Noah Gao。介于大四毕业和校招入职的中间阶段，在杭州某大厂做前端，大学做过部分混合的移动端开发（伪·全栈）。
掘金翻译计划译者，管理团队成员，水平一般，能力有限，还望大家多多指教~

**Comment by MzoneCL** [comment]
马从锂，目前在成都读大学，大三年级。去年12份开始接触Flutter，并喜欢上Flutter。
很高兴参与Flutter文档翻译计划，能够贡献自己的绵薄之力。
还请各位大佬多多指教啦~

**Comment by bestony** [comment]
白宦成，目前 Base 在深圳，自己在使用 Flutter 开发一些应用。

我还是 Linux中国 翻译组核心成员，技术组组长 @LCTT

**Comment by kira159357** [comment]
大家好，我是一名大二英语专业学生，喜欢科技和翻译，多次参加翻译比赛。对移动运用程序开发框架很有兴趣，初来乍到请多多指教

**Comment by panda8z** [comment]
张向北，英文名: Panda 深圳高新园某互联网公司移动端开发，3年Android开发经验，18个月ReactNative开发经验，两个月 Flutter玩具型实战经验，目前还在学习Flutter，英文读写能力良好，非常喜欢flutter ，望组织收留。😁
