### ISSUE TITLE
YT 视频替换备忘

### ISSUE THREAD

**Issue by wanglin6600** [cfug/flutter.cn#345]
文档位置：docs/development/tools/inspector.md

文字：
For a more complete demonstration of the inspector, see the
[DartConf 2018 talk](https://www.youtube.com/watch?v=JIcmJNT9DNI).

https://www.bilibili.com/video/av55813252/	

//player.bilibili.com/player.html?aid=55813252&cid=97569498&page=1

**Comment by chenglu** [comment]
该文档已经过时了被替换成一个外网链接了，不过内容似乎仍然有效。
@Vadaski xinlei 来帮忙把这个文档翻译一下吧？
https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/inspector.md

Thanks~!

**Comment by Vadaski** [comment]
ok～

**Comment by chenglu** [comment]
谢谢鑫磊！
