### ISSUE TITLE
Developing packages & plugins - Package 的开发和提交 - 补全

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#354]
https://debug.flutter.cn/docs/development/packages-and-plugins/developing-packages#adding-licenses-to-the-license-file

这部分的翻译应该是后期加入的，需要翻译。

**Comment by chenglu** [comment]
@nanjingboy 来试试看？

**Comment by nanjingboy** [comment]
@chenglu OK，这两天抽空看下

**Comment by chenglu** [comment]
👍
