### ISSUE TITLE
翻译格式有误,辛苦更正一下

### ISSUE THREAD

**Issue by yeqiling** [cfug/flutter.cn#359]
https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/android-devs.md
intent处,缺少一个括号.
![image](https://user-images.githubusercontent.com/9656440/59666648-d5af0200-91e7-11e9-9dd9-1951e5a38839.png)

**Comment by yeqiling** [comment]
@chenglu 发现一个翻译问题,辛苦帮忙更正一下

**Comment by yeqiling** [comment]
发现了网站上的第二处错误
译文:
![image](https://user-images.githubusercontent.com/9656440/59668227-afd72c80-91ea-11e9-9cd7-b20913daa8bf.png)
网站:
![image](https://user-images.githubusercontent.com/9656440/59668180-99c96c00-91ea-11e9-9714-568436105bf6.png)

**Comment by yeqiling** [comment]
第三处问题
译文:
![image](https://user-images.githubusercontent.com/9656440/59669172-58d25700-91ec-11e9-9f74-a5c9d37bc4b2.png)
网站:
![image](https://user-images.githubusercontent.com/9656440/59669227-6be52700-91ec-11e9-9eec-51a7f4bd44f9.png)

**Comment by chenglu** [comment]
已经提交了第一版，等半个小时之后看看编译结果。
表格的翻译格式看起来是没错儿的，有问题的话我再找人请教和帮忙，谢谢提出！

**Comment by chenglu** [comment]
@yeqiling 请帮忙验证，问题在 debug server: https://debug.flutter.cn/docs/get-started/flutter-for/android-devs
已经得以解决。

**Comment by yeqiling** [comment]
问题一和问题三刚验证了下,已解决.
问题二标题问题也改善了,但是似乎丢失了一点翻译.
![image](https://user-images.githubusercontent.com/9656440/59731834-4b63ae00-927a-11e9-9565-881ab1ce9d4d.png)
@chenglu 辛苦大大再查看下.

**Comment by chenglu** [comment]
![image](https://user-images.githubusercontent.com/2258420/59734121-cc26a800-9282-11e9-9143-0e89a15952ee.png)
fixed
