### ISSUE TITLE
'状态管理中的声明式编程思维' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#372]
Page URL: https://flutter-io.cn/docs/development/data-and-backend/state-mgmt/declarative.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/declarative.md

在入门指南中你可以阅读更多有关声明式编程思维的信息。
Read more about the declarative approach to UI programming in the get started guide.

这里的中文翻译没有对声明式加入链接。
![image](https://user-images.githubusercontent.com/47591151/60148973-b0cd1700-9805-11e9-8221-c8e1e7c59630.png)

**Comment by chenglu** [comment]
@Jin-zz

**Comment by Jin-zz** [comment]
收到

**Comment by chenglu** [comment]
good!
