### ISSUE TITLE
'打包和发布到 Android 平台' page issue

### ISSUE THREAD

**Issue by yalikes** [cfug/flutter.cn#376]
Page URL: https://flutter-io.cn/docs/deployment/android.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/android.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: 这上面说"This page describes the Android release process as of the 1.7.4 release of the Flutter SDK.",Flutter SDK最新的版本不才是1.5.4么,难道是我的理解有问题?

**Comment by chenglu** [comment]
可以参见 [这个页面](https://flutter-io.cn/docs/development/tools/sdk/releases)，Flutter 的 Dev Channel 已经发布到 v1.7.8 啦。

**Comment by chenglu** [comment]
有任何问题和跟进请再开启本 issue，先关闭啦。
