### ISSUE TITLE
'在 Windows 操作系统上安装和配置 Flutter 开发环境' page issue

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#380]
Page URL: https://flutter-io.cn/docs/get-started/install/windows.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/install/windows.md

今天检查 Flutter 社区推送文章的时候发现了几处错误，周末研究一下。

![image](https://user-images.githubusercontent.com/2258420/60325847-ec5d1200-99ba-11e9-9ecb-9d38a09c2d57.png)

**Comment by chenglu** [comment]
SDK 页面点开之后是英文，官网已经链接到 release 页面了，下面 User variables 的描述，似乎应该有对应的中文。

**Comment by chenglu** [comment]
另外，flutter_console.bat 似乎重复了，请 @asnowwolf 帮忙排查一下？

![image](https://user-images.githubusercontent.com/2258420/60334484-33083780-99ce-11e9-874c-6e099be1a71d.png)

**Comment by Vadaski** [comment]
> SDK 页面点开之后是英文，官网已经链接到 release 页面了，下面 User variables 的描述，似乎应该有对应的中文。

建议翻译为 「用户环境变量」

**Comment by cfug-dev** [comment]
@Vadaski 是否有 Windows 操作系统，可以看看这个具体是怎么翻译的？

ref: https://blog.csdn.net/palmer_kai/article/details/80588594
![image](https://user-images.githubusercontent.com/47591151/60427417-3fd49780-9c29-11e9-89c6-0c94e297fa38.png)

**Comment by Vadaski** [comment]
嗯，我在 Windows 电脑上查看过了，这里是叫做 用户变量，建议就翻译为 用户变量

**Comment by chenglu** [comment]
吃完饭来家门口的苏宁看了一下，叫「用户变量」
![5021561984161_ pic](https://user-images.githubusercontent.com/2258420/60436689-26d6e100-9c3f-11e9-85b0-08e2780a1fd2.jpg)

**Comment by Vadaski** [comment]
哈哈。666

**Comment by chenglu** [comment]
这个任务要 pending 一下，看看雪狼兄是否可以抽空帮忙看一下生成之后的内容，缘何中文和英文都多了 `flutter_consle.bat`，如果无解或许我们可以忽略，为它们换一个样式。

**Comment by chenglu** [comment]
SDK 归档页面的 Issue 分别在 macOS 和 Linux 下也有问题，接下来抽空再跟进一下。

**Comment by chenglu** [comment]
Done.
