### ISSUE TITLE
chrome book 配置环境出错

### ISSUE THREAD

**Issue by harwinvoid** [cfug/flutter.cn#382]
adb connect 100.115.92.2:5555
unable to connect to 100.115.92.2:5555: Connection timed out

**Comment by cfug-dev** [comment]
最近还没有时间去实测在 Chromebook 上的 Flutter 开发环境配置，可能这周末会看一下，可否先到网上搜一下解答方案，搜到之后如果是文档描述不详细，我们可以更新一下。谢谢！

**Comment by chenglu** [comment]
@Vadaski 
Hi Xinlei:
你能不能帮我把 Flutter PM 写的这篇文章翻译成中文？我给你寄去一台 Chromebook，实践完电脑就留下吧。https://proandroiddev.com/flutter-development-on-a-pixelbook-dde984a3fc1e

然后看一下这篇 issue 里提到的关于 connection timed out 的原因可能来自哪里。
文章到时候署你名发布到社区微信和文档，作为官网 Chromebook 的一个补充。

**Comment by Vadaski** [comment]
没问题～ 路哥我先翻译试试看 ；）

**Comment by chenglu** [comment]
@harwinvoid 一个小的提醒就是，这个命令似乎是连接 Chromebook 本机的 Android 虚拟机，所以需要在本机的 Android 选项里开启开发者模式，我在年初的时候曾经尝试过这个。看一下现在是否依然有效。

**Comment by chenglu** [comment]
@harwinvoid 请根据 [这篇文章](https://debug.flutter.cn/posts/flutter-development-on-a-pixelbook.html) 再试一下，看是否可以解决问题，如果不能解决问题，请再打开这个 Issue 回复，谢谢！
感谢 Xinlei 的翻译！

**Comment by harwinvoid** [comment]
@chenglu 已从dev 通道 切回 stable通道，在stable通道上没有这个问题啦

**Comment by chenglu** [comment]
好的，谢谢确认！
