### ISSUE TITLE
'给 iOS 开发者的 Flutter 指南' page issue

### ISSUE THREAD

**Issue by sugite** [cfug/flutter.cn#389]
Page URL: https://flutter-io.cn/docs/get-started/flutter-for/ios-devs.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/flutter-for/ios-devs.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

英文原文：StatelessWidgets are useful when the part of the user interface you are describing does not depend on anything other than the initial configuration information in the widget.

中文翻译：当某个 widget 不需要依赖任何别的初始配置来对这个 widget 进行描述时，StatefulWidget 会 是很有用的。

StatelessWidgets 误写作 StatefulWidget

**Comment by chenglu** [comment]
赞，收到，马上处理。

**Comment by chenglu** [comment]
文档上似乎没有错误，应该是 CDN 没有刷新，刚刷新了一下。
知乎和微信的都改好了：

https://mp.weixin.qq.com/s?__biz=MzUyMjg5NTI3NQ==&mid=2247483737&idx=1&sn=dd55f91bce2fd947a9951488ce39558b&chksm=f9c5ab9dceb2228bc0136d2e7b8155e84e87d6123d0e919e35ed013388c02752adbe67c48679&token=1758092138&lang=zh_CN#rd

https://zhuanlan.zhihu.com/p/66278625
