### ISSUE TITLE
'给 React Native 开发者的 Flutter 指南' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#396]
Page URL: https://flutter-io.cn/docs/get-started/flutter-for/react-native-devs.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/flutter-for/react-native-devs.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
![image](https://user-images.githubusercontent.com/47591151/61044324-fc3d1300-a40a-11e9-9420-73f92db8d6cd.png)

这里应该是无障碍？

**Comment by chenglu** [comment]
Fixed.
