### ISSUE TITLE
Debugging Flutter apps - 调试 Flutter 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#397]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/debugging.md

文档预览地址：https://debug.flutter.cn/docs/testing/debugging

建议完成天数：3 ~ 5 天

**Comment by dotcink** [comment]
认领翻译

**Comment by chenglu** [comment]
收到，辛苦啦！

**Comment by dotcink** [comment]
翻译完成。

备注：
1. 关于一些不确定是否需要翻译的名词（如 “Flutter inspector”，“debug 模式”），主要参考已有文档，不做翻译或部分翻译；
2. 外链的文档名称没有翻译（比如 “The Layer Cake”）；

**Comment by chenglu** [comment]
优秀！

**Comment by chenglu** [comment]
谢谢时间，本任务已经完成并发布！
