### ISSUE TITLE
No.144 - Debugging Flutter apps programmatically - 添加输出代码的方式调试 Flutter 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#398]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/code-debugging.md

文档预览地址：https://debug.flutter.cn/docs/testing/code-debugging

建议完成天数：10 ~ 14 天

**Comment by yuxizhe** [comment]
翻译认领 😄

**Comment by chenglu** [comment]
认领成功，辛苦你的时间啦～ 这可是个不小的工程 ^_^

**Comment by chenglu** [comment]
@yuxizhe 进度怎么样啦？

**Comment by yuxizhe** [comment]
@chenglu   不好意思，最近做了个手术。我这几天翻译下

**Comment by chenglu** [comment]
@yuxizhe 感谢回复，身体最重要哈，注意多休息～ 这个不着急。

**Comment by AlexV525** [comment]
Ping @yuxizhe

**Comment by AlexV525** [comment]
超时释放。

**Comment by toly1994328** [comment]
翻译认领 时间 12 天
