### ISSUE TITLE
Install and run DevTools from Android Studio - 在 Android Studio 上安装和运行开发者工具

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#399]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/android-studio.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/android-studio

建议完成天数：1 ~ 2 天

**Comment by Huanxiongjun** [comment]
认领

**Comment by chenglu** [comment]
👍 cc @hayley1643

**Comment by chenglu** [comment]
谢谢付出时间，本任务已经成功完成和发布！
