### ISSUE TITLE
Install and run DevTools from the command line - 通过命令行安装和运行开发者工具

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#400]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/cli.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/cli

建议完成天数：1 ~ 2 天

**Comment by yuxizhe** [comment]
I'm happy to pick this up.

**Comment by chenglu** [comment]
cool，感谢你的时间，cc @hayley1643 登记一下任务哈。

**Comment by chenglu** [comment]
@yuxizhe 任务进度如何啦？
