### ISSUE TITLE
No.152 - Using the Flutter inspector - 使用 Flutter inspector 工具

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#402]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/inspector.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/inspector

建议完成天数：5 ~ 7 天

**Comment by Nayuta403** [comment]
认领翻译 @chenglu
