### ISSUE TITLE
Using the Logging view - 使用日志视图 (Logging view)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#403]
(有更新) Markdown 文档：https://github.com/chenglu/flutter.cn/blob/master/src/docs/development/tools/devtools/logging.md

本任务请 fork https://github.com/chenglu/flutter.cn 并给这个 repo 提交 PR，谢谢～

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/logging

建议完成天数：1 ~ 2 天

**Comment by dotcink** [comment]
认领翻译。

DL: 0922 22:00

**Comment by dotcink** [comment]
翻译完成。

**Comment by chenglu** [comment]
感谢付出时间，本任务已经完成。
