### ISSUE TITLE
No.153 - Using the Memory view - 使用内存视图 (Memory view)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#404]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/memory.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/memory

建议完成天数：5 ~ 7 天

**Comment by cfug-dev** [comment]
assigned to: @talisk

**Comment by AlexV525** [comment]
Ping @talisk

**Comment by chenglu** [comment]
@talisk 恺哥有点事情这个任务不能参加了，重新加入未翻译给其他人吧～ FYI  @AlexV525

**Comment by Nayuta403** [comment]
领了，看起来文章内容比较长，预计需要两周左右完成翻译

**Comment by Nayuta403** [comment]
翻译中，最近事儿比较多，进度稍慢
