### ISSUE TITLE
No.126 - Using the Timeline view - 使用时间线视图 (Timeline view)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#406]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/timeline.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/timeline

建议完成天数：5 ~ 7 天

**Comment by DaoxingHuang** [comment]
@chenglu will translate it in 5-10 days .

**Comment by chenglu** [comment]
收到，辛苦啦。

**Comment by DaoxingHuang** [comment]
Sorry for delaying, work on it now.

**Comment by DaoxingHuang** [comment]
had been done [PR](https://github.com/cfug/flutter.cn/pull/523)

**Comment by cfug-dev** [comment]
Thanks for your great effort on this, this doc has been published, the issue should be closed now.
