### ISSUE TITLE
Install and run DevTools from VS Code - 在 VS Code 里安装和使用开发者工具

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#407]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/vscode.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/vscode

建议完成天数：1 ~ 2 天

**Comment by scvoet** [comment]
翻译范围：全部内容
预计时间：现已完成

**Comment by chenglu** [comment]
Merged.
