### ISSUE TITLE
No.143 - AndroidX Migration - 迁移到 AndroidX

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#408]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/androidx-migration.md

文档预览地址：https://debug.flutter.cn/docs/development/androidx-migration

建议完成天数：3 ~ 5 天

**Comment by chenglu** [comment]
Note: 原始任务文档已经被替换，因此本任务做了修改。
cc/ @Vadaski, FYI.

**Comment by qingmei2** [comment]
认领。

预计完成时间： 2019/12/29

**Comment by yunzhejude** [comment]
> 认领。
> 
> 预计完成时间：2天（2019/12/29）

认领已收到~谢谢你 \≥ω≤/
