### ISSUE TITLE
Animate a page route transition - 为页面切换加入动画效果

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#409]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/animation/page-route-animation.md

文档预览地址：https://debug.flutter.cn/docs/cookbook/animation/page-route-animation.html

建议完成天数：5 ~ 7 天

**Comment by chenglu** [comment]
谢谢鑫磊。
