### ISSUE TITLE
Using the Performance view - 使用性能视图 (Performance view)

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#415]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/performance.md

文档预览地址：https://debug.flutter.cn/docs/development/tools/devtools/performance

建议完成天数：3 ~ 5 天

**Comment by chenglu** [comment]
谢谢你的时间！任务认领已确认。

**Comment by DaoxingHuang** [comment]
@chenglu I had finished this last week ,but there is issue about table format.Also I checked the vs-code's table ,still exists problem, you could check[ it](https://flutter.cn/docs/development/tools/vs-code) .@Vadaski has created a issue for [this](https://github.com/cfug/flutter.cn/issues/504),feel free take a look.

**Comment by chenglu** [comment]
好，我现在看一下。

**Comment by chenglu** [comment]
@DaoxingHuang 我已经大致排查过问题了，本文档有两处 Markdown 内嵌 HTML，并有部分 HTML 标签未作闭合处理，请用我下面的内容替换文档里的两处内嵌 HTML，我也将中英文对照显示的内容写好了，可能要麻烦对照填写一下：

```<dl markdown="1">
<dt markdown="1"><t><b>Total time</b><t><t>中文翻译内容</t></dt>
<dd><p>Time the method spent executing its own code as well as
    the code for its callees.</p>

<p>中文翻译内容</p></dd>
<dt markdown="1"><t><b>Self time</b><t><t>中文翻译内容</t></dt>
<dd><t>Time the method spent executing only its own code.</t><t>中文翻译内容</t></dd>
<dt markdown="1"><t><b>Method</b><t><t>中文翻译内容</t></dt>
<dd><t>Name of the called method.</t><t>中文翻译内容</t></dd>
<dt markdown="1"><t><b>Source</b><t><t>中文翻译内容</t></dt>
<dd><t>File path for the method call site.</t><t>中文翻译内容</t></dd>
</dl>```

**Comment by chenglu** [comment]
第二处是：

```<dl markdown="1">
<dt markdown="1"><t><b>Total time</b><t><t>中文翻译内容</t></dt>
<dd markdown="1"><p>Time the method spent executing its own code
    as well as the code for its callee.</p>

<p>中文翻译内容</p>
</dd>

<dt markdown="1"><t><b>Self time</b><t><t>中文翻译内容</t></dt>
<dd markdown="1"><p>For top-level methods in the bottom-up tree
    (leaf stack frames in the profile), this is the time the
    method spent executing only its own code. For sub nodes
    (the callers in the CPU profile), this is the self time
    of the callee when being called by the caller.
    In the following example, the self time of the caller
    `Element.updateSlotForChild.visit()` is equal to the self time of
    the callee `[Stub] OneArgCheckInLineCache` when being called by
    the caller.</p>

<p>中文翻译内容（可以换行）</p>

</dd>

<dt markdown="1"><t><b>Method</b><t><t>中文翻译内容</t></dt>
<dd markdown="1"><t>Name of the called method.</t><t>中文翻译内容</t></dd>

<dt markdown="1"><t><b>Source</b><t><t>中文翻译内容</t></dt>
<dd markdown="1"><t>File path for the method call site.</t><t>中文翻译内容</t></dd>
</dl>
```

**Comment by chenglu** [comment]
cc/ @Vadaski, @asnowwolf.

**Comment by Vadaski** [comment]
Cool ! Already fix this issue at #505

**Comment by DaoxingHuang** [comment]
@chenglu thanks so much.

**Comment by DaoxingHuang** [comment]
@chenglu Please feel free to take a look code as below:
`<dl markdown="1">
<dt markdown="1"><p>**Toggle Baseline Painting**</p><p>**切换 Baseline 绘制** ![Baseline painting icon]({% asset tools/devtools/paint-baselines-icon.png @path %}){:width="20px"}</p></dt>
<dd><p>Causes each RenderBox to paint a line at each of its baselines.</p><p>每个 RenderBox 在底部绘制一条线。</p></dd>
<dt markdown="1"><p>**Toggle Repaint Rainbow**</p><p>**切换重绘 Rainbow** ![Repaint rainbow icon]({% asset tools/devtools/repaint-rainbow-icon.png @path %}){:width="20px"}</p></dt>
<dd><p>Shows rotating colors on layers when repainting.</p><p>重新绘制时在图层上改变颜色。</p></dd>
<dt markdown="1"><p>**Toggle Slow Animations**</p><p>**切换慢模式横幅** ![Slow animations icon]({% asset tools/devtools/slow-animations-icon.png @path %}){:width="20px"}</p></dt>
<dd><p>Slows down animations to enable visual inspection.</p> <p>减慢动画以启用视觉检查。</p></dd>
<dt markdown="1"><p>**Toggle Debug Mode Banner**</p> <p>**切换 debug 模式横幅显示** ![Debug mode banner icon]({% asset tools/devtools/debug-mode-banner-icon.png @path %}){:width="20px"}</p></dt>
<dd><p>Hides the debug mode banner even when running a debug build.</p><p>在运行调试构建时隐藏 debug 模式的横幅 (banner)。</p></dd>
</dl>`,it is from the [vs-code.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/vs-code.md), 
it seems the same as yours.but when you view[ the doc](https://flutter.cn/docs/development/tools/vs-code) online ,it is alos wrong.
but anyway ,I will done it as your suggestions.

**Comment by chenglu** [comment]
Why not just fill the Chinese text on my previous tips?

**Comment by chenglu** [comment]
We should avoid using **, please replace them to the `<b>`

**Comment by DaoxingHuang** [comment]
yes, I done it .but also want to know why. it will help me at next time.
Thanks @chenglu

**Comment by DaoxingHuang** [comment]
> We should avoid using **, please replace them to the `<b>`

got it .thanks so much.

**Comment by chenglu** [comment]
Hey Jams: 
Please see my comments here: https://github.com/cfug/flutter.cn/pull/505#pullrequestreview-309007680, since we have two different build system, one from the Flutter team, another is the English-Chinese toggle build plugin, it may have some unknown conflict if we use markdown tags in an HTML section while the build system parsing and rendering the .md file, in our case, I found if we use all the HTML tags in the HTML section, we won't have that problem, so we might follow the additional guide below:
* Avoid using any markdown tags in the HTML section in a .md file.
* Replace the markdown tags to the HTML tags if needed.

And also, we have the [guide docs](https://github.com/cfug/flutter.cn/wiki/Translation-Spec) on the translation spec in the wiki tab. 

Thanks!

**Comment by DaoxingHuang** [comment]
OK，thanks，will handle this later.

**Comment by chenglu** [comment]
本任务已经完成，Issue 关闭。
