### ISSUE TITLE
'在 macOS 上安装和配置 Flutter 开发环境' page issue

### ISSUE THREAD

**Issue by pillar69** [cfug/flutter.cn#419]
Page URL: https://flutter-io.cn/docs/get-started/install/macos.html
Page source: https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Repeated sentences
<img width="886" alt="Screen Shot 2019-07-27 at 11 06 35 AM" src="https://user-images.githubusercontent.com/12994159/61989261-055eee80-b05f-11e9-89f4-f8c605ed447a.png">

**Comment by chenglu** [comment]
谢谢提出这个问题和 PR 帮助我们解决！
