### ISSUE TITLE
JSON 文档的问题

### ISSUE THREAD

**Issue by t496971418** [cfug/flutter.cn#425]
在文档中执行`flutter pub run build_runner build`无法生效会报错
经过资料查询发现`flutter packages pub run build_runner build`可正确执行命令。
是因为配置问题还是版本问题导致加了`package`命令以后才能生效？
[链接](https://flutter-io.cn/docs/development/data-and-backend/json)

**Comment by chenglu** [comment]
谢谢提出，应该是原始文档的问题，在等原始文档的修正。

**Comment by t496971418** [comment]
> 谢谢提出，应该是原始文档的问题，在等原始文档的修正。

好的，耐心等待中。thx🤣

**Comment by Realank** [comment]
最近 https://github.com/flutter/flutter/issues/33302 修改了flutter packages pub ... 和 flutter pub ... 命令之间的问题
您遇到的问题在于，文档对应的最新的Flutter sdk版本，而您本地的Flutter sdk没有更新

请更新最新版本的Flutter sdk，然后执行flutter pub run build_runner build应该就不会报错了。

我的Flutter sdk版本：

RealankdeiMac:~ realank$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.3-pre.58, on Mac OS X 10.14.6 18G84, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)

**Comment by Vadaski** [comment]
Hi,Terry
我们在今天下午复现了你的 issue 后，我们尝试了几种解决方案
1.我的sdk为v1.5.4-hotfix.2，猜测是否是未升级到最新版本的缘故，故升级到 v1.7.8+hotfix.4，未解决。
2.我将 依赖版本 any 替换为 实际版本，命令生效，问题解决。
然后我们再次尝试复现该问题时，无论是降 flutter sdk 版本，还是依赖版本改为 any / 老版本 / 最新版本，都无法复现该问题了。

你那边现在这个问题是否还存在呢？方便加一个 qq 交流一下吗 1652219550
@t496971418

**Comment by Vadaski** [comment]
我的原因已找到 front_end 0.1.4 版本会导致构建出错，可以强制指定 0.1.9 版本避免此错误，pub错误还在复查中

**Comment by Realank** [comment]
@t496971418 还请贴出您的报错log，以便看到更多细节

**Comment by t496971418** [comment]
Flutter 版本：
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.37.1)
```
昨天做了一次更新后，发现今天再次执行`flutter pub run build_runner build`和`flutter packages pub run build_runner build`。
上诉问题都没有复现。初步认为是因为版本问题导致的。 
@Vadaski
@Realank

**Comment by chenglu** [comment]
谢谢大家的时间和探讨，我发了一个 PR https://github.com/flutter/website/pull/2918#issuecomment-524601975 到 Flutter 相关的文档咨询了 Flutter 团队的同学，也得到了很好的回复，相信这个问题已经被很好的解决了，如果有其他问题请再次提出，谢谢大家！
