### ISSUE TITLE
'为你的 Flutter 应用加入交互体验' page issue

### ISSUE THREAD

**Issue by OIngSaaa** [cfug/flutter.cn#434]
Page URL: https://flutter-io.cn/docs/development/ui/interactive/
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/interactive/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
</span></a>重点是什么？</b>
该行的样式未应用成功，建议修改

**Comment by OIngSaaa** [comment]
not

**Comment by OIngSaaa** [comment]
状态管理

</span></a>重点是什么？</b>

**Comment by OIngSaaa** [comment]
状态管理

"</span></a>重点是什么？</b>"

**Comment by OIngSaaa** [comment]
<*/span></a>重点是什么？</b*>

**Comment by chenglu** [comment]
收到，你访问到的这个页面是一个过期未删除的页面，后续会做删除处理，以及查看是否其他文档里有这个链接的引用。

请通过下面的链接访问最新文档：https://flutter-io.cn/docs/development/ui/interactive
其对应的 md 文件在: https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/interactive.md
再次感谢提出问题。

**Comment by chenglu** [comment]
目前尚未发现其他页面的文档引用，如果发现了请告诉我们，谢谢！
@OIngSaaa
