### ISSUE TITLE
Basic Flutter layout concepts - Codelab: Flutter 布局基础教程

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#436]
(有更新)
Markdown 文档：https://github.com/chenglu/flutter.cn/blob/master/src/docs/codelabs/layout-basics.md

请 fork https://github.com/chenglu/flutter.cn 并给这个 repo 提交 PR，谢谢！

文档预览地址：https://debug.flutter.cn/docs/codelabs/layout-basics

**Comment by Vadaski** [comment]
认领翻译

**Comment by hayley1643** [comment]
感谢@Vadaski  辛苦啦 翻译已成功认领和登记
翻译格式请参考[中文文案排版指南](url)和[文档翻译格式](url)
期待你的翻译

**Comment by chenglu** [comment]
@Vadaski 任务有部分更新，请查阅。

**Comment by chenglu** [comment]
谢谢鑫磊，你是大功臣！
