### ISSUE TITLE
'了解更多' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#455]
Page URL: https://flutter-io.cn/docs/get-started/learn-more.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/learn-more.md

Description of issue:

页脚中英换行的问题，需要加入一个换行。

![331567860982_ pic](https://user-images.githubusercontent.com/47591151/64475200-0f255700-d1b2-11e9-949e-d244657bef24.jpg)

**Comment by chenglu** [comment]
will be fixed at next PR.
