### ISSUE TITLE
'在 Web 平台使用 Flutter' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#468]
Page URL: https://flutter-io.cn/web.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/web.md

链接引用错误。

Description of issue:
![image](https://user-images.githubusercontent.com/47591151/65017773-17238a80-d95a-11e9-96ea-9bc4098e5313.png)

**Comment by chenglu** [comment]
Done.
