### ISSUE TITLE
'Flutter 开发文档' page issue

### ISSUE THREAD

**Issue by godot0413301** [cfug/flutter.cn#475]
Page URL: https://flutter-io.cn/docs/
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
有两个：网站更新。删掉一个

**Comment by chenglu** [comment]
收到。

**Comment by chenglu** [comment]
问题已经修复，请强制刷新浏览器之后应该就好啦，有任何问题再开启这个 Issue 跟进，谢谢！
