### ISSUE TITLE
'Flutter 开发文档' page issue

### ISSUE THREAD

**Issue by godot0413301** [cfug/flutter.cn#477]
Page URL: https://flutter.cn/docs/
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
下面视频都是重复的，你看一下就明白了

**Comment by chenglu** [comment]
收到，谢谢细心发现这个问题，
已经在最新的一次提交里试着修复。

**Comment by chenglu** [comment]
本页面仍有一处细节错误——「视频」的标题栏，多了一个英文，已经在最近一次的 PR #480 里修复。

**Comment by chenglu** [comment]
Fixed，如果有其他问题欢迎重新开启本 Issue。
