### ISSUE TITLE
C and C++ interop 翻译

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#481]
```interop``` 的翻译我不特别拿捏准，其英文原意是 互调性/互操作。

但是这里放这里我不太清楚使用 dart:ffi 是否可以实现「互调」，据我的了解它可能只是方便通过这个接口调用 C/C++ 代码。
不知道是否有有过相关经验的同学解毒一下。

目前暂时先翻译成<s>「与 C 和 C++ 互调」</s>：调用 C 和 C++，同时 [dart.cn](https://dart.cn/server/c-interop) 上也有这一篇。

谢谢！

**Comment by chenglu** [comment]
@Vadaski @Realank 叫一些小哥哥们看是否有更深入的见解和提议。

Thanks!

**Comment by Vadaski** [comment]
好～

**Comment by Vadaski** [comment]
向闲鱼的工程师请教了这个问题，目前应该是只能 dart 调用 c/c++ 的代码，目前的 ffi 还不稳定，后续可能会实现互相调用。建议现在先翻译为「调用 C 和 C++」

**Comment by chenglu** [comment]
看到了，做的很棒，这个精神值得发扬！
提一个 Issue 吧

XinLei <notifications@github.com>于2019年10月13日 周日22:24写道：

**Comment by chenglu** [comment]
我们就统一翻译成「调用 C 和 C++」吧，Issue closed.
