### ISSUE TITLE
中文排版指南标题错误

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#482]
src: https://github.com/cfug/flutter.cn/wiki/Chinese-Typography-Guide#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E6%97%A0%E9%9C%80%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC

标题： 数字与单位之间无需增加空格
实际需要增加空格，与样例不一致

**Comment by chenglu** [comment]
Good catch!
已经改过来了。
