### ISSUE TITLE
如何获取计算机中文件的绝对路径呢？

### ISSUE THREAD

**Issue by LISONG040576** [cfug/flutter.cn#489]
我想上传一个文件到服务器，目前用到的方法是：
FormData formData = FormData.fromMap({
    "name": "wendux",
    "age": 25,
    "file": await MultipartFile.fromFile(filePath)
  });

这里面需要填入文件的路径，目前我已经能够获取到文件对象，通过以下方法：
final completer = new Completer<String>();
    final html.InputElement input = html.document.createElement('input');
    input..type = 'file'
        // ..accept = 'image/*'
        ;
    input.onChange.listen((e) async {
      final List<html.File> files = input.files;
      final reader = new html.FileReader();
      reader.readAsDataUrl(files[0]);
      reader.onError.listen((error) => completer.completeError(error));
      await reader.onLoad.first;
      completer.complete((reader.result as String) + "," + files[0].name);

      html.File firstFile = files.first;
      print('baseUri ---------- ${input.baseUri}');
      print('name ---------- ${firstFile.name}');
      print('path ---------- ${firstFile.relativePath}');
      print('type ---------- ${firstFile.type}');
    });

但是无法获取到这个文件的绝对路径，这个firstFile.relativePath也是空的，查了好久也没有找到解决方法，请问哪位可以帮助解答一下？？？

**Comment by chenglu** [comment]
本项目的 issue 区可能仅限于快速处理关于文档勘误的问题，具体技术细节问题可能在 sifou.com/flutter 或者 stackoverflow 上能更快的得到解决。

**Comment by chenglu** [comment]
@Vadaski 鑫磊来帮忙看看？

**Comment by Vadaski** [comment]
Hi LISONG:
这里是我之前上传图片文件的方法
``` dart
Future<String> uploadImage(File image, String info) async {
  String path = image.path;
  var name = path.substring(path.lastIndexOf("/") + 1, path.length);
  var suffix = name.substring(name.lastIndexOf(".") + 1, name.length);
  FormData formData = new FormData.from({
    "upfile": new UploadFileInfo(new File(path), name,
        contentType: ContentType.parse("image/$suffix"))
  });
  var response = await baseposturl(servicepath['uploadImage'], info, formData);
  print('上传成功，image response data 为：${response.runtimeType}}');
  final res = json.decode(response);
  if (res['code'] == 1) {
    return res['data'];
  }
  return null;
}
```

我这里是 dart:io 中的 File，可以直接通过 path 拿到路径。
你这里的 html.File 是哪个包的呢

**Comment by chenglu** [comment]
因为没有收到回复，我暂时关闭这个 Issue，有任何新的问题再提出，谢谢！
@LISONG040576
