### ISSUE TITLE
'Web 常见问题' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#499]
Page URL: https://flutter.cn/docs/development/platform-integration/web.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/platform-integration/web.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
这个页面有部分 link 失效，而且，是否可以将这个页面的标题降一级？
目前的页面看着有点乱，尤其是标题非常大而实际内容并不多。

**Comment by chenglu** [comment]
Fixed, thanks to @Vadaski .
