### ISSUE TITLE
'Widgets 介绍' page issue

### ISSUE THREAD

**Issue by dingbo8128** [cfug/flutter.cn#502]
Page URL: https://flutter.cn/docs/development/ui/widgets-intro.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/widgets-intro.md

原文：
when the MaterialApp widget is used, this is taken care of for you, as demonstrated later.
翻译：
当使用 MaterialApp widget 时，你需要考虑这一点，之后我们会进一步的描述。
正确翻译：
当使用 MaterialApp widget 时，你就无需考虑这一点，之后我们会进一步的描述。
解释：
因为使用 MaterialApp widget时就无需显示指定textDirection这个参数。

**Comment by Vadaski** [comment]
hi @dingbo8128 
此处确实存在译误，感谢你的反馈！

**Comment by chenglu** [comment]
👍

**Comment by chenglu** [comment]
Cool，文档已经更新，本 Issue 关闭，如果有任何问题请再次打开和跟进。
