### ISSUE TITLE
'在 VS Code 里开发 Flutter 应用' page issue

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#504]
Page URL: https://flutter.cn/docs/development/tools/vs-code.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/vs-code.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
表单格式有问题，\<p> 没有效果，需要重新处理

**Comment by chenglu** [comment]
好，回头我也再看一下。

**Comment by chenglu** [comment]
Markdown 内的 HTML 标签里继续包含 Markdown 标签，导致这个问题。

其他的翻译应该都可以通过 
`<t>Original English content</t><t>翻译之后的中文</t> `
这个格式来处理。

**Comment by chenglu** [comment]
我已经处理过这个啦，预览站也更新了，看起来已经没问题了。
https://debug.flutter.cn/docs/development/tools/vs-code

仍有几处比如英文名没有翻译，以及这句话重复了
> Keyboard mappings can be changed by executing the Open Keyboard Shortcuts command from the Command Palette.

鑫磊抽空可以处理一下这些问题。

**Comment by Vadaski** [comment]
好的

**Comment by chenglu** [comment]
本 Issue 提及的所有问题均已修复，如有任何问题再打开本 Issue 跟进。
谢谢各位！
