### ISSUE TITLE
Writing platform-specific code - 撰写双端平台代码 (插件编写实现) 

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#506]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/platform-integration/platform-channels.md

英文文档预览：https://debug.flutter.cn/docs/development/platform-integration/platform-channels

文章有新增部分，故开启此 issue

**Comment by Nayuta403** [comment]
这篇文章看起来已经翻译完了,新增的部分是指？
