### ISSUE TITLE
Official Posts 发布计划

### ISSUE THREAD

**Issue by godot0413301** [cfug/flutter.cn#530]
Page URL: https://flutter.cn/docs/
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
这个flutter的web支持变为beta这个a连接，在国内无法跳转
![E153DBF4-BD59-4BA6-B714-AB7DF496E6D2](https://user-images.githubusercontent.com/44113641/70757597-23618d00-1d7b-11ea-907a-fe59f78c308c.png)

**Comment by cfug-dev** [comment]
收到，谢谢提醒，这些官方的文档正在等待 Google 的翻译，翻译之后我们会找志愿者合并到网站中来。

**Comment by chenglu** [comment]
@Vadaski 
- https://mp.weixin.qq.com/s/OAQ1eUX7QPdNpOOy_R3sfw
- https://mp.weixin.qq.com/s/ItRWmXPKt81tKLLTWoJqEQ
- https://mp.weixin.qq.com/s/sETtUi-J4cxCCbKP_FQkpA
- https://mp.weixin.qq.com/s/LyAtbiYYM6PEbxLoLD7OYA
- https://mp.weixin.qq.com/s/aWLdZC6EWqokEFlQONHyAg

**Comment by chenglu** [comment]
- https://mp.weixin.qq.com/s/OAQ1eUX7QPdNpOOy_R3sfw
- https://mp.weixin.qq.com/s/DR999l2PZsQKbrrzXIZ0zA
- https://mp.weixin.qq.com/s/WkB3phcCD2vA_SrA9T8cVA
- https://mp.weixin.qq.com/s/NGqF2OTvsV1A2KLiMXE2PQ
- https://mp.weixin.qq.com/s/VXNbqxpoVDJeOPkBt5_88A
- https://mp.weixin.qq.com/s/-kknoeIq0hJfIHTB190ppQ
- https://mp.weixin.qq.com/s/fSbprLMhBy3RqSY4NCZhWA
- https://mp.weixin.qq.com/s/CqX_dB0g-rIdk7eyE0tQlw -- 已发布
- https://mp.weixin.qq.com/s/DS8lAkqtK_Qp37o8ISlthA --已发布

以及这些文章，需要抽空同步到 flutter.cn/posts 下面
