### ISSUE TITLE
No.137 - Integrate a Flutter module into your Android project - 将 Flutter 集成到现有应用

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#534]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/index.md
Page URL: https://flutter.cn/docs/development/add-to-app

建议完成天数：3 ~ 5 天

**Comment by talisk** [comment]
@chenglu I will finish the translation in 3-5 days.

**Comment by Vadaski** [comment]
确认认领～

**Comment by chenglu** [comment]
谢谢，本任务已经完成，Issue 忘记关闭，现在关闭 ;-)
