### ISSUE TITLE
No.136-Integrate a Flutter module into your Android project-将 Flutter module 集成到 Android 项目

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#535]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/android/project-setup.md

文档预览地址：https://flutter.cn/docs/development/add-to-app/android/project-setup.html

建议完成天数：5 ~ 7 天

**Comment by MeandNi** [comment]
认领翻译
