### ISSUE TITLE
No.139 - Integrate a Flutter module into your iOS project - 将 Flutter module 集成到 iOS 项目

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#536]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/ios/project-setup.md

文档预览地址：https://flutter.cn/docs/development/add-to-app/ios/project-setup.html

建议完成天数：5 ~ 7 天

**Comment by Realank** [comment]
认领

**Comment by Realank** [comment]
翻译已合并
