### ISSUE TITLE
No.133-Add a normal Flutter screen-向 Android 应用中添加 Flutter 页面

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#537]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/android/add-flutter-screen.md

文档预览地址：https://flutter.cn/docs/development/add-to-app/android/add-flutter-screen.html

建议完成天数：5 ~ 7 天

**Comment by teabyii** [comment]
认领，预计 11.08 完成
