### ISSUE TITLE
No.151 - Running, debugging, and hot reload - 运行，调试以及热重载

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#539]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/debugging.md

文档预览地址：https://flutter.cn/docs/development/add-to-app/debugging.html

建议完成天数：3 ~ 5 天

**Comment by DaoxingHuang** [comment]
@chenglu 这个我来，不过有时候因个人工作问题，可能部分处理会延时，请见谅。

**Comment by Vadaski** [comment]
赞道星！

**Comment by chenglu** [comment]
any updates? @DaoxingHuang

**Comment by DaoxingHuang** [comment]
抱歉，马上处理

**Comment by DaoxingHuang** [comment]
@chenglu Sorry, it will be done in next week.

**Comment by AlexV525** [comment]
Ping @DaoxingHuang

**Comment by AlexV525** [comment]
超时释放。

**Comment by Nayuta403** [comment]
认领了，我尽量把第三阶段的文章多翻译点
