### ISSUE TITLE
No.150 - Load sequence, performance, and memory - 控制加载顺序，优化性能与内存

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#540]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/performance.md

文档预览地址：https://flutter.cn/docs/development/add-to-app/performance.html

建议完成天数：5 ~ 7 天

**Comment by talisk** [comment]
@chenglu I will finish the translation in 5-7 days.

**Comment by Vadaski** [comment]
确认认领，辛苦啦！
