### ISSUE TITLE
文档链接指向错误

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#544]
https://flutter.cn/docs/development/packages-and-plugins/androidx-compatibility 

https://flutter.cn/docs/development/tools/sdk/archive

这两个文档所对应的 Markdown 链接在 GitHub repo 里是 404，是否是文档指向了新的地方？

Thanks to @yunzhejude

**Comment by chenglu** [comment]
第一个 AndroidX 的文档应该是移动了位置，我发现导航栏内容也有问题，这个链接被暴露出来，导航栏的问题也需要修复。

**Comment by chenglu** [comment]
done
