### ISSUE TITLE
'Flutter 1.9 正式发布' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#545]
Page URL: https://flutter.cn/posts/flutter-news-from-gdd-china-flutter1.9.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/posts/flutter-news-from-gdd-china-flutter1.9.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Bitcode 实验性支持 链接错误，应该是
https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app

cc/ @Vadaski

**Comment by chenglu** [comment]
👍
