### ISSUE TITLE
'Flutter SDK 版本列表' page issue

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#546]
Page URL: https://flutter.cn/docs/development/tools/sdk/releases.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/sdk/releases.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
[Flutter’s channels][] 链接丢失。
应该指向 https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by Vadaski** [comment]
这里发现是引用时的 [Flutter’s channels] ‘ 符号不一致导致的，fixed！

**Comment by chenglu** [comment]
👍
