### ISSUE TITLE
'测量你的应用体积' page issue

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#562]
Page URL: https://flutter.cn/docs/perf/app-size.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/perf/app-size.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
性能优化这部分的左边侧边栏似乎没有跟着文档页面进行加粗表示，不知道为什么。

<img width="1393" alt="Screen Shot 2019-12-24 at 4 13 21 PM" src="https://user-images.githubusercontent.com/2258420/71402635-64ee1400-2668-11ea-8d22-9a102270d944.png">

**Comment by Vadaski** [comment]
这里是渲染性能部分缩紧错误导致的，我看了下，原 site 也存在这个问题。

**Comment by chenglu** [comment]
@Vadaski 
看看我这个 commit 是否可以解决这个 bug: https://github.com/cfug/flutter.cn/commit/3ce339148595a1052b55dc5f06ab1de3c879e603

**Comment by chenglu** [comment]
无法解决，等官方方案吧。
