### ISSUE TITLE
侧边栏问题

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#570]
- [x] https://github.com/cfug/flutter.cn/issues/567
- [x] https://github.com/cfug/flutter.cn/issues/557
- [x] https://github.com/cfug/flutter.cn/issues/569
- [x] 以及 Google 文字库 链接应指向 pub.flutter-io.cn
- [x] https://github.com/cfug/flutter.cn/issues/562
- [x]  重新比对英文文档和中文文档的侧边栏内容，看是否需要增补： https://gist.github.com/chenglu/e2af81a21cc2930072378b701f69bbbe/revisions

**Comment by chenglu** [comment]
感谢 @Vadaski，list 最后面两个仍需要再看一下。

**Comment by Vadaski** [comment]
对比了我们和原 site，侧边栏是一致的

**Comment by chenglu** [comment]
#562 问题依旧存在，等官方解决吧，Issues closed.
