### ISSUE TITLE
No.134 - Add a FlutterFragment to an Activity with a new FlutterEngine - 向 Android 应用中添加 Flutter Fragment

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#576]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/add-to-app/android/add-flutter-fragment.md

文档预览地址：https://debug.flutter.cn/docs/development/add-to-app/android/add-flutter-fragment

预计完成时间：5 - 7天

**Comment by howshea** [comment]
认领，预计5天完成
