### ISSUE TITLE
No.135 - Android launch screen - 向 Android 应用中添加闪屏页和启动页

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#577]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/add-to-app/android/add-flutter-fragment.md

文档预览地址：https://debug.flutter.cn//docs/development/add-to-app/android/add-splash-screen

建议完成时间 ：3 - 5 天

**Comment by qingmei2** [comment]
认领。

预计完成时间：3天（ 2020/01/12 ）

**Comment by yunzhejude** [comment]
认领成功~辛苦啦(๑′௰‵๑)

**Comment by AlexV525** [comment]
404？出了啥意外？ 🤣

**Comment by chenglu** [comment]
> 404？出了啥意外？ 🤣 

看一下官网 flutter.dev 指向的这个文档地址还在否？

**Comment by AlexV525** [comment]
新地址： https://flutter.dev/docs/development/ui/advanced/splash-screen#android-launch-screen

**Comment by chenglu** [comment]
https://flutter.cn/docs/development/ui/advanced/splash-screen#android-launch-screen

这个应该是之前文档移动，中文已经翻译完了

**Comment by AlexV525** [comment]
那么我就关闭了，因为时间也比较久了
