### ISSUE TITLE
No.141 - Supporting the new Android plugins APIs - 支持新的 Android 的 API

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#578]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/plugin-api-migration.md

文档预览地址：https://debug.flutter.cn/docs/development/packages-and-plugins/plugin-api-migration

建议完成时间：5 - 7 天

**Comment by AlexV525** [comment]
认领。😉

**Comment by AlexV525** [comment]
Reopen since there are some display issues in the debug preview.
