### ISSUE TITLE
No.142 - Flutter Favorite program - Flutter Favorite 项目

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#579]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/favorites.md

文档预览地址：https://debug.flutter.cn/docs/development/packages-and-plugins/favorites

建议完成时间：3 - 5 天

**Comment by scvoet** [comment]
认领&预计于 5 月 11 日完成。
