### ISSUE TITLE
No.145 - Performance - 性能估计

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#580]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/perf/index.md

文档预览地址：https://debug.flutter.cn/docs/perf/

建议完成时间：1 - 3 天

**Comment by Nayuta-D** [comment]
申请认领 @Vadaski

**Comment by Vadaski** [comment]
已确认，祝你好运！

**Comment by chenglu** [comment]
厉害！

**Comment by Nayuta-D** [comment]
第一次提交，如有问题，欢迎各位指出

**Comment by chenglu** [comment]
厉害！

**Comment by AlexV525** [comment]
还没 PR 过来呢
