### ISSUE TITLE
No.147 - Improving rendering performance - 提高渲染性能

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#582]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/perf/rendering/index.md

文档预览地址：https://debug.flutter.cn/docs/perf/rendering/

建议完成时间：1 - 3 天

**Comment by MeandNi** [comment]
认领翻译

**Comment by chenglu** [comment]
感谢你的时间参与翻译，可访问我们的 [wiki 页面](https://github.com/cfug/flutter.cn/wiki) 了解具体的翻译要求和格式。
任务完成之后请直接发送 PR 给我们，相关格式等内容也可以在 [这个文档](https://github.com/cfug/flutter.cn/wiki/Translation-Workflow-with-GitHub) 里查看。

再次感谢你的时间！
