### ISSUE TITLE
No.148 - Flutter compatibility policy - Flutter 兼容性策略

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#583]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/compatibility.md

文档预览地址：https://debug.flutter.cn/docs/resources/compatibility

建议完成时间：1 - 3 天

**Comment by NeroSong** [comment]
申请认领该任务。
预计完成时间：2 天。

**Comment by yunzhejude** [comment]
@NeroSong 感谢认领，辛苦啦～

**Comment by chenglu** [comment]
谢谢花费时间帮忙翻译，任务已完成。
