### ISSUE TITLE
No.155 - Handling errors in Flutter - 处理错误

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#585]
Markdown 文档：https://github.com/cfug/flutter.cn/tree/master/src/docs/testing/errors.md

文档预览地址：https://debug.flutter.cn/docs/testing/errors

建议完成时间：1 - 3 天

**Comment by xudqiang93** [comment]
翻译认领，预计5月11号完成

**Comment by Vadaski** [comment]
认领已确认，祝顺利

**Comment by scvoet** [comment]
这个 issue 早就被完成了，因为 PR 格式有问题所以没被自动关闭。
