### ISSUE TITLE
No.160 - Flutter crash reporting - Flutter 崩溃报告

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#592]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/reference/crash-reporting.md

文档预览地址：https://debug.flutter.cn/docs/reference/crash-reporting

建议完成天数：10 ~ 15 天

**Comment by yumi0629** [comment]
认领，预计完成天数：3天以内
