### ISSUE TITLE
No.161 - Write your first Flutter app on the web - 编写你的第一个 Flutter 网页应用

### ISSUE THREAD

**Issue by yunzhejude** [cfug/flutter.cn#593]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/codelab-web.md

文档预览地址：https://debug.flutter.cn/docs/get-started/codelab-web

建议完成天数：1 ~ 2 天

**Comment by lihang1991** [comment]
申请认领

**Comment by Vadaski** [comment]
确认认领，祝顺利！
