### ISSUE TITLE
No.163 - ParentDataWidget 的通用类型已更改为 ParentData

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#601]
Markdown 文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/release/breaking-changes/parent-data-widget-generic-type.md

文档预览地址：https://debug.flutter.cn/docs/release/breaking-changes/parent-data-widget-generic-type

建议完成天数：1 ~ 3 天

**Comment by yumi0629** [comment]
认领，预计完成天数：3天以内
