### ISSUE TITLE
[翻译] /docs/development/ui/animations/staggered-animations/

### ISSUE THREAD

**Issue by andyxiaoxi** [cfug/flutter.cn#605]
希望完成该文档的翻译。
文章链接: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/staggered-animations/index.md

**Comment by chenglu** [comment]
感谢 @andyxiaoxi，我检查了一下这个文档应该是翻译过了，谢谢你的热情，以及帮助我们找到了一个 bug：因为这个文档涉及到路径的修改，所以它在静态化处理的时候指向了旧的文档，目前已经修复了这个问题，如果你感兴趣其他的文档翻译，请在查看这个协作表里的任务，并通过 I 列的任务链接认领，谢谢！

**Comment by chenglu** [comment]
协作表：https://shimo.im/sheets/KaUjqukvcZciKQ4A/YEsuI

**Comment by chenglu** [comment]
我暂时先关闭这个 issue 了，如果有什么其他问题再跟进我们，谢谢！
