### ISSUE TITLE
'在 Windows 操作系统上安装和配置 Flutter 开发环境' page issue

### ISSUE THREAD

**Issue by lypat2008** [cfug/flutter.cn#628]
Page URL: https://flutter.cn/docs/get-started/install/windows.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:  

Problem:   "Android license status unknown" error on Flutter 1.12 with Android Studio 3.6 #51712
https://github.com/flutter/flutter/issues/51712

The Install Guide has been updated in flutter web site.

https://flutter.dev/docs/get-started/install/windows
![new](https://user-images.githubusercontent.com/49168365/77344085-a2e4fc00-6d6d-11ea-914b-786cbff995f7.jpg)

**Comment by lypat2008** [comment]
Section:

Install Android Studio
---------------------------------------------------------------------------

Warning: In Android Studio 3.6 or later, you need to manually add the old version of the Android SDK Tools for Flutter to work. To do this:

1 Open the Android Studio SDK Manager
2  In the Android SDK tab, uncheck Hide Obsolete Packages
3  Check Android SDK Tools (Obsolete)

**Comment by chenglu** [comment]
新的文档同步工作正在进行，正在处理由于ci的变更带来的错误，请稍等。

**Comment by chenglu** [comment]
这部分内容已经更新，请清空缓存或者强制刷新页面查看。
Issue closed，有任何问题请再跟进。
