### ISSUE TITLE
'集成测试介绍' page issue

### ISSUE THREAD

**Issue by twototwoto** [cfug/flutter.cn#649]
Page URL: https://flutter.cn/docs/cookbook/testing/integration/introduction.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/cookbook/testing/integration/introduction.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

> Integration tests 是成对出现的：首先，发布一个可测试应用程序到真是设备或者模拟器，然后，利用独立的测试套件去驱动应用程序，检查一切是否完好可用。

![真实设备](https://user-images.githubusercontent.com/18694645/82275604-c1eebb80-99b5-11ea-8fc5-7c589cafe905.png)

发布一个可测试应用程序到真实

设备的真实写错了。

**Comment by chenglu** [comment]
好的，收到。
