### ISSUE TITLE
'Widget 的淡入淡出效果' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#652]
Page URL: https://flutter.cn/docs/cookbook/animation/opacity-animation.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/cookbook/animation/opacity-animation.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
dartpad.dev 引用无法访问，应修正文档里 [以 ```run-dartpad:``` 方式运行 dartpad 的页面](https://github.com/cfug/flutter.cn/search?q=run-dartpad&unscoped_q=run-dartpad)，查看源码找到替换方案。

**Comment by cfug-dev** [comment]
nginx 替换 js，https://dartpad.cn/inject_embed.dart.js，将 dartpad.dev 替换为 dartpad.cn 可解。

**Comment by chenglu** [comment]
bug fixed, 已经替换并刷新 CDN。
