### ISSUE TITLE
'向 Android 应用中添加 Flutter Fragment' page issue

### ISSUE THREAD

**Issue by SevenWalnut** [cfug/flutter.cn#657]
Page URL: https://flutter.cn/docs/development/add-to-app/android/add-flutter-fragment.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/android/add-flutter-fragment.md

Description of issue:
```
flutterFragment.withCachedEngine("my_engine_id").build()
```
should be:
```
FlutterFragment.withCachedEngine("my_engine_id").build()
```
first latter should be F not f

**Comment by chenglu** [comment]
Thanks for your time to raise this issue, the original English docs are also using `flutterFragment` now, so I've created a PR there, once they are valid and update this, we will sync the docs to the cn site. 

Great to have your feedback, you helped the global Flutter developers!

**Comment by chenglu** [comment]
@Vadaski could you please help to verify this?

**Comment by Vadaski** [comment]
Sure, let me check it
