### ISSUE TITLE
Git 的 submodule 同步

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#659]
目前 CN 的 repo 里两个 submodule 跟官方是不同步的：

CN 是：
https://github.com/cfug/flutter.cn
```
flutter @ 8fbfe1c
site-shared @ a480c72
```

官方是：
https://github.com/flutter/website
```
flutter @ 5f21edf
site-shared @ 8c17259
```

不知道怎么样的命令可以在每次同步文档的时候同步上游文档的 submodule，或者说不同步估计问题也不大？

cc/ @asnowwolf 雪狼兄是否有经验？
also ping @Realank ，刘老师是否有经验？

@Vadaski 是否也可以帮我找一下解决方案，在自己的 repo 里 update 这个成功之后，发个 PR，然后把方法同步到 [wiki 页面](https://github.com/cfug/flutter.cn/wiki/Keep-updated-with-the-official-site)。

**Comment by Vadaski** [comment]
ok

**Comment by chenglu** [comment]
fixed:

```
# 进入项目文件夹
cd flutter.cn
# 同步最新 submodule 至本地仓库
git submodule foreach "(git checkout master; git pull)&"
# 提交本次 sync
git commit
# 推送到 Github
git push
```
