### ISSUE TITLE
[翻译] /docs/development/packages-and-plugins/background-processes.html

### ISSUE THREAD

**Issue by zhenghuan87916275** [cfug/flutter.cn#66]
希望完成该文档的翻译。
文章链接: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/packages-and-plugins/background-processes.md

**Comment by chenglu** [comment]
辛苦你的时间了，请简要自我介绍一下然后开始翻译吧，谢谢～
#3

**Comment by chenglu** [comment]
@zhenghuan87916275 进度怎么样啦？

**Comment by chenglu** [comment]
@zhenghuan87916275 好，我将在本 Issue 30 天没有进展的时候关闭并撤回任务哈。
现在进度怎么样啦？
