### ISSUE TITLE
'Flutter 布局基础教程' page issue

### ISSUE THREAD

**Issue by OceanAndWu** [cfug/flutter.cn#661]
Page URL: https://flutter.cn/docs/codelabs/layout-basics.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/codelabs/layout-basics.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by chenglu** [comment]
哪里遇到什么问题了呢？

**Comment by chenglu** [comment]
没有更多的信息反馈，本 issue 暂时关闭。
