### ISSUE TITLE
[翻译] /docs/get-started/flutter-for/android-devs.html

### ISSUE THREAD

**Issue by LoveLin0516** [cfug/flutter.cn#67]
希望完成该文档的翻译。
文章链接: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/flutter-for/android-devs.md

**Comment by chenglu** [comment]
谢谢你的时间，请简单介绍一下自己 #3 然后开始抽空完成这篇文档吧～

辛苦啦！

**Comment by chenglu** [comment]
@LoveLin0516 进度如何啦 ;-)

**Comment by chenglu** [comment]
@LoveLin0516 谢谢，我将在本 Issue 30 天没有进展的时候关闭并撤回任务哈。
现在进度怎么样啦？

**Comment by LoveLin0516** [comment]
抱歉，之前申请页面翻译是点错了，我以为这个申请是由别人来进行翻译操作。本人因为时间精力和英语水平，目前无法完成该页面的翻译工作，请撤回该任务。
带来麻烦，深感抱歉~ @chenglu

**Comment by chenglu** [comment]
好，谢谢提出，我会尽快招募到合适的志愿者小伙伴来翻译这篇文档，欢迎随时回来看看～
