### ISSUE TITLE
'深入理解布局约束' 文章反馈

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#680]
收集针对文章 https://flutter.cn/docs/development/ui/layout/constraints.html 的反馈和问题讨论。

将于文章发布之日 30 天之后关闭 issue。

**Comment by shuyankwok** [comment]
哪些组件会约束子元素，哪些不会？具体行为有什么差异，可以有个对比表格呈现一下。

**Comment by Vadaski** [comment]
@shuyankwok  每个 widget 的约束方式都是独特的，我自己的学习经验发现其实列出差异不如开启 DartPad 自己试一试印象会更深呢～

**Comment by chenglu** [comment]
文章反馈时间超过三十天，本 issue 关闭。微信文章阅读原文已经设置跳转到 flutter.cn 内容。
