### ISSUE TITLE
No.172 - List of state management approaches - 状态 (State) 管理参考

### ISSUE THREAD

**Issue by chenglu** [cfug/flutter.cn#691]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

英文文档预览：https://debug.flutter.cn/docs/development/data-and-backend/state-mgmt/options

建议完成时间：3 - 5 天

**Comment by AlexV525** [comment]
认领
