### ISSUE TITLE
'打包并发布 iOS 应用' page issue

### ISSUE THREAD

**Issue by CaiJingLong** [cfug/flutter.cn#721]
Page URL: https://flutter.cn/docs/deployment/ios.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/deployment/ios.md

Description of issue:

有部分中文和英文会同时显示, 而不是像其他行, 只显示中文, 点击时才显示英文原本, 见截图
![image](https://user-images.githubusercontent.com/14145407/92851736-7eb2cf80-f420-11ea-9799-255b90f45c2f.png)

红色部分: 不正常,默认同时显示 
绿色部分: 正常的, 点击中文出现英文, 中间有虚线分割中英文

---
参考了别的正常的markdown, 没找到修复方式

**Comment by AlexV525** [comment]
cc @Vadaski because the document was synced by #507 .

The problem might the content alignment.

https://github.com/cfug/flutter.cn/blob/f7b37da7226969ed1e5fd52281f2cfd5125d520b/src/docs/deployment/ios.md#L209-L211

**Comment by chenglu** [comment]
谢谢提出问题，由于使用了双语显示工具，在对冒号的处理里，有一个 [特别的 exception](https://github.com/cfug/flutter.cn/wiki/Translation-Spec#%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F) 应该是我们同步文档的时候忘记替换了，最新的 PR 应该可以修复这个问题，等 CI 通过之后先看一下预览。

**Comment by CaiJingLong** [comment]
debug.flutter.cn 上目测正常了

**Comment by chenglu** [comment]
我又改了个小问题，等 @Vadaski 修改 Banner 的 PR merged 之后，去手动进行 flutter.cn 的部署，再次感谢龙哥 @CaiJingLong 和 @AlexV525 。
