### ISSUE TITLE
'将 Flutter module 集成到 iOS 项目' page issue

### ISSUE THREAD

**Issue by DeveloperLx** [cfug/flutter.cn#726]
Page URL: https://flutter.cn/docs/development/add-to-app/ios/project-setup.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/add-to-app/ios/project-setup.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

You can also run the module in Android Studio/IntelliJ or VS Code with the Flutter and Dart plugins.
你也同样可以在 Android Studio/IntelliJ 或者 VS Code 中运行这个模块，并附带 Flutter 和 Dart 插件

这个翻译不对，with 在这里是“通过”的意思

**Comment by chenglu** [comment]
谢谢 @DeveloperLx 的提醒，已经提了一个 commit 修复了这个翻译。

**Comment by chenglu** [comment]
此翻译内容已经被修复，再次谢谢提出！
