### ISSUE TITLE
'Flutter 应用里的国际化' page issue

### ISSUE THREAD

**Issue by zhonghanwen** [cfug/flutter.cn#744]
Page URL: https://flutter.cn/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
乱码
![image](https://user-images.githubusercontent.com/12220537/97839304-e567b180-1d1c-11eb-8044-1e05786181bd.png)

**Comment by chenglu** [comment]
OK, 我来处理一下。
