### ISSUE TITLE
SJTUG Flutter 镜像已全量同步

### ISSUE THREAD

**Issue by skyzh** [cfug/flutter.cn#766]
我们近期对镜像站架构进行了一些升级。目前 flutter_infra 与 dart-pub 都从反向代理切换成了全量同步，应该已经解决了之前报告的重定向回 google storage 的问题，使用体验应该会好很多。

希望 flutter.cn 可以帮忙更新一下相关的文档(比如 https://flutter.cn/community/china )，并测试一下目前 SJTUG 镜像站是否可用。感谢。

**Comment by AlexV525** [comment]
感谢知会，我们会尽快进行更新

**Comment by chenglu** [comment]
Hi Alex @skyzh:

感谢一直以来的帮助，我测试看了一下 pub get 的行为应该是正常了的， @Vadaski @AlexV525 @Realank 几位同学按照 flutter.cn 上的配置，配置一下 SJTUG 的镜像试试看？

另外，我们为镜像新增添了一个目录 `download.flutter.io/` [详见](https://mirrors.tuna.tsinghua.edu.cn/flutter/download.flutter.io/)，是否可以帮忙把这个目录也做一下同步？它反向代理的是 https://storage.googleapis.com/download.flutter.io

感谢！
Luke

**Comment by AlexV525** [comment]
`flutter pub get` 目前测试未发现问题，但是 `flutter doctor` 进行 SDK 初始化的时候貌似无法访问到 Dart SDK。

![image](https://user-images.githubusercontent.com/15884415/101611213-349fb100-3a44-11eb-8136-2c01d25e05c0.png)

**Comment by skyzh** [comment]
b0d31ae 这个 hash 在 TUNA（我们目前的上游）也不存在。可能需要做刷新缓存之类的操作？

**Comment by AlexV525** [comment]
> b0d31ae 这个 hash 在 TUNA（我们目前的上游）也不存在。可能需要做刷新缓存之类的操作？

这个是我昨天同步的 master branch hash，昨天有从我们的镜像拉过。需要我怎么配合？

**Comment by skyzh** [comment]
有没有更详细的信息可以查看呢？（比如带 `-v` 执行命令？）

**Comment by AlexV525** [comment]
结果一致，显示只有14bytes并且下载完成，最后找不到。verbose没有额外的log

**Comment by skyzh** [comment]
好的，我猜想是 404 了。之后我再自己测试一下。感谢。

**Comment by skyzh** [comment]
download.flutter.io 已经添加。请问现在是否还会有 404 问题呢？

**Comment by AlexV525** [comment]
测试了下，问题仍然出现。`4797b066524201e86d6bc5c110104c390899f264`

![image](https://user-images.githubusercontent.com/15884415/102062716-1238d980-3e30-11eb-8236-ab2c7b0d001c.png)

**Comment by skyzh** [comment]
看起来 stable 是可以的，master 似乎是因为还没有同步导致的。

<img width="691" alt="image" src="https://user-images.githubusercontent.com/4198311/102063202-ac991d00-3e30-11eb-8810-9757ba9c3ebc.png">

**Comment by AlexV525** [comment]
https://github.com/flutter/flutter/commit/63062a64432cce03315d6b5196fda7912866eb37 可以试试，19小时前的。

**Comment by skyzh** [comment]
似乎是因为我们目前的上游 TUNA https://github.com/tuna/tunasync-scripts/issues/63 没有同步 beta 导致的。看起来是暂时不太好解决的问题。

**Comment by chenglu** [comment]
谢谢 Alex，清华的源在设计之初应该有 “404 回源到 flutter-io.cn” 的策略（现在应该也还有保留），建议 @skyzh 也可以设定？

比如在 tuna issue 里提到的 artifacts.zip 文件在 tuna 里是空文件夹，但是仍可下载，可能就是通过 404 回源请求 storage.flutter-io.cn，然后再返回结果给用户的。

另外，在请求 pub.dartlang.org 的时候，建议加入一个 user agent，这样可以帮助 Flutter 团队的工程师识别我们的流量而不会误判：
user-agent: dart-pub.mirrors.sjtug.sjtu.edu.cn

最后，类似这样的 API Call:
https://dart-pub.mirrors.sjtug.sjtu.edu.cn/api/packages/flutter_bdface_plugin
预期应该是返回一串 JSON，而 👆 的返回值是在下载一个文件？

@AlexV525 跑一下 pub get 看是否有问题？

**Comment by skyzh** [comment]
感谢提醒。404 回源在我们的很多 repo 里都支持，我们预计在月底为 flutter 加上这个功能。

我们的 User-Agent 均为 mirror-intel (siyuan.internal.sjtug.org)。

**Comment by skyzh** [comment]
json 返回值变成 gz 的问题我们会调查一下。感谢提醒。

**Comment by AlexV525** [comment]
`flutter update-packages`

```none
Download failed.                                                        
URL: https://mirrors.sjtug.sjtu.edu.cn/flutter_infra/flutter/coverage/lcov.info
Error: 404 Not Found
```

![image](https://user-images.githubusercontent.com/15884415/102174569-c4c47700-3ed8-11eb-8af7-4e2796e7dcba.png)

**Comment by skyzh** [comment]
看起来也是 TUNA 那边没有同步，转发到 flutter.cn 的文件。之后做好 404 转发后，我再更新一下这个 issue。感谢测试！

**Comment by skyzh** [comment]
我们已经修复了 Pub API 返回 gzip 的问题。与此同时，flutter 也添加了回源策略。如果某个文件在我们的缓存中不存在，用户会被重定向到 storage.googleapis.com；与此同时，我们会在后台将文件缓存在服务器上（这个过程只需要 10s 左右）。之后的下载都会直接走我们的缓存。

没有选择回源到 flutter.cn 是因为
* 之前尝试将 flutter.cn 作为镜像上游时，发现大量请求 Timeout。
* 目前的架构只能做到缓存下载和返回给用户的重定向请求为同一个地址。

感谢各位的测试！

**Comment by skyzh** [comment]
另外 `https://mirrors.sjtug.sjtu.edu.cn/flutter_infra/flutter/coverage/lcov.info` 这个文件是否会被修改，能否永久保存？我们可能还需要调整一下缓存策略。

**Comment by chenglu** [comment]
> 如果某个文件在我们的缓存中不存在，用户会被重定向到 storage.googleapis.com 

重定向到 storage.flutter-io.cn 可否，以避免单次不可用给用户带来的不好体验。

> 之前尝试将 flutter.cn 作为镜像上游时，发现大量请求 Timeout。

比如？

storage.flutter-io.cn 的策略是内网直接穿透，从上海走内网到香港直接拉 storage.googleapis.com 内容（仅限定的 bucket 比如 flutter_infra, dart-archive 等），然后缓存在国内的云存储上下次就直接从国内云存储获取，国内云存储只保留三个月的热数据。

Btw，我简单更新了镜像站的 Flutter 配置说明，https://github.com/sjtug/portal/pull/46 请审核。

**Comment by AlexV525** [comment]
> 另外 `https://mirrors.sjtug.sjtu.edu.cn/flutter_infra/flutter/coverage/lcov.info` 这个文件是否会被修改，能否永久保存？我们可能还需要调整一下缓存策略。

根据 https://github.com/flutter/flutter/wiki/Test-coverage-for-package:flutter#how-to-view-test-coverage 这个文件是可变更的。

**Comment by skyzh** [comment]
对 flutter 镜像源的调整已经完成。目前，`lcov.info` 已经设置为全部跳转到 `storage.flutter-io.cn`，不会再缓存天。对于没有缓存的文件，会将用户重定向到 `storage.flutter-io.cn`。（镜像源服务器依然从 `storage.googleapis.com` 获取文件）

**Comment by AlexV525** [comment]
目前 `flutter doctor`、`flutter pub get` 和 `flutte update-packages` 都是正常的，速度也比原来快了一些 👍 

![image](https://user-images.githubusercontent.com/15884415/103117148-212b5180-46a4-11eb-993a-1e95ec3738a3.png)

![image](https://user-images.githubusercontent.com/15884415/103117175-31433100-46a4-11eb-85a8-3bf75b73afe4.png)

![image](https://user-images.githubusercontent.com/15884415/103117178-3902d580-46a4-11eb-976a-8ce678856e21.png)

**Comment by AlexV525** [comment]
已在 #775 发起内容更新
