### ISSUE TITLE
[翻译] /docs/cookbook/animation/animated-container.html

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#77]
申请翻译该文档：
https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/animation/animated-container.md

GitHub ID 是：@Vadaski

**Comment by inferjay** [comment]
感谢参与翻译，一次最好只申请一个翻译任务，谢谢！

**Comment by Vadaski** [comment]
好的！下次会注意

**Comment by Vadaski** [comment]
初稿 @Dong09 校对@Vadaski

**Comment by chenglu** [comment]
谢谢，已经合并了本 issue 提到的翻译稿，辛苦鑫磊啦
