### ISSUE TITLE
[翻译] /docs/cookbook/animation/opacity-animation.html

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#78]
申请翻译该文档：
https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/animation/opacity-animation.md
GitHub ID 是：@Vadaski

**Comment by chenglu** [comment]
@Vadaski 鑫磊这个稿子怎么样，什么时候能交，需要什么帮助吗？

**Comment by Vadaski** [comment]
不好意思拖久了，这个稿子就今天交，我去催一下翻译的同学，他还没弄的话我就自己来😅

**Comment by Vadaski** [comment]
翻译：@Robinhaizhou 校对：@Vadaski

**Comment by chenglu** [comment]
great job!
