### ISSUE TITLE
No.178 - Reduce shader compilation jank on mobile - 减少移动设备上的着色器动画卡顿

### ISSUE THREAD

**Issue by MeandNi** [cfug/flutter.cn#788]
Markdown 文件路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/perf/rendering/shader.md

英文文档预览：https://flutter.cn/docs/perf/rendering/shader.html

建议完成时间：5 - 7 天

**Comment by Vadaski** [comment]
认领该文章
