### ISSUE TITLE
'撰写双端平台代码（插件编写实现）' page issue

### ISSUE THREAD

**Issue by tjuchen** [cfug/flutter.cn#795]
Page URL: https://flutter.cn/docs/development/platform-integration/platform-channels.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/platform-integration/platform-channels.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
（1）in "https://flutter.cn/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab" create a new flutter project:
should not use "flutter create -i swift -a kotlin batterylevel", but use "flutter create -i objc -a java batterylevel"
（2）in "https://flutter.cn/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab" Add an iOS platform-specific implementation:
"#import <Flutter/Flutter.h>" would make error like "can not find flutter", you should build this xcode project and add "App.framework" and "Flutter.framework" in embed framework of "build phases", and this error can be solved. At last, when you run this flutter app, you should delete these two frameworks just in case "Your Xcode project requires migration"
refer "http://www.cocoachina.com/articles/25392"
you can describe this step(Add an iOS platform-specific implementation) more detail, so we can understand it easier.

**Comment by AlexV525** [comment]
Thanks for reporting.
* (1) is also tracked in #794 .
* (2) Your anchor for the web pages seems not matched with your description, but I guess you're talking about https://flutter.cn/docs/development/platform-integration/platform-channels#step-4a-add-an-ios-platform-specific-implementation . As I imagine, we don't need to add framework references if the project has been built or set up manually. So IMO the error won't exist if you have run the `example` project for the plugin once.

**Comment by tjuchen** [comment]
> Thanks for reporting.
> 
> * (1) is also tracked in #794 .
> * (2) Your anchor for the web pages seems not matched with your description, but I guess you're talking about https://flutter.cn/docs/development/platform-integration/platform-channels#step-4a-add-an-ios-platform-specific-implementation . As I imagine, we don't need to add framework references if the project has been built or set up manually. So IMO the error won't exist if you have run the `example` project for the plugin once.

i use "flutter create -i objc -a java batterylevel"  and create a new flutter project, but there doesn't exist folder which name is "example". And if i build this project would make error. (i have already told @Vadaski about this issue)

**Comment by tjuchen** [comment]
![Uploading image.png…]()

**Comment by tjuchen** [comment]
![image](https://user-images.githubusercontent.com/22878573/105443492-cd158c00-5ca6-11eb-9b75-425200977d81.png)

**Comment by Vadaski** [comment]
Yes,  thanks for reporting this issue! We will fix it tonight ; )
