### ISSUE TITLE
[翻译] /docs/cookbook/design/tabs.html

### ISSUE THREAD

**Issue by Vadaski** [cfug/flutter.cn#80]
申请翻译该文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/design/tabs.md

GitHub ID 是：@Vadaski

**Comment by chenglu** [comment]
👍，辛苦了。

**Comment by Vadaski** [comment]
翻译：@Dosimz @Vadaski  校对：@Vadaski
