### ISSUE TITLE
'Codelabs' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#809]
Page URL: https://flutter.cn/docs/codelabs/
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/codelabs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

![image](https://user-images.githubusercontent.com/47591151/106630513-dd870a00-65b6-11eb-91b3-5c1d65f343dd.png)

链接失效，后面两个 codelabs 的链接失效了。

**Comment by cfug-dev** [comment]
Firebase 那个中国链接可以是 https://firebase.google.cn/learn/codelabs/firebase-get-to-know-flutter#0

下面那个链接好像还木有同步到 Cn 的 Codelabs site 上。

**Comment by AlexV525** [comment]
应该在 #980 和 #986 中修复了。
