### ISSUE TITLE
'在中国网络环境下使用 Flutter' page issue

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#814]
Page URL: https://flutter.cn/community/china.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/community/china.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
页面需要加入双语显示。

**Comment by chenglu** [comment]
不需要加入了，这个页面已经被排除在双语显示之外了，单中文即可。
