### ISSUE TITLE
[翻译] /docs/reference/tutorials.md

### ISSUE THREAD

**Issue by MzoneCL** [cfug/flutter.cn#82]
申请翻译该文档：https://github.com/cfug/flutter.cn/blob/master/src/docs/reference/tutorials.md

GitHub ID 是：@MzoneCL

**Comment by chenglu** [comment]
确认一下，这个文档已经有了中文翻译了，要不换一个其他的？
应该是因为格式问题，所以看起来页面里仍然有中文，详见 https://debug.flutter.cn/docs/reference/tutorials
谢谢~

**Comment by chenglu** [comment]
刚刚修改了一下格式把英文删掉了，等 CI 工作之后应该就正常显示中文了，FYI
