### ISSUE TITLE
'Web renderers' page issue

### ISSUE THREAD

**Issue by rainsolo** [cfug/flutter.cn#823]
Page URL: https://flutter.cn/docs/development/tools/web-renderers.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/tools/web-renderers.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Is the command to switch rendering mode missing a '=' ??
flutter build web --web-renderer html --release     => error, the renderer mode still default
flutter build web --web-renderer=html --release   => success

**Comment by chenglu** [comment]
Hi @rainsolo, the command should be alright, please upgrade Flutter to a recent stable channel and try again, feel free to reopen this issue to let me know if you still stuck on this (please also attach the log: `flutter doctor -v`)
