### ISSUE TITLE
No.181 - Ads support for Flutter - Flutter 对广告的支持

### ISSUE THREAD

**Issue by AlexV525** [cfug/flutter.cn#830]
ref #829 

Markdown 文档路径：https://github.com/cfug/flutter.cn/blob/master/src/ads/index.md

英文文档预览：https://flutter.cn/docs/ads

预计完成时间：1 - 3 天

**Comment by yumi0629** [comment]
认领。计划完成时间：4月24日。

**Comment by YouYiShan1248** [comment]
Hello, I would like to translate this document

**Comment by AlexV525** [comment]
@YouYiShan1248 Good luck with your translations and make sure you've read our translation flow and spec in our [wiki](https://github.com/cfug/flutter.cn/wiki) carefully. 🚀
