### ISSUE TITLE
No.185 - Configuring the URL strategy on the web - 配置 Web 应用的 URL 策略

### ISSUE THREAD

**Issue by AlexV525** [cfug/flutter.cn#834]
ref #829

Markdown 文档路径：https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/navigation/url-strategies.md

英文文档预览：https://debug.flutter.cn/docs/development/ui/navigation/url-strategies

预计完成时间：3 - 5 天

**Comment by yumi0629** [comment]
认领任务，计划完成时间：4月14日。
