### ISSUE TITLE
'编辑工具设定' page issue

### ISSUE THREAD

**Issue by 404-error-404** [cfug/flutter.cn#843]
Page URL: https://flutter.cn/docs/get-started/editor?tab=vscode
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/editor.md

Description of issue:

The plugins I need to install for VS code are not only "Flutter" and "Dart", but also "Android iOS Emulator". Otherwise I can't find the "No device" button.

Finally, Thank you for your document!

**Comment by chenglu** [comment]
@AlexV525 could you please help to reproduce this issue?

**Comment by 404-error-404** [comment]
> @AlexV525 could you please help to reproduce this issue?

不好意思，是我没说清楚。这个其实也不算问题，只是我的一个建议：在教程中安装扩展的地方增加Android iOS Emulator扩展。因为在安装扩展的时候只提示我安装FLutter和Dart，但没有提示我安装Android IOS Emulator扩展，这样的话会导致我后边找不到在哪选择模拟器。
谢谢你的回复！

**Comment by AlexV525** [comment]
感谢反馈。我有一个疑问：Android iOS Emulator 指的是 Android 模拟器还是 iOS 模拟器？Android Emulator 确实需要单独下载，而 iOS Simulator 是自带的。

**Comment by AlexV525** [comment]
或者是 VSCode 的 「Android iOS Emulator」 extension？

**Comment by 404-error-404** [comment]
对！Android iOS Emulator不是模拟器，他是VS code插件商店里边的一个扩展插件，但是不装的话是没有办法调用模拟器的

**Comment by AlexV525** [comment]
谢谢解疑，因为平时不用 VSCode，晚些我会尝试验证下。在此之前我建议开一个新的 issue 到 flutter/website ，我们一般不操作原文。我可以在官方仓库中帮助你修改它。

**Comment by 404-error-404** [comment]
麻烦你们了！

**Comment by chenglu** [comment]
顺便说，如果 @404-error-404 可以帮忙写一篇小教程投稿在 https://flutter.cn/community/tutorials 的话，我们倒是可以在这里加入一个 tips 框链接过去，作为延展阅读。

**Comment by 404-error-404** [comment]
我也想，但不会，我就是在看你们的教程入门，等以后水平上来了再写教程(≖ᴗ≖)✧

**Comment by chenglu** [comment]
@404-error-404 加油加油！

**Comment by AlexV525** [comment]
我尝试使用了一下 VSCode，选择设备的时候，我的 Android/iOS 模拟器都正常显示在设备列表里，同时包含了一个 Create Android Emulator 的选项。并没有安装 Android iOS Emulator Extension
![image](https://user-images.githubusercontent.com/15884415/113660073-f0f94300-96d5-11eb-9bb4-b87a6b91c619.png)
![image](https://user-images.githubusercontent.com/15884415/113660084-f6ef2400-96d5-11eb-8f8a-9175bbb1b20a.png)

**Comment by 404-error-404** [comment]
> 我尝试使用了一下 VSCode，选择设备的时候，我的 Android/iOS 模拟器都正常显示在设备列表里，同时包含了一个 Create Android Emulator 的选项。并没有安装 Android iOS Emulator Extension
> ![image](https://user-images.githubusercontent.com/15884415/113660073-f0f94300-96d5-11eb-9bb4-b87a6b91c619.png)
> ![image](https://user-images.githubusercontent.com/15884415/113660084-f6ef2400-96d5-11eb-8f8a-9175bbb1b20a.png)

不好意思给你们添麻烦了，我现在也没办法复现这个问题了，我把Android iOS Emulator Extension卸载之后也还可以选择模拟器，真不好意思给你们添麻烦了

**Comment by chenglu** [comment]
完全没有添麻烦的，为你的探索精神点赞。
