### ISSUE TITLE
'占位符和网络图片淡入' page issue

### ISSUE THREAD

**Issue by bx-code** [cfug/flutter.cn#855]
Page URL: https://flutter.cn/docs/cookbook/images/fading-in-images.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/cookbook/images/fading-in-images.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by chenglu** [comment]
暂时木有更多相关信息，就当是误触了叭～ Issue 先关啦。
