### ISSUE TITLE
有一个小疑问

### ISSUE THREAD

**Issue by yanshouwang** [cfug/flutter.cn#860]
为什么镜像的域名使用 flutter-io.cn 而不是 flutter.cn 呢，我强迫症有点严重😀

**Comment by chenglu** [comment]
好问题，最初在内部计划镜像项目的时候，就计划并使用 flutter-io.cn (pub.flutter-io.cn / storage.flutter-io.cn) 作为镜像的域名。

后来到 18 年 GMTC，在 [Flutter RP 1](https://www.bilibili.com/read/cv620258/) 的时候发布了 flutter-io.cn 作为一个 mini-site，推荐了一些中文文档和中文的社区内容，也把一些 Flutter 的 codelabs 在 [codelabs.flutter-io.cn](https://codelabs.flutter-io.cn/) 上做了发布。

再后来我们发起了新版中文文档的翻译，在 19 年 GDD 大会上 [正式上线了 flutter.cn](https://zhuanlan.zhihu.com/p/83222900)，包含完整的中文文档和社区的资源推荐，因此 flutter.cn 就一直被启用和使用到现在。

整个一个时间线大致是这样的，镜像的域名没有做改动是不希望让已经在使用 Flutter 的开发者有更多的操作，希望可以理解哈。

**Comment by yanshouwang** [comment]
那可以把flutter.cn的这两个域名也解析到镜像上去吗？感觉这样会舒服好多

**Comment by chenglu** [comment]
请求驳回 ;-)

不过倒是可以考虑未来加入一个 302 跳转，让 pub.flutter.cn 和 storage.flutter.cn 跳转到 flutter-io.cn 去 ;-)
