### ISSUE TITLE
'Widgets 介绍' page issue: required应为@required

### ISSUE THREAD

**Issue by Power-tile** [cfug/flutter.cn#863]
Page URL: https://flutter.cn/docs/development/ui/widgets-intro.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/widgets-intro.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

[Widgets->基础Widgets](https://flutter.cn/docs/development/ui/widgets-intro#basic-widgets)代码示例的第四行为：
```dart
  MyAppBar({required this.title});
```
而实际应为
```dart
  MyAppBar({@required this.title});
```
原代码无法运行，在vscode中会报错```required isn't a type. Try correcting the name to match an existing type.``` 此处应为用注解标记```this.title```为```MyAppBar```构造函数中的必有参数。

**Comment by AlexV525** [comment]
`required` 是空安全版本的 Dart 中的新关键字，`@required` 为未启用空安全时的 **必需命名参数** 注解。有关 `required` 的介绍可参考 https://dart.cn/null-safety/understanding-null-safety#required-named-parameters 。如你的本地环境尚未支持空安全，可以手动改为 `@required` 或升级 SDK 并进行迁移以解决。

![image](https://user-images.githubusercontent.com/15884415/116803950-9d9bd880-ab4d-11eb-828c-5518c0038f9b.png)
