### ISSUE TITLE
关于 `` 的使用规范

### ISSUE THREAD

**Issue by wenxiangjiang** [cfug/flutter.cn#934]
你好，请问 `` 的使用规范是什么？在 [中文文案排版指南 (Chinese Typography Guide)](https://github.com/cfug/flutter.cn/wiki/中文文案排版指南-(Chinese-Typography-Guide)) 中没有找到相关说明。

通过我的观察，大多数翻译文档在使用 `` 的时候都是跟官方保持同步。当然也存在未与官方同步的情况，比如 [这里](https://flutter.cn/docs/development/ui/widgets-intro#responding-to-widget-lifecycle-events) 的翻译文档内容。

<img width="950" alt="20210816-100039" src="https://user-images.githubusercontent.com/10527100/129501940-c8f4fead-e9c6-41b4-b488-2e9716a71b30.png">

**Comment by AlexV525** [comment]
主要原则就是与官方文档同步。某些文档可能由于历史同步原因没有完全同步，或者译者及审阅者认为相关内容可以降低其强调的权重时，也会适当的简配（不使用 \`\`）。

**Comment by wenxiangjiang** [comment]
我个人的理解，强调的权重应该是通过 ** ** 来实现，而反引号的作用是用来标记简短的代码，所以 `flutter` 如果作为一个命令，则使用反引号标记，而 Flutter 作为一门语言而不是代码，则可以直接书写。

@AlexV525 我在实际使用时对这种用法不是特别确定，希望专业人士能够指正，谢谢。

**Comment by AlexV525** [comment]
> 我个人的理解，强调的权重应该是通过 ** ** 来实现，而反引号的作用是用来标记简短的代码

这里的说的「强调的权重」首先要以原文为准，指的是在界定「命令」和名称有歧义时，考虑上下文来决定是否强调为命令。
一般情况下我们会完全依照原文使用，以下是一些常见的处理方法：
- dart run 工具
- `dart pub run`
- pub global 工具
- flutter 命令行工具
- `flutter --help`
- 使用 pub get 获取 packages
- `flutter pub get`

如果你有更详细的上下文内容，可以提供进行讨论。

**Comment by wenxiangjiang** [comment]
@AlexV525 谢谢指导，现在主要是我自己有些时候会拿捏不准，以后会尝试按照示例方法进行处理。后续如果有具体的上下文内容，再来此贴请教。

**Comment by chenglu** [comment]
> 存在未与官方同步的情况，比如 [这里](https://flutter.cn/docs/development/ui/widgets-intro#responding-to-widget-lifecycle-events) 的翻译文档内容。

根据我的经验，在同步文档的时候，对于上游文档修改而造成的 conflict 可以明显发现，如果上游文档只是修改了格式，比如是给部分文字或者链接加入了代码块包裹符 ``，这个在同步文档的时候很难发现，如果发现这样类似的不一致可以发 issue 或者开 PR 直接修复它。

同意你们的讨论，内容强调是使用加粗形式来完成。感谢提供这么有价值的讨论，谢谢两位！
