### ISSUE TITLE
[PAGE ISSUE]: '关于 Flutter 文档中文版'

### ISSUE THREAD

**Issue by devcui** [cfug/flutter.cn#942]
### Page URL

https://flutter.cn/docs/development/accessibility-and-localization/internationalization#setting-up

### Page source

https://flutter.cn/docs/development/accessibility-and-localization/internationalization#setting-up

### Describe the problem

您好，国际化部分有一小处地方，为了避免一些不必要的麻烦，文章中有一处地方需要稍加修改

原文 `为了让 CN，TW 和 HK 三个不同的国家/地区代码能够完整地表达每个变种的中文，你应该包括以下支持的语言环境`

### Expected fix

为了让 CN，TW 和 HK 三个不同地区代码能够完整地表达每个变种的中文，你应该包括以下支持的语言环境

十分感谢您对flutter文档翻译做出的贡献🙏

**Comment by AlexV525** [comment]
感谢你的建议。`国家/地区代码` 是一种较为通用的说法，其他通用的说法还有：
- [国家地区代码](https://zh.wikipedia.org/zh-cn/%E5%9B%BD%E5%AE%B6%E5%9C%B0%E5%8C%BA%E4%BB%A3%E7%A0%81)
- [国家和地区代码（世界各国和地区名称代码）](https://baike.baidu.com/item/%E5%9B%BD%E5%AE%B6%E5%92%8C%E5%9C%B0%E5%8C%BA%E4%BB%A3%E7%A0%81/52038578)
- [国家代码](https://baike.baidu.com/item/%E5%9B%BD%E5%AE%B6%E4%BB%A3%E7%A0%81/6518042)
- [国家和所属地区名称代码](http://www.samr.gov.cn/xw/sj/201908/t20190823_306228.html)

所有以上的描述都指向的是基于 ISO3166《国家和所属地区名称代码》标准的规定。这些描述均遵循「一个中国」原则。

为了更好地表示和说明该名词的特殊性，我们调整了一下描述及参考链接。

再次感谢你的建议！

**Comment by chenglu** [comment]
谢谢 @devcui 的建议和 @AlexV525 的修改，原始中文翻译容易在断句时引起不必要的误会和麻烦，应该做出修改，非常细心的发现，感谢两位！

**Comment by chenglu** [comment]
经过一些资料查询，我建议遵循这份 [国标](http://std.samr.gov.cn/gb/search/gbDetailed?id=5DDA8BA23A9018DEE05397BE0A0A95A7) 文档，将 Flutter 中文文档中的「country code」翻译为「国家和地区代码」，同时对 @devcui 提到的部分做一些翻译优化，我去对 PR 做一下更新。
