### ISSUE TITLE
[PAGE ISSUE]: 一些页面未正确同步英文内容/链接引用无效

### ISSUE THREAD

**Issue by CCXXXI** [cfug/flutter.cn#965]
### 页面 URL

https://flutter.cn/docs/get-started/flutter-for/react-native-devs/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/docs/get-started/flutter-for/react-native-devs.md

### 描述问题

未正确同步英文内容。

https://raw.githubusercontent.com/cfug/flutter.cn/master/src/docs/get-started/flutter-for/react-native-devs.md
```markdown
Text fields allow users to type text into your app so they can be used to build
forms, messaging apps, search experiences, and more. Flutter provides two
core text field widgets:
[TextField][] and
[TextFormField][].
```

https://raw.githubusercontent.com/flutter/website/main/src/docs/get-started/flutter-for/react-native-devs.md
```markdown
Text fields allow users to type text into your app so they can be
used to build forms, messaging apps, search experiences, and more.
Flutter provides two core text field widgets:
[`TextField`][] and [`TextFormField`][].
```

### 附加信息

[hero-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/hero-animations.md), [json.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md) 等页有类似问题

**Comment by AlexV525** [comment]
> [hero-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/hero-animations.md), [json.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md) 等页有类似问题

有时间可以一并排查下，这些是历史同步时 merge 的问题。

**Comment by CCXXXI** [comment]
> > [hero-animations.md](https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/animations/hero-animations.md), [json.md](https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md) 等页有类似问题
> 
> 有时间可以一并排查下，这些是历史同步时 merge 的问题。

这些我是通过无效链接（HTML 里直接出现了类似 `[TextField][] and [TextFormField][].` 的东西）注意到的，写了个[脚本](https://gist.github.com/CCXXXI/af4fc7659a0612629ad0eeca460f2cf8)扫了一遍，发现以下文件比较可疑：
<details>

1. https://github.com/cfug/flutter.cn/blob/master/src/desktop.md
2. https://github.com/cfug/flutter.cn/blob/master/src/community/tutorials/text-classification-using-tensorflow-lite-plugin-for-flutter.md
3. https://github.com/cfug/flutter.cn/blob/master/src/docs/null-safety.md
4. https://github.com/cfug/flutter.cn/blob/master/src/docs/whats-new.md
5. https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/index.md
6. https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/layout-basics.md
7. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/effects/gradient-bubbles.md
8. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/gestures/handling-taps.md
9. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/fetch-data.md
10. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/persistence/sqlite.md
11. https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/android.md
12. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/firebase.md
13. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md
14. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/state-mgmt/options.md
15. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/developing-packages.md
16. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/using-packages.md
17. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/c-interop.md
18. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/platform-channels.md
19. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/web.md
20. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/vs-code.md
21. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/memory.md
22. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/overview.md
23. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-1.12.13.md
24. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-1.17.0.md
25. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-1.20.0.md
26. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-1.22.0.md
27. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-1.9.1.md
28. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-2.0.0.md
29. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-2.2.0.md
30. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/release-notes-2.5.0.md
31. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.12.13.md
32. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.17.0.md
33. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.2.1.md
34. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.5.4.md
35. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.7.8.md
36. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/sdk/release-notes/changelogs/changelog-1.9.1.md
37. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/assets-and-images.md
38. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/widgets-intro.md
39. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/hero-animations.md
40. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/index.md
41. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/overview.md
42. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/adaptive-responsive.md
43. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/index.md
44. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/responsive.md
45. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/tutorial.md
46. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/android-devs.md
47. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/ios-devs.md
48. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/react-native-devs.md
49. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/xamarin-forms-devs.md
50. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-chromeos.md
51. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-linux.md
52. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_androidstudio.md
53. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_terminal.md
54. https://github.com/cfug/flutter.cn/blob/master/src/docs/reference/crash-reporting.md
55. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/architectural-overview.md
56. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/faq.md
57. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/videos.md
58. https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/code-debugging.md
59. https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/debugging.md
60. https://github.com/cfug/flutter.cn/blob/master/src/_includes/docs/dart-tool.md

</details>

没逐个检查过，我猜可能有一些误报。

**Comment by CCXXXI** [comment]
> 有时间可以一并排查下，这些是历史同步时 merge 的问题。

既然有中英对照脚本，略加修改把扫描出的中文部分去掉，再去和英文文档对比，应该比人工检查更可靠。

**Comment by AlexV525** [comment]
内容太多，花了较多时间进行比对，可以关注 PR 是否已处理完上述标记的内容。

**Comment by CCXXXI** [comment]
> 内容太多，花了较多时间进行比对，可以关注 PR 是否已处理完上述标记的内容。

稍微改进了脚本之后扫出了以下文件，人工排查了前10个发现都是有失效链接的，推测剩下的应该很少是误报了。

1. https://github.com/cfug/flutter.cn/blob/master/src/docs/null-safety.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/whats-new.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/index.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/layout-basics.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/effects/gradient-bubbles.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/gestures/handling-taps.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/fetch-data.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/android.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/firebase.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/state-mgmt/options.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/developing-packages.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/using-packages.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/c-interop.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/platform-channels.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/web.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/memory.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/overview.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/assets-and-images.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/widgets-intro.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/hero-animations.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/index.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/overview.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/adaptive-responsive.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/index.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/responsive.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/android-devs.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/ios-devs.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/react-native-devs.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/xamarin-forms-devs.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-chromeos.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-linux.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_androidstudio.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_terminal.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/reference/crash-reporting.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/architectural-overview.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/faq.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/videos.md
1. https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/code-debugging.md
1. https://github.com/cfug/flutter.cn/blob/master/src/_includes/docs/dart-tool.md
