### ISSUE TITLE
[PAGE ISSUE]: '短时 (ephemeral) 和应用 (app) 状态的区别'

### ISSUE THREAD

**Issue by CCXXXI** [cfug/flutter.cn#968]
### 页面 URL

https://flutter.cn/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app.md

### 描述问题

斜体不美观，如图：
![image](https://user-images.githubusercontent.com/25550534/133888096-6c6c54c0-87c5-42bf-a3ca-6312b7cc62fa.png)

### 期望如何修复

#571 已经进行过一次全文档替换斜体为加粗了，期望可以自动处理（自动任务或者直接在渲染时改效果）。

### 附加信息

虽然和斜体没什么关系，使用 [pangu.js](https://github.com/vinta/pangu.js) 在渲染时为中英之间自动加空格也许值得考虑。

**Comment by CCXXXI** [comment]
另外粗体文本周围加不加空格，看起来没有统一。

**Comment by AlexV525** [comment]
cc @chenglu
