### ISSUE TITLE
#8 - Flutter for React Native devs - 给 React Native 开发者的 Flutter 指南

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#98]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/react-native-devs.md

英文文档预览：https://debug.flutter.cn/docs/get-started/flutter-for/react-native-devs

建议完成时间：10 - 15 天

**Comment by tyisme614** [comment]
认领翻译任务，Yuan

**Comment by chenglu** [comment]
感谢 @tyisme614 的时间和贡献！

**Comment by Jin-zz** [comment]
helo! @tyisme614 目前的翻译进度如何呢，有遇到问题么
翻译完的话可以直接提交 PR 啦 
要是遇到问题的话可以一起讨论看看！再次感谢@tyisme614 ~

**Comment by cfug-dev** [comment]
任务完成，谢谢大家的时间。
