### ISSUE TITLE
[Page issue] 一些页面的链接语法无效

### ISSUE THREAD

**Issue by CCXXXI** [cfug/flutter.cn#981]
<details>
<summary>问题列表</summary>

- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/null-safety.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/whats-new.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/index.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/codelabs/layout-basics.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/effects/gradient-bubbles.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/gestures/handling-taps.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/cookbook/networking/fetch-data.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/deployment/android.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/firebase.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/json.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/data-and-backend/state-mgmt/options.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/developing-packages.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/packages-and-plugins/using-packages.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/c-interop.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/platform-channels.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/platform-integration/web.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/memory.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/tools/devtools/overview.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/assets-and-images.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/widgets-intro.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/hero-animations.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/index.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/animations/overview.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/adaptive-responsive.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/index.md
- [ ] ~~https://github.com/cfug/flutter.cn/blob/master/src/docs/development/ui/layout/responsive.md~~ （已移除）
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/android-devs.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/ios-devs.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/react-native-devs.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/xamarin-forms-devs.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-chromeos.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/install/_get-sdk-linux.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_androidstudio.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/test-drive/_terminal.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/reference/crash-reporting.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/architectural-overview.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/faq.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/resources/videos.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/docs/testing/code-debugging.md
- [x] https://github.com/cfug/flutter.cn/blob/master/src/_includes/docs/dart-tool.md
</details>

ref:
- #965
-  https://gist.github.com/CCXXXI/af4fc7659a0612629ad0eeca460f2cf8
- https://github.github.com/gfm/#reference-link

考虑把检查写进 workflows？

**Comment by AlexV525** [comment]
> 考虑把检查写进 workflows？

可以跑一个实际效果我们看下不？

**Comment by CCXXXI** [comment]
> > 考虑把检查写进 workflows？
> 
> 可以跑一个实际效果我们看下不？最好是能直接定位出错误位置。

https://github.com/CCXXXI/flutter.cn/runs/3712615093?check_suite_focus=true
