### ISSUE TITLE
#10 - Flutter for Xamarin.Forms devs - 给 Xamarin.Forms 开发者的 Flutter 指南

### ISSUE THREAD

**Issue by cfug-dev** [cfug/flutter.cn#99]
Markdown 文件路径：https://github.com/cfug/flutter.cn/blob/master/src/docs/get-started/flutter-for/xamarin-forms-devs.md

英文文档预览：https://debug.flutter.cn/docs/get-started/flutter-for/xamarin-forms-devs

建议完成时间：10 - 15 天

**Comment by ElderJames** [comment]
我可以认领一下这篇文档，我本身是多年.NET栈的开发者，对Xamarin相关的内容或许会有所帮助。预计15天可完成。

**Comment by chenglu** [comment]
谢谢 James @ElderJames ! 辛苦你的时间了，翻译任务已经登记。

**Comment by Jin-zz** [comment]
helo! @ElderJames 翻译完了可以提交 PR 啦，如果是遇到问题了也可以一起讨论看看~
另外请注意一下完成时间哦~辛苦啦~

**Comment by ElderJames** [comment]
@Jin-zz 不好意思，我 之前已经翻译完一半，最近时间有点忙，会尽量抽时间完成。

**Comment by cfug-dev** [comment]
@ElderJames 辛苦啦，感谢您的时间！

**Comment by ElderJames** [comment]
提交pr了 #327

**Comment by chenglu** [comment]
谢谢！
